/* Global Discover views consume canonical projections, never provider APIs. */
(function(root){'use strict';const D=root.VUDiscover,S=root.QuantShell,el=S.el;
 function home(body,ctx){const section=el('section',{class:'v2-world','data-surface':'global-universe'},[el('h2',{text:'Unternehmen weltweit'}),el('p',{class:'v2-world-subtitle',text:'Entdecke Aktien aus den USA, Deutschland und Europa.'})]),filters=el('nav',{'aria-label':'Region filtern',class:'v2-settings-choices'}),track=el('div',{class:'v2-track',role:'list','aria-label':'Unternehmen weltweit'});let region='ALL',cards=[];section.append(filters,el('a',{href:'#/aktien',class:'v2-world-more',text:'Alle Aktien →'}),track);body.append(section);
 function paint(){S.clear(track);cards.filter(c=>region==='ALL'||(region==='DE'?c.country==='DE':c.region===region)).forEach((c,i)=>{const item=el('div',{class:'v2-track-item',role:'listitem'}),tile=D.Views.Home.tile(c,ctx,{position:i,live:false});tile.href=c.href;if(c.logoKey&&D.Logos){const mark=tile.querySelector('.v2-tile-head');if(mark){const previous=mark.firstElementChild;if(previous)previous.replaceWith(D.Logos.mark(c.logoKey,{name:c.companyName,size:'sm'}));}}item.append(tile);track.append(item);});}
 [['ALL','Alle'],['US','USA'],['DE','Deutschland'],['EUROPE','Europa']].forEach(([id,label])=>{const b=el('button',{type:'button',class:'v2-pill',text:label,'aria-pressed':String(id===region)});b.onclick=()=>{region=id;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));paint();};filters.append(b);});
 D.GlobalUniverse.home().then(data=>{if(!section.isConnected)return;cards=data;paint();}).catch(()=>{if(section.isConnected)track.append(el('p',{text:'Die weltweite Auswahl ist derzeit nicht verfügbar. Die Suche bleibt erreichbar.'}));});return section;
 }
 async function browse(root,active){root.append(el('h1',{text:'Alle Aktien'}),el('p',{class:'v2-lead',text:'Unternehmen weltweit. Regionale Filter ändern nicht die globale Suche.'}));let region='ALL',offset=0,token=0;const filters=el('nav',{'aria-label':'Region filtern',class:'v2-settings-choices'}),list=el('div',{class:'v2-watch-list'}),more=el('button',{type:'button',class:'v2-button',text:'Weitere Aktien'});root.append(filters,list,more);
 async function load(reset){const current=++token;more.disabled=true;if(reset){offset=0;S.clear(list);}try{const docs=await D.GlobalUniverse.browse(region,offset,48);if(!active()||token!==current)return;docs.forEach(d=>list.append(el('a',{class:'v2-watch-row',href:d.href,text:d.n+' · '+d.ticker+(d.mic?' · '+d.mic:'')})));offset+=docs.length;more.hidden=docs.length<48;}finally{if(token===current)more.disabled=false;}}
 [['ALL','Alle'],['US','USA'],['DE','Deutschland'],['EUROPE','Europa']].forEach(([id,label])=>{const b=el('button',{type:'button',class:'v2-pill',text:label,'aria-pressed':String(id===region)});b.onclick=()=>{region=id;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));load(true);};filters.append(b);});more.onclick=()=>load(false);await load(true);
 }
 async function watchlist(root,{active,route}){let ids;try{ids=JSON.parse(localStorage.getItem('vu.core.europe.watchlist.v1')||'{}').securityIds;}catch(_){return;}if(!Array.isArray(ids)||!ids.length)return;try{if(!D.europeProduct&&!D.europePublicLoader)await D.GlobalUniverse.ready();if(!D.europeProduct&&D.europePublicLoader)await D.europePublicLoader.connect();if(!active())return;if(!D.europeProduct)throw Error('CANONICAL_WATCHLIST_UNAVAILABLE');const result=await D.europeProduct.saved();if(!active())return;root.querySelectorAll('.v2-lead').forEach(n=>n.remove());let list=root.querySelector('.v2-watch-list');if(!list){list=el('div',{class:'v2-watch-list'});root.append(list);}result.data.members.forEach(m=>{const name=m.name||m.ticker||m.securityId,row=el('div',{class:'v2-watch-row'},[el(m.href?'a':'span',{href:m.href||null,text:name}),el('button',{type:'button',text:'Entfernen','aria-label':name+' aus Watchlist entfernen'})]);row.querySelector('button').onclick=()=>{D.europeProduct.remove(m.securityId);route();};list.append(row);});}catch(_){if(active())root.append(el('p',{text:'Gespeicherte europäische Titel sind derzeit nicht verfügbar.'}));}}
 D.GlobalView={home,browse,watchlist};
})(window);
