import json,csv,re,unicodedata,collections
from pathlib import Path
D=Path(__file__).parent;reference=json.loads((D/'top_europe_reference.json').read_text()); master=list(csv.DictReader(open(D.parent/'endpoints/supported_tickers.csv'))); by=collections.defaultdict(list)
for r in master:by[r['ticker'].upper()].append(r)
# Curated issuer mappings; no same-ticker inference for local symbols.
MAP={'BW LPG':('BWLP','US_ORDINARY'),'Hafnia Limited':('HAFN','US_ORDINARY'),'Liberty Global':('LBTYA','US_ORDINARY'),'Linde plc':('LIN','US_ORDINARY'),'Sunbelt Rentals':('SUNB','US_ORDINARY'),'TechnipFMC':('FTI','US_ORDINARY'),'Transocean':('RIG','US_ORDINARY'),'Teva Pharmaceutical Industries':('TEVA','ADR'),'Lanvin Group':('LANV','US_ORDINARY'),'Wise':('WSE','US_ORDINARY'),'Philips':('PHG','ADR'),'Equinor':('EQNR','ADR'),'Ryanair Holdings':('RYAAY','ADR'),'Frontline':('FRO','US_ORDINARY'),
'Aegon':('AEG','ADR'),'Alcon':('ALC','US_ORDINARY'),'Amrize AG':('AMRZ','US_ORDINARY'),'Anheuser-Busch InBev':('BUD','ADR'),'ArcelorMittal':('MT','US_ORDINARY'),'Argenx':('ARGX','ADR'),'ASML Holding':('ASML','US_ORDINARY'),'AstraZeneca':('AZN','ADR'),'Banco Bilbao Vizcaya Argentaria':('BBVA','ADR'),'Banco Santander':('SAN','ADR'),'Barclays':('BCS','ADR'),'BP':('BP','ADR'),'British American Tobacco':('BTI','ADR'),'Coca-Cola Europacific Partners':('CCEP','US_ORDINARY'),'Deutsche Bank':('DB','US_ORDINARY'),'Diageo':('DEO','ADR'),'Eni':('E','ADR'),'Ericsson':('ERIC','ADR'),'Evotec':('EVO','ADR'),'Ferrari':('RACE','US_ORDINARY'),'Ferrovial':('FER','US_ORDINARY'),'Flutter Entertainment':('FLUT','US_ORDINARY'),'Fresenius Medical Care':('FMS','ADR'),'Genmab':('GMAB','ADR'),'Grifols':('GRFS','ADR'),'GSK plc':('GSK','ADR'),'Haleon':('HLN','ADR'),'HSBC':('HSBC','ADR'),'Indivior':('INDV','US_ORDINARY'),'InterContinental Hotels Group':('IHG','ADR'),'ING Group':('ING','ADR'),'Lloyds Banking Group':('LYG','ADR'),'Logitech':('LOGI','US_ORDINARY'),'National Grid':('NGG','ADR'),'NatWest Group':('NWG','ADR'),'Nokia':('NOK','ADR'),'Novartis':('NVS','ADR'),'Novo Nordisk':('NVO','ADR'),'Pearson':('PSO','ADR'),'Prudential plc':('PUK','ADR'),'Qiagen':('QGEN','US_ORDINARY'),'RELX':('RELX','ADR'),'Rentokil Initial':('RTO','ADR'),'Rio Tinto Group':('RIO','ADR'),'Sanofi':('SNY','ADR'),'SAP':('SAP','ADR'),'Shell plc':('SHEL','ADR'),'Smith & Nephew':('SNN','ADR'),'Stellantis':('STLA','US_ORDINARY'),'STMicroelectronics':('STM','US_ORDINARY'),'Telefónica':('TEF','ADR'),'Tenaris':('TS','ADR'),'TotalEnergies':('TTE','US_SECURITY_FORM_NEEDS_VERIFICATION'),'UBS Group':('UBS','US_ORDINARY'),'Unilever':('UL','ADR'),'Vodafone':('VOD','ADR'),'WPP':('WPP','ADR')}
OTC={'AIXTRON':'AIIXY','AkzoNobel':'AKZOY','ASM International':'ASMIY','Bayer':'BAYRY','E.ON':'EONGY','Mowi':'MHGVY','Norsk Hydro':'NHYDY','Repsol':'REPYY','Subsea 7':'SUBCY','Telia Company':'TLSNY','Vivendi':'VIVHY','Golden Ocean Group':'GOGL','Nestlé':'NSRGY','Roche Holding':'RHHBY','Siemens':'SIEGY','LVMH':'LVMUY','Airbus':'EADSY','Schneider Electric':'SBGSY','Allianz':'ALIZY','BASF':'BASFY','BMW':'BMWYY','Mercedes-Benz Group':'MBGYY','Volkswagen Group':'VWAGY','Adidas':'ADDYY','Iberdrola':'IBDRY','BNP Paribas':'BNPQY','Tencent':'TCEHY','ABB Ltd':'ABBNY','Infineon Technologies':'IFNNY','Hermès':'HESAY','Safran':'SAFRY','Heineken':'HEINY','Dassault Systèmes':'DASTY'}
probes=[];bridge=[];unmatched=[]
for r in reference['companies']:
 name=r['company'];m=next((MAP.get(a) for a in [name]+r.get('aliases',[]) if MAP.get(a)),None)
 row={**r,'localCoverage':'NOT_CONFIRMED','usBridge':None,'otcCandidate':None,'coverageStatus':'NO_USEFUL_US_LISTING_IDENTIFIED','confidence':'CONSERVATIVE_CURATED_MAPPING; not exhaustive ADR directory'}
 if m:
  symbol,form=m;records=by[symbol];row['usBridge']={'symbol':symbol,'securityForm':'UNVERIFIED_CURRENT_FORM','expectedSecurityForm':form,'securityFormBasis':'curated expectation, not current legal-form verification; US listing identity is validated separately','identityBasis':'curated issuer name mapping; validate metadata identity and EOD, never local-symbol equality','providerDiscoveryRecords':records,'apiAvailability':'PENDING_ACCOUNT_PROBE'};row['coverageStatus']='US_BRIDGE_DISCOVERED_PENDING_API';bridge.append(row)
  probes.extend([{'id':f'europe-us-{symbol}-meta','path':f'/tiingo/daily/{symbol.lower()}','params':{},'purpose':f'European issuer US bridge identity: {name}','group':'europe_bridge'},{'id':f'europe-us-{symbol}-prices','path':f'/tiingo/daily/{symbol.lower()}/prices','params':{'startDate':'2026-09-23','endDate':'2026-10-02'},'purpose':f'European issuer US bridge actual current EOD: {name}','group':'europe_bridge'}])
 if name in OTC:
  symbol=OTC[name];row['otcCandidate']={'symbol':symbol,'providerDiscoveryRecords':by[symbol],'countsAsUsefulBridge':False,'reason':'OTC listing is not equivalent to primary local listing; identity, freshness, liquidity and execution constraints require independent validation'}
 if not m:unmatched.append(row)
# Bounded local spelling probes across countries. Bare symbols can collide with unrelated US securities; metadata identity mandatory.
locals=[('SAP.DE','Germany','SAP'),('SIE.DE','Germany','Siemens'),('MC.PA','France','LVMH'),('AIR.PA','France','Airbus'),('ASML.AS','Netherlands','ASML'),('NESN.SW','Switzerland','Nestle'),('AZN.L','United Kingdom','AstraZeneca'),('NOVO-B.CO','Denmark','Novo Nordisk'),('ENI.MI','Italy','Eni'),('IBE.MC','Spain','Iberdrola'),('VOLV-B.ST','Sweden','Volvo'),('EQNR.OL','Norway','Equinor'),('NOKIA.HE','Finland','Nokia'),('OMV.VI','Austria','OMV'),('ABI.BR','Belgium','AB InBev'),('SAP','Germany','SAP (symbol collision: NYSE ADR)'),('AOF','United Kingdom','archived LSE metadata row'),('HYVE','United Kingdom','archived LSE metadata rows')]
for s,c,n in locals:
 probes.extend([{'id':f'europe-local-{s}-meta','path':f'/tiingo/daily/{s.lower()}','params':{},'purpose':f'Local listing probe {c}: {n}; must distinguish USD US listing collision','group':'europe_local'},{'id':f'europe-local-{s}-prices','path':f'/tiingo/daily/{s.lower()}/prices','params':{'startDate':'2026-09-23','endDate':'2026-10-02'},'purpose':f'Actual local EOD probe {c}: {n}','group':'europe_local'}])
for name,s in [(n,OTC[n]) for n in ['Nestlé','Roche Holding','Siemens','LVMH','Airbus','Schneider Electric','Allianz','BASF','BMW','Mercedes-Benz Group','Volkswagen Group','Adidas','Iberdrola','BNP Paribas','Tencent']]:
 probes.extend([{'id':f'europe-otc-{s}-meta','path':f'/tiingo/daily/{s.lower()}','params':{},'purpose':f'Major Europe OTC identity: {name}; not included in strict bridge coverage','group':'europe_otc'},{'id':f'europe-otc-{s}-prices','path':f'/tiingo/daily/{s.lower()}/prices','params':{'startDate':'2026-09-23','endDate':'2026-10-02'},'purpose':f'Major Europe OTC EOD liquidity sample: {name}; not local coverage','group':'europe_otc'}])
(D/'probes-updated.json').write_text(json.dumps({'probes':probes},indent=2)+'\n')
(D/'tiingo_europe_adr_bridge.json').write_text(json.dumps({'asOf':'2026-10-02','referenceTotal':len(reference['companies']),'curatedUsBridgeCandidates':len(bridge),'apiValidatedCovered':None,'importantLimitation':'No mapped listing means no useful bridge IDENTIFIED by conservative curated mapping, not proof that no listing exists. Supported ticker ZIP includes reserved symbols. API proof still required. No OTC candidate counts as strict useful bridge.','companies':bridge+unmatched},indent=2,ensure_ascii=False)+'\n')
print('bridge',len(bridge),'probes',len(probes),'mapped missing references',sorted(set(MAP)-{x['company'] for x in reference['companies']}))
