import json,statistics,argparse
from pathlib import Path
D=Path(__file__).parent;parser=argparse.ArgumentParser();parser.add_argument('evidence',type=Path);args=parser.parse_args();j=json.loads(args.evidence.read_text());out=[]
metadata={}
for response in j['responses']:
 for ref in response.get('references',[]):
  if ref['id'].startswith('europe-otc-') and ref['id'].endswith('-meta') and isinstance(response.get('payload'),dict):metadata[ref['id'][11:-5]]=response['payload']
verified={r['otcCandidate']['symbol']:r['otcCandidate'].get('currentAccountPriceResponseVerified',False) for r in json.loads((D/'tiingo_europe_adr_bridge.json').read_text())['companies'] if r.get('otcCandidate')}
for r in j['responses']:
 refs=[p for p in r['references'] if p['id'].startswith('europe-otc-') and p['id'].endswith('-prices')]
 if not refs:continue
 rows=r.get('payload');rows=rows if isinstance(rows,list) else [];latest=max(rows,key=lambda x:x.get('date','')) if rows else {};dv=[x['close']*x['volume'] for x in rows if isinstance(x.get('close'),(float,int)) and isinstance(x.get('volume'),(float,int))];p=refs[0];symbol=p['id'][11:-7]
 out.append({'symbol':symbol,'geographicClassification':'CHINA_CONTROL_NOT_EUROPE' if symbol=='TCEHY' else ('RECYCLED_SYMBOL_WRONG_INSTRUMENT_CONTROL' if symbol=='GOGL' else 'EUROPEAN_ISSUER_US_OTC'),'providerMetadataName':metadata.get(symbol,{}).get('name'),'providerMetadataExchangeCode':metadata.get(symbol,{}).get('exchangeCode'),'currentEuropeanIssuerIdentityAndPriceVerified':verified.get(symbol,False),'purpose':p['purpose'],'status':r['status'],'bars':len(rows),'positiveVolumeBars':sum((x.get('volume') or 0)>0 for x in rows),'latestDate':latest.get('date'),'latestClose':latest.get('close'),'latestVolume':latest.get('volume'),'sampleMedianApproxUsdDailyTurnover':round(statistics.median(dv),2) if dv else None,'countsAsStrictPrimaryOrLocalBridge':False,'liquidityInterpretation':'Daily close times volume is a rough turnover proxy, not spread/order-depth evidence or equivalence to a local listing. Current-date zero-volume bars can be carry-forward quotes rather than trades.','actualEvidenceUrl':r['url'],'actualEvidenceSha256':r.get('sha256')})
(D/'major_europe_otc_liquidity.json').write_text(json.dumps({'asOf':'2026-10-02','methodology':'Actual current-account seven-session EOD sample; daily close x volume approximate traded value. Separate OTC analysis never added to strict primary-US/local coverage. TCEHY is an explicitly separated China control; GOGL is rejected because current metadata identifies the Corgi GOOGL 2x Daily ETF rather than Golden Ocean despite stale fundamentals identity/activity fields.','europeanOtcNamesTested':sum(x['geographicClassification']=='EUROPEAN_ISSUER_US_OTC' and x['currentEuropeanIssuerIdentityAndPriceVerified'] for x in out),'europeanNamesWithPositiveSampleVolume':sum(x['geographicClassification']=='EUROPEAN_ISSUER_US_OTC' and x['currentEuropeanIssuerIdentityAndPriceVerified'] and x['positiveVolumeBars']>0 for x in out),'observations':out},indent=2)+'\n')
