import csv,json,collections,hashlib
from pathlib import Path
D=Path(__file__).parent;csvpath=D.parent/'endpoints/supported_tickers.csv';rows=list(csv.DictReader(csvpath.open()))
venues=[('XETR','Xetra','Germany',['XETR','XETRA']),('XFRA','Frankfurt','Germany',['XFRA','FRANKFURT']),('XPAR','Euronext Paris','France',['XPAR','EURONEXT PARIS']),('XAMS','Euronext Amsterdam','Netherlands',['XAMS','EURONEXT AMSTERDAM']),('XBRU','Euronext Brussels','Belgium',['XBRU','EURONEXT BRUSSELS']),('XMIL','Borsa Italiana','Italy',['XMIL','MILAN','BORSA ITALIANA']),('XMAD','Madrid','Spain',['XMAD','MADRID']),('XSWX','SIX','Switzerland',['XSWX','SIX','SWISS']),('XLON','LSE','United Kingdom',['XLON','LSE']),('XCSE','Copenhagen','Denmark',['XCSE','COPENHAGEN']),('XSTO','Stockholm','Sweden',['XSTO','STOCKHOLM']),('XOSL','Oslo','Norway',['XOSL','OSLO']),('XHEL','Helsinki','Finland',['XHEL','HELSINKI']),('XWBO','Vienna','Austria',['XWBO','VIENNA']),('XLIS','Lisbon','Portugal',['XLIS','LISBON']),('XICE','Iceland','Iceland',['XICE','ICELAND']),('XDUB','Dublin','Ireland',['XDUB','DUBLIN'])]
results=[]
for mic,name,country,aliases in venues:
 found=[r for r in rows if r['exchange'].upper() in aliases]
 results.append({'mic':mic,'exchange':name,'country':country,'discoveryRecords':len(found),'discoveryDistinctSymbols':len({r['ticker'] for r in found}),'discoveryStatus':'METADATA_ONLY' if found else 'NOT_FOUND','supportedLocalListingsConfirmed':0,'apiStatus':'PENDING_BOUNDED_PROBES; no supported local listing claimed','records':found,'note':'All LSE-tagged rows end in2018–2020 and use USD; duplicate HYVE. They are stale/misassigned catalog entries until identity-and-price evidence proves a local listing.' if found else 'No matching exchange code in the full provider directory. This is discovery evidence, not an exhaustive account endpoint denial.'})
out={'asOf':'2026-10-02','providerDirectoryRows':len(rows),'providerDirectorySha256':hashlib.sha256(csvpath.read_bytes()).hexdigest(),'priceCurrencyCounts':dict(collections.Counter(r['priceCurrency'] for r in rows)),'europeanTradingCurrencyRecords':sum(r['priceCurrency'] in ['EUR','GBP','GBX','CHF','DKK','SEK','NOK','ISK','PLN','HUF','CZK'] for r in rows),'importantLimitations':['Provider catalog includes reservations and is not account entitlement proof.','No EUR/GBP/CHF/Nordic trading currencies found; currency catalog may contain anomalies, so never substitute catalog for actual listing identity.','US ADR/ordinary coverage is tracked separately, never classified as local Europe support.'],'exchanges':results}
(D/'tiingo_europe_exchange_coverage.json').write_text(json.dumps(out,indent=2)+'\n')
print('exchange artifact ready')
