(async function(){
const app=document.querySelector('#app');
const view=document.body.dataset.view||'home';
const pages={home:"<section class='home'><div class='kicker'>VISION UNIVERSE</div><h1>Was möchtest du heute verstehen?</h1><p class='intro'>Unabhängiges Research für fundiertere Anlageentscheidungen.</p><div class='actions'><a class='action' href='/dashboard/research/'><b>Research</b><span>Fundamentale Analyse und Score</span></a><a class='action' href='/dashboard/charting/'><b>Charting</b><span>Kurs, Trend und Szenarien</span></a><a class='action' href='/dashboard/discover/'><b>Entdecken</b><span>Aktien suchen und auswählen</span></a><a class='action' href='/dashboard/watchlist/'><b>Watchlist</b><span>Scores und Kennzahlen vergleichen</span></a></div></section>"};
if(view==='home'){app.innerHTML=pages.home;return;}
let data;try{data=await Promise.all(['config/universe.json','data/fundamental_scores.json','data/research_profiles.json','data/fundamental_metrics.json','data/technical_scores.json','data/market_data.json','data/technical_scenarios.json'].map(function(path){return fetch('/dashboard/'+path).then(function(r){return r.json()})}));}catch(e){app.innerHTML="<p class='notice'>Daten sind derzeit nicht verfügbar.</p>";return;}
const universe=data[0],fundamental=data[1],profiles=data[2],metrics=data[3],technical=data[4],market=data[5],scenarios=data[6],symbol=new URLSearchParams(location.search).get('symbol')||'NVDA';
const stock=universe.stocks.filter(function(x){return x.symbol===symbol})[0]||universe.stocks[0],score=fundamental.symbols[stock.symbol],profile=profiles.symbols[stock.symbol],metric=metrics.symbols[stock.symbol],tech=technical.symbols[stock.symbol];
if(view==='research'){app.innerHTML="<div class='kicker'>Fundamentale Analyse</div><h1 class='heading'>Research</h1><section class='research-grid'><div class='orb'><small>Fundamental Score</small><b>"+score.fundamental_score_beta+"</b><span>/100</span></div><div class='profile'><h2>"+profile.name+"</h2><p>"+profile.summary+"</p><ul>"+profile.highlights.map(function(x){return '<li>✓ '+x+'</li>'}).join('')+"</ul></div></section><section class='scores'>"+[['Quality',score.quality],['Growth',score.growth],['Value',score.value],['Risiko',score.risk],['Momentum',tech.momentum_score_beta],['Timing',tech.timing_score_beta]].map(function(x){return "<div class='score'><span>"+x[0]+"</span><b>"+Math.round(x[1])+"</b></div>"}).join('')+"</section><section class='metrics'>"+[['Umsatzwachstum',metric.revenue_growth],['KGV',metric.pe_ratio],['KUV',metric.ps_ratio],['FCF-Rendite',metric.fcf_yield]].map(function(x){return "<div class='metric'><span>"+x[0]+"</span><b>"+x[1]+"</b></div>"}).join('')+"</section>";return;}
if(view==='watchlist'){app.innerHTML="<div class='kicker'>Universum</div><h1 class='heading'>Watchlist</h1>"+universe.stocks.filter(function(x){return x.active}).sort(function(a,b){return fundamental.symbols[b.symbol].fundamental_score_beta-fundamental.symbols[a.symbol].fundamental_score_beta}).map(function(x){var fs=fundamental.symbols[x.symbol],fm=metrics.symbols[x.symbol];return "<a class='row' href='/dashboard/research/?symbol="+x.symbol+"'><b>"+x.symbol+"</b><span>"+x.name+"</span><strong>"+fs.fundamental_score_beta+"/100</strong><em>KGV "+fm.pe_ratio+" · KUV "+fm.ps_ratio+"</em></a>"}).join('');return;}
if(view==='discover'){app.innerHTML="<div class='kicker'>Universum</div><h1 class='heading'>Entdecken</h1><input class='search' id='search' placeholder='Aktie oder Symbol suchen'><div id='list'></div>";var render=function(term){document.querySelector('#list').innerHTML=universe.stocks.filter(function(x){return x.active&&(x.symbol+x.name).toLowerCase().indexOf(term.toLowerCase())>=0}).map(function(x){return "<a class='row' href='/dashboard/research/?symbol="+x.symbol+"'><b>"+x.symbol+"</b><span>"+x.name+"</span><strong>Research ›</strong></a>"}).join('')};render('');document.querySelector('#search').oninput=function(e){render(e.target.value)};return;}
if(view==='charting'){var rows=market.symbols[stock.symbol].slice(-252),closes=rows.map(function(x){return x.close}),lo=Math.min.apply(null,closes),hi=Math.max.apply(null,closes),pad=(hi-lo)*.04||1,xp=function(i){return 35+i*830/(closes.length-1)},yp=function(v){return 420-(v-(lo-pad))*370/(hi-lo+pad*2)},path=closes.map(function(v,i){return(i?'L':'M')+xp(i).toFixed(1)+' '+yp(v).toFixed(1)}).join(' '),sc=scenarios.symbols[stock.symbol],levels=sc&&sc.status==='beta'?[[sc.entry_zone.low,'#16835b','Einstieg'],[sc.entry_zone.high,'#16835b','Einstieg'],[sc.invalidation,'#d84d43','Invalidierung'],[sc.target_1,'#d9aa12','Ziel 1'],[sc.target_2,'#14b85a','Ziel 2']]:[];app.innerHTML="<div class='kicker'>Technische Analyse β</div><h1 class='heading'>Charting · "+stock.symbol+"</h1><svg class='chart' viewBox='0 0 920 470'><path d='"+path+"' fill='none' stroke='#14b85a' stroke-width='5'/>"+levels.map(function(l){return "<line x1='35' x2='865' y1='"+yp(l[0])+"' y2='"+yp(l[0])+"' stroke='"+l[1]+"' stroke-dasharray='8 6'/><text x='42' y='"+(yp(l[0])-8)+"' fill='"+l[1]+"' font-size='12'>"+l[2]+"</text>"}).join('')+"</svg><p class='notice'>Technisches Szenario β · keine Anlageempfehlung.</p>";return;}
app.innerHTML="<div class='kicker'>"+view+"</div><h1 class='heading'>"+view+"</h1><p class='notice'>Diese Ansicht wird im Rebuild separat ergänzt.</p>";
}());