(function(){
var app=document.getElementById("vu-app");if(!app)return;
var universe,market,technical,active,analysis=false,range=180;
function q(s){return app.querySelector(s)}
function usd(n){return "$"+Number(n).toFixed(2)}
app.innerHTML='<header class="vu-appbar vu-shell"><img class="vu-logo" src="../assets/vision-universe-logo.png" alt="Vision Universe"><span class="vu-mode">Research App · Beta</span></header><main class="vu-shell"><section class="vu-hero"><div class="vu-kicker">Dein Research-Überblick</div><button class="vu-instrument" id="vu-picker"><b id="vu-symbol">—</b><span id="vu-name">Aktie auswählen</span></button><div><span class="vu-price" id="vu-price">—</span><span class="vu-change" id="vu-change"></span></div><div class="vu-sub" id="vu-date">Marktdaten werden geladen …</div></section><div class="vu-tabs" id="vu-tabs"></div><section class="vu-chart-card"><svg class="vu-chart" id="vu-chart" viewBox="0 0 920 470"></svg><div class="vu-controls"><p id="vu-note">Reiner Kursverlauf</p><button class="vu-analysis" id="vu-analysis">Analyse einblenden</button></div></section><section class="vu-section"><h2>Technisches Szenario</h2><p>Orientierung anhand statischer Tagesdaten — keine Handelsempfehlung.</p><div class="vu-scenarios" id="vu-scenarios"></div></section><section class="vu-section"><h2>Entdecken</h2><p>Weitere Werte im VISION-UNIVERSE-Pilotuniversum.</p><div class="vu-pills" id="vu-pills"></div></section></main><nav class="vu-bottom"><button>Übersicht</button><button id="vu-nav-search">Entdecken</button><button>Research</button></nav><div class="vu-sheet" id="vu-sheet"><section class="vu-sheet-inner"><div class="vu-handle"></div><div class="vu-sheet-head"><h2>Aktie wählen</h2><button class="vu-close" id="vu-close">×</button></div><input id="vu-search" class="vu-search" placeholder="Suche nach Aktie oder Symbol"><div id="vu-results"></div></section></div>';
function current(){return market.symbols[active].slice(-range)}
function draw(){
 var rows=current(),prices=rows.map(function(x){return x.close}),low=Math.min.apply(null,prices),high=Math.max.apply(null,prices),padding=(high-low)*.1||1,min=low-padding,max=high+padding;
 function x(i){return 40+i*840/(prices.length-1)}function y(v){return 430-(v-min)*380/(max-min)}
 var path=prices.map(function(v,i){return (i?"L":"M")+x(i).toFixed(1)+" "+y(v).toFixed(1)}).join(" ");
 var html='<line x1="40" y1="70" x2="880" y2="70" stroke="#eee"/><line x1="40" y1="250" x2="880" y2="250" stroke="#eee"/><line x1="40" y1="430" x2="880" y2="430" stroke="#eee"/><path d="'+path+'" fill="none" stroke="#14b85a" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>';
 if(analysis){var score=technical.symbols[active],levels=[[score.sma50,"#e1a400","Unterstützung"],[score.high_52w,"#14b85a","Zielbereich"],[score.sma50*.95,"#d94e43","Invalidierung"]];levels.forEach(function(level){if(level[0]>=min&&level[0]<=max){html+='<line x1="40" y1="'+y(level[0])+'" x2="880" y2="'+y(level[0])+'" stroke="'+level[1]+'" stroke-width="2" stroke-dasharray="7 6"/><text x="48" y="'+(y(level[0])-7)+'" fill="'+level[1]+'" font-size="12" font-weight="700">'+level[2]+' · '+usd(level[0])+'</text>'}})}
 q("#vu-chart").innerHTML=html;q("#vu-note").textContent=analysis?"Ziel-, Unterstützungs- und Invalidierungslevel sichtbar":"Reiner Kursverlauf";
}
function render(){
 var rows=current(),last=rows[rows.length-1],first=rows[0],pct=(last.close/first.close-1)*100,stock=universe.stocks.filter(function(s){return s.symbol===active})[0],score=technical.symbols[active];
 q("#vu-symbol").textContent=active;q("#vu-name").textContent=stock.name+" ›";q("#vu-price").textContent=usd(last.close);q("#vu-change").textContent=(pct>=0?"▲ ":"▼ ")+Math.abs(pct).toFixed(2)+" %";q("#vu-change").style.color=pct>=0?"#14b85a":"#d94e43";q("#vu-date").textContent="Stand "+last.date+" · "+rows.length+" Handelstage";
 q("#vu-tabs").innerHTML=[[30,"1M"],[90,"3M"],[180,"6M"],[252,"1J"],[500,"Max"]].map(function(a){return '<button class="vu-tab '+(range===a[0]?"is-active":"")+'" data-r="'+a[0]+'">'+a[1]+'</button>'}).join("");
 q("#vu-tabs").querySelectorAll("button").forEach(function(b){b.onclick=function(){range=Math.min(Number(b.dataset.r),market.symbols[active].length);render()}});
 q("#vu-scenarios").innerHTML='<article class="vu-scenario vu-scenario--good"><h3>Trend-Fortsetzung</h3><p>Bei Stabilisierung über '+usd(score.close*1.015)+' liegt der technische Zielbereich bei '+usd(score.high_52w)+'.</p></article><article class="vu-scenario"><h3>Rücklauf</h3><p>Die 50-Tage-Linie bei '+usd(score.sma50)+' ist die zentrale Beobachtungszone.</p></article><article class="vu-scenario vu-scenario--risk"><h3>Invalidierung</h3><p>Unter '+usd(score.sma50*.95)+' muss das technische Bild neu bewertet werden.</p></article>';
 q("#vu-pills").innerHTML=universe.stocks.filter(function(s){return s.active}).map(function(s){return '<button class="vu-pill" data-s="'+s.symbol+'">'+s.symbol+'</button>'}).join("");
 q("#vu-pills").querySelectorAll("button").forEach(function(b){b.onclick=function(){active=b.dataset.s;range=180;render();window.scrollTo({top:0,behavior:"smooth"})}});
 draw();
}
function showResults(term){var list=universe.stocks.filter(function(s){return s.active&&(s.symbol+" "+s.name).toLowerCase().indexOf((term||"").toLowerCase())>-1});q("#vu-results").innerHTML=list.map(function(s){return '<button class="vu-result" data-s="'+s.symbol+'"><b>'+s.symbol+'</b><span>'+s.name+'</span></button>'}).join("");q("#vu-results").querySelectorAll("button").forEach(function(b){b.onclick=function(){active=b.dataset.s;range=180;q("#vu-sheet").classList.remove("is-open");render();window.scrollTo({top:0,behavior:"smooth"})}})}
function openSheet(){showResults("");q("#vu-sheet").classList.add("is-open");q("#vu-search").focus()}
q("#vu-picker").onclick=openSheet;q("#vu-nav-search").onclick=openSheet;q("#vu-close").onclick=function(){q("#vu-sheet").classList.remove("is-open")};q("#vu-sheet").onclick=function(e){if(e.target===q("#vu-sheet"))q("#vu-sheet").classList.remove("is-open")};q("#vu-search").oninput=function(e){showResults(e.target.value)};q("#vu-analysis").onclick=function(){analysis=!analysis;this.textContent=analysis?"Analyse ausblenden":"Analyse einblenden";this.classList.toggle("is-on",analysis);draw()};
Promise.all(["config/universe.json","data/market_data.json","data/technical_scores.json"].map(function(url){return fetch(url).then(function(r){if(!r.ok)throw Error("Daten nicht verfügbar");return r.json()})})).then(function(data){universe=data[0];market=data[1];technical=data[2];active=universe.stocks.filter(function(s){return s.active})[0].symbol;render()}).catch(function(){q("#vu-date").textContent="Marktdaten sind momentan nicht verfügbar."});
})();