import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,statSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {projectCompletion,run,OUTPUT_NAMES} from '../build-europe-817-completion.mjs';
const H='b'.repeat(64),SHA='a'.repeat(40),evidence=['private:exact-input-sha256:'+H],clone=v=>structuredClone(v);
const id='lst_XETR_DE0007164600';const ready=()=>({status:'READY',causes:[],evidence});
function fixture(){
 const row={listingId:id,securityId:'sec_isin_DE0007164600',isin:'DE0007164600',mic:'XETR',name:'SAP',currency:'EUR',tradingCurrency:'EUR',companyId:null,referencedIssuerId:'iss_lei_529900ZJSLWMTV9ILO54',indexMemberships:['DAX','TECDAX','EURO_STOXX_50'],mappingStatus:'VERIFIED'};
 const cert={...row,schemaVersion:'europe-history-certification-1.0.0',asOf:'2026-10-07',inputSeriesHash:H,fullHistoryQuality:{bars:300,first:'2025-08-01',last:'2026-10-06',issues:[],quarantinedRowsRetained:0},freshness:{...ready(),state:'FRESH_LAST_VALID_SESSION',latestDate:'2026-10-06',expectedLastSession:'2026-10-06'},technicalFields:{sma20:{...ready(),value:10,inputSeriesHash:H,asOf:'2026-10-06',window:{from:'2026-09-01',to:'2026-10-06'},valueUnit:'LISTING_QUOTE_UNIT'}},splitAdjustedOHLC:ready(),splitAdjustedVolume:{status:'BLOCKED',causes:['UNVERIFIED_VOLUME_BASIS']},totalReturn:{status:'BLOCKED',causes:['UNKNOWN_ADJUSTMENT_BASIS']}};
 const ingestion={...row,providerIdentityMatched:true,history:{state:'AVAILABLE',bars:300,first:'2025-08-01',last:'2026-10-06',inputSeriesHash:H},latest:{date:'2026-10-06'},freshness:{status:'CURRENT'}};
 const product={...row,asOf:'2026-10-07',inputSeriesHash:H,functions:{search:ready(),watchlist:ready(),detail:ready(),chart:ready(),screener:ready(),privateCloseChart:ready(),quantFullScore:{...ready(),population:'US'},supertrader:ready(),publishedBacktest:ready()}};
 return {sourceSHA:SHA,asOf:'2026-10-07',now:'2026-10-07T09:00:00Z',expectedListingCount:1,selectedListingIds:[id],reports:{listingMap:{listings:[row]},ingestion:{listings:[ingestion]},productReadiness:{listings:[product]},logoStatus:{listings:[{listingId:id,status:'EXISTING_FALLBACK',verified:false}]}},certifications:[cert],fundamentals:{listings:[{...row,status:'NONE',causes:['MISSING_FUNDAMENTALS']}]},coreBlockers:{targetCount:29,selectionReferenceDate:'2026-10-06',targets:[]},budget:{requestsAttempted:3712,totalEstimatedCreditsConsumed:3712,ledgerHash:H},sourceArtifacts:[{name:'fixture',sha256:H}],monthlyPatterns:{}};
}
const output=(r,name)=>r.outputs['europe_817_'+name+'.json'].listings[0];
test('14 artifacts, deduplicated index overlaps, technical subset and no public claims',()=>{const i=fixture(),before=JSON.stringify(i),r=projectCompletion(i);assert.equal(JSON.stringify(i),before);assert.deepEqual(Object.keys(r.outputs),OUTPUT_NAMES);assert.equal(output(r,'freshness').status,'FRESH_LAST_VALID_SESSION');assert.equal(output(r,'technical_readiness').status,'TECHNICAL_PARTIAL');assert.equal(output(r,'quant_readiness').status,'QUANT_TECHNICAL_ONLY');assert.equal(output(r,'supertrader_readiness').status,'SUPERTRADER_BLOCKED');assert.equal(output(r,'fundamentals_readiness').status,'FUNDAMENTALS_NONE');for(const x of r.outputs['europe_core_index_status.json'].indexes.filter(x=>!['MDAX','SDAX'].includes(x.index)))assert.equal(x.target,1);assert.equal(r.outputs['europe_refresh_credit_model.json'].additionalCredits,10);for(const f of Object.values(r.outputs))assert.equal(f.publicDisplay,false);});
test('certificate hash drift denies freshness and technicals while actual bars remain visible',()=>{const i=fixture();i.certifications[0].inputSeriesHash='c'.repeat(64);const r=projectCompletion(i);assert.equal(output(r,'technical_readiness').status,'TECHNICAL_BLOCKED');assert.equal(output(r,'freshness').status,'UNKNOWN');assert.equal(output(r,'history_readiness').bars,300);assert.equal(output(r,'chart_readiness').status,'CHART_BLOCKED');});
test('unknown calendar with EOD remains UNKNOWN, proven lower bound can establish stale',()=>{const i=fixture();i.certifications[0].freshness={status:'READY',latestDate:'2026-10-06',evidence};let f=output(projectCompletion(i),'freshness');assert.equal(f.status,'UNKNOWN');assert.equal(f.dataPresent,true);i.certifications[0].freshness={status:'PARTIAL',latestDate:'2026-10-06',lastProvenCompletedSession:'2026-10-07',evidence};f=output(projectCompletion(i),'freshness');assert.equal(f.status,'STALE');assert.equal(f.expectedLastSession,null);});
test('compacted real-producer quarantine allows only bounded close chart, never infers actions',()=>{const i=fixture(),c=i.certifications[0];c.fullHistoryQuality.issues={compacted:true,count:40,sha256:H,sample:[]};c.fullHistoryQuality.quarantinedRowsRetained=40;i.certifications=[{...c,schemaVersion:'private-europe-cache-audit-1.0.0',fullWindow:clone(c),recentWindow:clone(c),chart:{...ready(),state:'CHART_READY_WITH_LIMITATION',asOf:'2026-10-06',dataAsOf:'2026-10-07',inputSeriesHash:H,scope:'ONLY_PROVEN_WINDOW',priceBasis:'RAW',window:{start:'2026-09-01',end:'2026-10-06'}},corporateActionCompleteness:{status:'BLOCKED'},totalReturnDiagnostic:{status:'PARTIAL',engineResult:{state:'TOTAL_RETURN_RECONSTRUCTED'}}}];const r=projectCompletion(i);assert.equal(output(r,'quality').issueCount,40);assert.equal(output(r,'quality').quarantineReleased,0);assert.equal(output(r,'chart_readiness').status,'CHART_READY_WITH_LIMITATION');assert.equal(output(r,'chart_readiness').scope,'ONLY_PROVEN_WINDOW');assert.equal(output(r,'adjustment_status').corporateActionsComplete,false);assert.equal(r.summary.quarantinedRowsRetained,40);});
test('unknown engine field and field hash drift cannot manufacture technical readiness',()=>{const i=fixture();i.certifications[0].technicalFields={invented:{...ready(),inputSeriesHash:H},sma20:{...ready(),value:999,inputSeriesHash:'c'.repeat(64)}};const t=output(projectCompletion(i),'technical_readiness');assert.equal(t.status,'TECHNICAL_BLOCKED');assert.equal(t.fields.sma20.value,null);assert.equal(t.fields.invented,undefined);});
test('unlinked SEC FULL candidate cannot authorize local fundamentals, shares or Quant',()=>{const i=fixture();i.fundamentals.listings[0]={...i.fundamentals.listings[0],status:'FULL',companyId:'iss_cik_0001000184',existingUnverifiedCandidates:[{cik:'0001000184',factsPresent:true}],approvedFundamentalFactors:['revenue']};const r=projectCompletion(i);assert.equal(output(r,'fundamentals_readiness').status,'FUNDAMENTALS_IDENTITY_BLOCKED');assert.deepEqual(output(r,'fundamentals_readiness').approvedFundamentalFactors,[]);assert.notEqual(output(r,'quant_readiness').status,'QUANT_FULL');assert.equal(r.summary.actualLinkedCompanies,0);});
test('wrong-issuer logo never blocks listing; tier 3 needs chart UI proof',()=>{const i=fixture();i.reports.logoStatus.listings[0]={listingId:id,status:'VERIFIED_LOGO',verified:true,referencedIssuerId:'iss_lei_WRONG',asset:'/wrong.svg',evidence};i.reports.productReadiness.listings[0].functions.chart={status:'NOT_TESTED',causes:['PRODUCT_INTEGRATION_MISSING']};const r=projectCompletion(i);assert.equal(output(r,'logo_status').status,'LOGO_FALLBACK');assert.equal(r.outputs['europe_817_product_readiness.json'].listings[0].product.tier,'TIER_1');});
test('denominator, canonical IDs and provider acceptance cannot be forced',()=>{for(const mutate of [i=>i.selectedListingIds.push(id),i=>i.reports.listingMap.listings[0].securityId='ref_SAP',i=>i.reports.ingestion.listings[0].providerIdentityMatched=false,i=>i.expectedListingCount=817]){const i=fixture();mutate(i);assert.throws(()=>projectCompletion(i));}});
test('monthly one versus two-call patterns require actual evidence; hardcap enforced',()=>{const i=fixture();i.budget.totalEstimatedCreditsConsumed=15703;assert.throws(()=>projectCompletion(i),/HARD_CAP/);i.budget.totalEstimatedCreditsConsumed=3712;const mode={activeListings:1,sessionsPerMonth:22,callsPerListingPerSession:1,pagesPerListingPerSession:1,creditsPerListingPerSession:1,metadataCreditsPerMonth:1,corporateActionCreditsPerMonth:0,reserveFraction:0.1,actionScopeDocumented:true,actionScope:'UNSUPPORTED_DEDICATED_ENDPOINT; EMBEDDED_EOD_MONITORING',evidence,observed:{sourceHash:H,requests:10,credits:10,listings:10,pages:10,retries:0,endpointPattern:'ONE_INCREMENTAL_EOD_OVERLAP'}};i.monthlyPatterns={MINIMUM_SAFE:mode,RECOMMENDED:{...mode,callsPerListingPerSession:2,pagesPerListingPerSession:2,creditsPerListingPerSession:2,observed:{...mode.observed,requests:20,credits:20,pages:20,endpointPattern:'SEPARATE_LATEST_AND_HISTORY'}},FULL_REFRESH:{...mode,creditsPerListingPerSession:0.5}};const c=projectCompletion(i).outputs['europe_refresh_credit_model.json'];assert.equal(c.modes.MINIMUM_SAFE.projectedMonthlyCredits,26);assert.equal(c.modes.RECOMMENDED.projectedMonthlyCredits,50);assert.equal(c.modes.FULL_REFRESH.projectedMonthlyCredits,null);assert.equal(c.scheduleActivated,false);assert.equal(c.modes.MINIMUM_SAFE.actionsCompleteCertified,false);});
test('CLI verifies byte hashes, emits private files, rejects drift/symlinks/public repo',()=>{const dir=mkdtempSync(join(tmpdir(),'vu-817-report-'));try{const i=fixture(),dataset=join(dir,'certificates.json'),data=JSON.stringify(i.certifications);writeFileSync(dataset,data);i.datasets={certifications:{path:dataset,sha256:createHash('sha256').update(data).digest('hex')}};delete i.certifications;const input=join(dir,'input.json');writeFileSync(input,JSON.stringify(i));const out=join(dir,'out');run(['--input',input,'--out',out]);assert.equal(statSync(join(out,OUTPUT_NAMES[0])).mode&0o777,0o600);assert.equal(JSON.parse(readFileSync(join(out,'europe_817_completion_manifest.json'))).files.length,17);writeFileSync(dataset,'[]');assert.throws(()=>run(['--input',input,'--out',out]),/HASH_DRIFT/);const linked=join(dir,'linked.json');symlinkSync(input,linked);assert.throws(()=>run(['--input',linked,'--out',out]),/SYMLINK/);assert.throws(()=>run(['--input',input,'--out',join(process.cwd(),'public-report')]),/OUTSIDE_REPOSITORY/);}finally{rmSync(dir,{recursive:true,force:true});}});

test("legacy aggregate ingestion omits securityId safely; wrong explicit ID and future market date denied",()=>{const i=fixture();delete i.reports.ingestion.listings[0].securityId;assert.equal(projectCompletion(i).summary.providerSeries,1);i.reports.ingestion.listings[0].securityId="ref_SAP";assert.throws(()=>projectCompletion(i));delete i.reports.ingestion.listings[0].securityId;i.reports.ingestion.listings[0].latest.date="2026-10-08";assert.equal(output(projectCompletion(i),"freshness").status,"INVALID");});

test('private diagnostic output ownership is registered without a public price artifact',()=>{
 const registry=JSON.parse(readFileSync(new URL('../../../core/registry/domains.json',import.meta.url)));
 const owners=registry.privateGenerators.filter(g=>g.id==='europe817Completion');assert.equal(owners.length,1);
 assert.equal(owners[0].producer,'scripts/marketstack/build-europe-817-completion.mjs');assert.deepEqual(owners[0].artifacts,OUTPUT_NAMES);
 assert.equal(owners[0].publicDisplay,false);assert.equal(owners[0].scheduleActivated,false);
});

test('current quote rejection, missing issuer and malformed engine outputs cannot gain approvals',()=>{
 for(const patch of [{value:null},{value:Infinity},{asOf:'2026-10-05'},{window:{from:'2026-10-07',to:'2026-10-06'}},{valueUnit:null}]){const i=fixture();Object.assign(i.certifications[0].technicalFields.sma20,patch);assert.equal(output(projectCompletion(i),'technical_readiness').readyFields,0);}
 const i=fixture();i.certifications=[{...i.certifications[0],schemaVersion:'private-europe-cache-audit-1.0.0',recentWindow:clone(i.certifications[0]),latestEod:{status:'BLOCKED',state:'INVALID',asOf:'2026-10-06',inputSeriesHash:H,evidence,causes:['MAPPING_ERROR']},researchDiagnostics:[{status:'PARTIAL',inputSeriesHash:H,evidence}]}];
 i.reports.logoStatus.listings[0]={listingId:id,status:'VERIFIED_LOGO',verified:true,asset:'/unbound.png',evidence};
 const r=projectCompletion(i);assert.equal(output(r,'freshness').status,'INVALID');assert.equal(output(r,'logo_status').status,'LOGO_FALLBACK');assert.equal(output(r,'supertrader_readiness').status,'SUPERTRADER_BLOCKED');assert.equal(output(r,'supertrader_readiness').backtest.status,'BLOCKED');
});
test('one proven stale session permits limited chart, older or unproven staleness does not',()=>{
 const i=fixture();i.reports.ingestion.listings[0].latest.date='2026-10-05';i.reports.ingestion.listings[0].history.last='2026-10-05';const c=i.certifications[0];c.freshness={status:'PARTIAL',state:'STALE',latestDate:'2026-10-05',expectedLastSession:'2026-10-06',lagSessions:1,evidence};
 const chart={status:'PARTIAL',state:'CHART_READY_WITH_LIMITATION',asOf:'2026-10-05',dataAsOf:'2026-10-07',expectedLastSession:'2026-10-06',inputSeriesHash:H,window:{start:'2026-09-01',end:'2026-10-05'},scope:'ONLY_PROVEN_WINDOW',lagSessions:1,freshnessPolicy:{maxLagSessions:1},evidence};
 i.certifications=[{...c,schemaVersion:'private-europe-cache-audit-1.0.0',recentWindow:c,chart}];assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_READY_WITH_LIMITATION');
 chart.expectedLastSession='2026-11-09';assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_BLOCKED');chart.expectedLastSession='2026-10-06';chart.asOf='2020-01-01';assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_BLOCKED');chart.asOf='2026-10-05';chart.lagSessions=2;assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_BLOCKED');
});

test('a contradictory wrapper chart never falls back to an unbound legacy approval',()=>{
 const i=fixture(),c=i.certifications[0],cp={status:'BLOCKED',inputSeriesHash:H,asOf:'2026-10-06',dataAsOf:'2026-10-07',window:{start:'2026-09-01',end:'2026-10-06'},evidence};
 i.certifications=[{...c,schemaVersion:'private-europe-cache-audit-1.0.0',recentWindow:c,chart:cp}];
 assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_BLOCKED');
 cp.window=null;cp.causes=['SHORT_HISTORY'];assert.deepEqual(output(projectCompletion(i),'chart_readiness').causes,['SHORT_HISTORY']);
 cp.inputSeriesHash='c'.repeat(64);assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_BLOCKED');
 delete i.certifications[0].chart;assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_BLOCKED');
 Object.assign(i.reports.productReadiness.listings[0].functions.privateCloseChart,{inputSeriesHash:H,asOf:'2026-10-06',dataAsOf:'2026-10-07',window:{start:'2026-09-01',end:'2026-10-06'}});
 assert.equal(output(projectCompletion(i),'chart_readiness').status,'CHART_READY');
});

test('exact ready chart window is independent of older retained quarantine',()=>{const i=fixture(),c=i.certifications[0];c.fullHistoryQuality.quarantinedRowsRetained=40;c.fullHistoryQuality.issues={compacted:true,count:40,sha256:H,sample:[]};i.certifications=[{...c,schemaVersion:'private-europe-cache-audit-1.0.0',fullWindow:clone(c),recentWindow:clone(c),chart:{...ready(),state:'CHART_READY',asOf:'2026-10-06',dataAsOf:'2026-10-07',inputSeriesHash:H,scope:'ONLY_PROVEN_WINDOW',priceBasis:'RAW',window:{start:'2026-09-18',end:'2026-10-06'}}}];const before=JSON.stringify(i),r=projectCompletion(i);assert.equal(output(r,'chart_readiness').status,'CHART_READY');assert.deepEqual(output(r,'chart_readiness').validatedWindow,{start:'2026-09-18',end:'2026-10-06'});assert.equal(r.summary.quarantinedRowsRetained,40);assert.equal(output(r,'quality').quarantineReleased,0);assert.equal(JSON.stringify(i),before);});
