"""Redaktionelle Stammdaten der kuratierten Hedgefonds-Manager.

Alles hier ist KEINE SEC-Angabe, sondern redaktionell gepflegt:
  cik      SEC-Filer-Nummer. Wird bei jedem Lauf gegen den bei der SEC
           hinterlegten Namen geprüft (match). Passt der Name nicht oder
           fehlt die CIK, löst fetch_edgar_data.py die CIK über den
           SEC-Sammeldatensatz (COVERPAGE.tsv) per Namensabgleich neu auf.
  match    Großgeschriebener Namensbestandteil, der im SEC-Filernamen
           vorkommen muss.
  altMatch weitere Namen, unter denen der Fonds heute melden kann
           (z.B. Greenlight Capital -> DME Capital Management).
  manager  bekannteste Person hinter dem Fonds (Gründer/CIO).
  role     Rolle dieser Person heute.
  wiki     Titel des englischen Wikipedia-Artikels; daraus holt das
           Skript ein frei lizenziertes Porträt (Wikimedia Commons) samt
           Urheber und Lizenz. Ohne Treffer zeigt die Seite Initialen.
  style    Anlagestil (Filterchip im Frontend).
  note     optionaler Hinweis, der im Frontend beim Fonds steht.
  photoSearch False = keine Commons-Suche nach dem Namen (zu häufiger
           Name, Verwechslungsgefahr – z.B. „Jeff Smith“).
  optional True = nur aufnehmen, wenn bei der SEC eine 13F-Meldung
           existiert (z.B. deutsche Manager, deren Meldepflicht unklar
           ist). Fehlt sie, wird das nur protokolliert, nicht als Fehler.

Stand der Personalangaben: Oktober 2026.
"""

FUND_META = [
    # --- Star-Investoren / konzentrierte Portfolios --------------------------
    {"slug": "pershing-square", "cik": "0001336528", "match": "PERSHING SQUARE",
     "name": "Pershing Square Capital Management", "manager": "Bill Ackman", "role": "Gründer & CEO",
     "wiki": "Bill_Ackman", "style": "Aktivist",
     "bio": "Aktivistischer Investor mit wenigen, sehr konzentrierten Positionen."},
    {"slug": "berkshire", "cik": "0001067983", "match": "BERKSHIRE HATHAWAY",
     "name": "Berkshire Hathaway", "manager": "Warren Buffett", "role": "Chairman (CEO seit 2026: Greg Abel)",
     "wiki": "Warren_Buffett", "style": "Value",
     "bio": "Die bekannteste Value-Holding der Welt, seit 1965 von Buffett geprägt."},
    {"slug": "scion", "cik": "0001649339", "match": "SCION ASSET",
     "name": "Scion Asset Management", "manager": "Michael Burry", "role": "Gründer",
     "wiki": "Michael_Burry", "style": "Value",
     "bio": "Bekannt aus „The Big Short“. Konträre, oft kurzfristig wechselnde Positionen.",
     "note": "Scion hat Ende 2025 die Registrierung beendet; es kommen keine neuen 13F-Meldungen mehr."},
    {"slug": "appaloosa", "cik": "0001656456", "match": "APPALOOSA",
     "name": "Appaloosa", "manager": "David Tepper", "role": "Gründer & Präsident",
     "wiki": "David_Tepper", "style": "Opportunistisch",
     "bio": "Bekannt für große Wetten auf Erholungen nach Krisen."},
    {"slug": "duquesne", "cik": "0001536411", "match": "DUQUESNE FAMILY OFFICE",
     "name": "Duquesne Family Office", "manager": "Stanley Druckenmiller", "role": "Gründer",
     "wiki": "Stanley_Druckenmiller", "style": "Macro",
     "bio": "Makro-Legende, früher Partner von George Soros. Verwaltet heute eigenes Vermögen."},
    {"slug": "icahn", "cik": "0000921669", "match": "ICAHN",
     "name": "Icahn Capital", "manager": "Carl Icahn", "role": "Gründer",
     "wiki": "Carl_Icahn", "style": "Aktivist",
     "bio": "Einer der ersten und bekanntesten aktivistischen Investoren."},
    {"slug": "third-point", "cik": "0001040273", "match": "THIRD POINT",
     "name": "Third Point", "manager": "Daniel Loeb", "role": "Gründer & CEO",
     "wiki": "Daniel_S._Loeb", "style": "Aktivist",
     "bio": "Event-Driven und Aktivismus, oft mit offenen Briefen an Vorstände."},
    {"slug": "greenlight", "cik": "0001079114", "match": "GREENLIGHT CAPITAL", "altMatch": ["DME CAPITAL"],
     "name": "Greenlight Capital", "manager": "David Einhorn", "role": "Gründer & Präsident",
     "wiki": "David_Einhorn_(hedge_fund_manager)", "style": "Value",
     "bio": "Value-Investor, bekannt für Short-Thesen wie Lehman Brothers."},
    {"slug": "baupost", "cik": "0001061768", "match": "BAUPOST",
     "name": "Baupost Group", "manager": "Seth Klarman", "role": "CEO & Portfoliomanager",
     "wiki": "Seth_Klarman", "style": "Value",
     "bio": "Autor von „Margin of Safety“. Sehr vorsichtiger Value-Ansatz."},
    {"slug": "tci", "cik": "0001647251", "match": "TCI FUND",
     "name": "TCI Fund Management", "manager": "Chris Hohn", "role": "Gründer",
     "wiki": "Christopher_Hohn", "style": "Aktivist",
     "bio": "Konzentriertes Qualitätsportfolio aus London, aktivistisch."},
    {"slug": "himalaya", "cik": "0001709323", "match": "HIMALAYA CAPITAL",
     "name": "Himalaya Capital", "manager": "Li Lu", "role": "Gründer",
     "wiki": "Li_Lu", "style": "Value",
     "bio": "Von Charlie Munger geschätzter Value-Investor mit wenigen Positionen."},
    {"slug": "dalal-street", "cik": "0001549575", "match": "DALAL STREET",
     "name": "Pabrai Investment Funds (Dalal Street)", "manager": "Mohnish Pabrai", "role": "Gründer",
     "wiki": "Mohnish_Pabrai", "style": "Value",
     "bio": "Buffett-Schüler, sehr konzentriert, oft Tiefwert-Aktien."},
    {"slug": "hh-international", "cik": "0001759760", "match": "H&H INTERNATIONAL",
     "name": "H&H International Investment", "manager": "Duan Yongping", "role": "Gründer",
     "wiki": "Duan_Yongping", "style": "Value",
     "bio": "Gründer von BBK (Oppo, Vivo), langfristiger Investor in Apple."},
    {"slug": "fairfax", "cik": "0000915191", "match": "FAIRFAX FINANCIAL",
     "name": "Fairfax Financial", "manager": "Prem Watsa", "role": "Gründer & Chairman",
     "wiki": "Prem_Watsa", "style": "Value",
     "bio": "„Kanadas Warren Buffett“, Versicherungsholding mit Value-Portfolio."},
    {"slug": "markel", "cik": "0001096343", "match": "MARKEL",
     "name": "Markel Group", "manager": "Tom Gayner", "role": "CEO",
     "wiki": "Tom_Gayner", "style": "Value",
     "bio": "Versicherer mit Buffett-ähnlichem Aktienportfolio."},
    {"slug": "akre", "cik": "0001112520", "match": "AKRE CAPITAL",
     "name": "Akre Capital Management", "manager": "Chuck Akre", "role": "Gründer",
     "wiki": "Chuck_Akre", "style": "Qualität",
     "bio": "„Dreibeiniger Hocker“: Qualität, Management, Reinvestition."},
    {"slug": "fundsmith", "cik": "0001569205", "match": "FUNDSMITH",
     "name": "Fundsmith", "manager": "Terry Smith", "role": "Gründer & CEO",
     "wiki": "Terry_Smith_(businessman)", "style": "Qualität",
     "bio": "„Kaufe gute Unternehmen, zahle nicht zu viel, tue nichts.“"},
    {"slug": "gotham", "cik": "0001510387", "match": "GOTHAM ASSET",
     "name": "Gotham Asset Management", "manager": "Joel Greenblatt", "role": "Co-CIO",
     "wiki": "Joel_Greenblatt", "style": "Value",
     "bio": "Erfinder der „Magic Formula“, heute breit gestreut."},
    {"slug": "oaktree", "cik": "0000949509", "match": "OAKTREE CAPITAL",
     "name": "Oaktree Capital Management", "manager": "Howard Marks", "role": "Co-Chairman",
     "wiki": "Howard_Marks_(investor)", "style": "Distressed",
     "bio": "Spezialist für Krisen- und Kreditinvestments, bekannt für seine Memos."},
    {"slug": "fairholme", "cik": "0001056831", "match": "FAIRHOLME",
     "name": "Fairholme Capital Management", "manager": "Bruce Berkowitz", "role": "Gründer & CIO",
     "wiki": "Bruce_Berkowitz", "style": "Value",
     "bio": "Extrem konzentrierter Value-Investor."},
    {"slug": "trian", "cik": "0001345471", "match": "TRIAN FUND",
     "name": "Trian Fund Management", "manager": "Nelson Peltz", "role": "Gründer & CEO",
     "wiki": "Nelson_Peltz", "style": "Aktivist",
     "bio": "Aktivist mit Fokus auf große Konsum- und Industriekonzerne."},
    {"slug": "starboard", "photoSearch": False, "cik": "0001517137", "match": "STARBOARD VALUE",
     "name": "Starboard Value", "manager": "Jeff Smith", "role": "Gründer & CIO",
     "wiki": "Jeffrey_C._Smith", "style": "Aktivist",
     "bio": "Einer der aktivsten US-Aktivisten, oft mit Kampfabstimmungen."},
    {"slug": "elliott", "cik": "0001791786", "match": "ELLIOTT INVESTMENT",
     "name": "Elliott Investment Management", "manager": "Paul Singer", "role": "Gründer & Co-CEO",
     "wiki": "Paul_Singer_(businessman)", "style": "Aktivist",
     "bio": "Größter aktivistischer Hedgefonds der Welt."},
    {"slug": "jana", "cik": "0001159159", "match": "JANA PARTNERS",
     "name": "Jana Partners", "manager": "Barry Rosenstein", "role": "Gründer",
     "wiki": "Barry_Rosenstein", "style": "Aktivist",
     "bio": "Aktivistischer Fonds mit Fokus auf Mid Caps."},
    {"slug": "sachem-head", "cik": "0001582090", "match": "SACHEM HEAD",
     "name": "Sachem Head Capital", "manager": "Scott Ferguson", "role": "Gründer",
     "wiki": None, "style": "Aktivist",
     "bio": "Aktivist aus der Schule von Bill Ackman."},
    {"slug": "abrams", "cik": "0001358706", "match": "ABRAMS CAPITAL",
     "name": "Abrams Capital Management", "manager": "David Abrams", "role": "Gründer",
     "wiki": None, "style": "Value",
     "bio": "Zurückhaltender, sehr konzentrierter Value-Investor aus Boston."},
    {"slug": "ark", "cik": "0001697748", "match": "ARK INVESTMENT",
     "name": "ARK Investment Management", "manager": "Cathie Wood", "role": "Gründerin & CEO",
     "wiki": "Cathie_Wood", "style": "Wachstum",
     "bio": "Disruptive Innovation: KI, Robotik, Genomik, Krypto."},
    {"slug": "gates-foundation", "cik": "0001166559", "match": "GATES FOUNDATION",
     "name": "Bill & Melinda Gates Foundation Trust", "manager": "Bill Gates", "role": "Stifter",
     "wiki": "Bill_Gates", "style": "Stiftung",
     "bio": "Stiftungsvermögen, verwaltet von Cascade; großer Anteil Berkshire und Microsoft."},
    # --- Tiger Cubs / Growth ------------------------------------------------
    {"slug": "tiger-global", "cik": "0001167483", "match": "TIGER GLOBAL",
     "name": "Tiger Global Management", "manager": "Chase Coleman", "role": "Gründer",
     "wiki": "Chase_Coleman_III", "style": "Wachstum",
     "bio": "„Tiger Cub“ von Julian Robertson, Tech- und Growth-Fokus."},
    {"slug": "coatue", "cik": "0001135730", "match": "COATUE",
     "name": "Coatue Management", "manager": "Philippe Laffont", "role": "Gründer",
     "wiki": "Philippe_Laffont", "style": "Wachstum",
     "bio": "Tech-Spezialist, früher bei Tiger Management."},
    {"slug": "lone-pine", "cik": "0001061165", "match": "LONE PINE",
     "name": "Lone Pine Capital", "manager": "Stephen Mandel", "role": "Gründer",
     "wiki": "Stephen_Mandel", "style": "Long/Short",
     "bio": "Tiger Cub mit Qualitäts- und Wachstumsaktien."},
    {"slug": "viking", "cik": "0001103804", "match": "VIKING GLOBAL",
     "name": "Viking Global Investors", "manager": "Andreas Halvorsen", "role": "Gründer",
     "wiki": "Andreas_Halvorsen", "style": "Long/Short",
     "bio": "Tiger Cub, fundamentale Long/Short-Strategie."},
    {"slug": "maverick", "cik": "0000934639", "match": "MAVERICK CAPITAL",
     "name": "Maverick Capital", "manager": "Lee Ainslie", "role": "Gründer",
     "wiki": "Lee_Ainslie", "style": "Long/Short",
     "bio": "Tiger Cub aus Dallas."},
    {"slug": "altimeter", "cik": "0001541617", "match": "ALTIMETER",
     "name": "Altimeter Capital", "manager": "Brad Gerstner", "role": "Gründer & CEO",
     "wiki": "Brad_Gerstner", "style": "Wachstum",
     "bio": "Tech-Investor mit großen Positionen in Plattform- und KI-Werten."},
    {"slug": "d1", "cik": "0001747057", "match": "D1 CAPITAL",
     "name": "D1 Capital Partners", "manager": "Dan Sundheim", "role": "Gründer",
     "wiki": "Dan_Sundheim", "style": "Long/Short",
     "bio": "Früherer CIO von Viking, gemischte Public- und Private-Strategie."},
    {"slug": "situational-awareness", "cik": None, "match": "SITUATIONAL AWARENESS",
     "name": "Situational Awareness", "manager": "Leopold Aschenbrenner", "role": "Gründer",
     "wiki": "Leopold_Aschenbrenner", "style": "Wachstum",
     "bio": "Junger KI-fokussierter Fonds eines früheren OpenAI-Forschers."},
    # --- Macro ---------------------------------------------------------------
    {"slug": "bridgewater", "cik": "0001350694", "match": "BRIDGEWATER",
     "name": "Bridgewater Associates", "manager": "Ray Dalio", "role": "Gründer (seit 2025 ohne Anteil)",
     "wiki": "Ray_Dalio", "style": "Macro",
     "bio": "Größter Macro-Fonds der Welt; heute von Co-CIOs geführt."},
    {"slug": "soros", "cik": "0001029160", "match": "SOROS FUND",
     "name": "Soros Fund Management", "manager": "George Soros", "role": "Gründer (CIO: Dawn Fitzpatrick)",
     "wiki": "George_Soros", "style": "Macro",
     "bio": "Family Office des „Mannes, der die Bank of England brach“."},
    {"slug": "tudor", "cik": "0000923093", "match": "TUDOR INVESTMENT",
     "name": "Tudor Investment Corp", "manager": "Paul Tudor Jones", "role": "Gründer",
     "wiki": "Paul_Tudor_Jones", "style": "Macro",
     "bio": "Makro-Trader, bekannt für die Vorhersage des Crashs von 1987."},
    {"slug": "paulson", "cik": "0001035674", "match": "PAULSON",
     "name": "Paulson & Co.", "manager": "John Paulson", "role": "Gründer",
     "wiki": "John_Paulson", "style": "Event-Driven",
     "bio": "Berühmt durch die Wette gegen den US-Immobilienmarkt 2007."},
    # --- Multi-Strategy & Quant ----------------------------------------------
    {"slug": "citadel", "cik": "0001423053", "match": "CITADEL ADVISORS",
     "name": "Citadel Advisors", "manager": "Ken Griffin", "role": "Gründer & CEO",
     "wiki": "Kenneth_C._Griffin", "style": "Multi-Strategy",
     "bio": "Einer der erfolgreichsten Multi-Strategy-Fonds der Geschichte."},
    {"slug": "millennium", "cik": "0001273087", "match": "MILLENNIUM MANAGEMENT",
     "name": "Millennium Management", "manager": "Israel Englander", "role": "Gründer & CEO",
     "wiki": "Israel_Englander", "style": "Multi-Strategy",
     "bio": "Plattform mit hunderten unabhängigen Portfolio-Teams."},
    {"slug": "point72", "cik": "0001603466", "match": "POINT72",
     "name": "Point72 Asset Management", "manager": "Steven A. Cohen", "role": "Gründer & CEO",
     "wiki": "Steve_Cohen_(businessman)", "style": "Multi-Strategy",
     "bio": "Nachfolger von SAC Capital, Eigentümer der New York Mets."},
    {"slug": "balyasny", "cik": "0001218710", "match": "BALYASNY",
     "name": "Balyasny Asset Management", "manager": "Dmitry Balyasny", "role": "Gründer",
     "wiki": None, "style": "Multi-Strategy",
     "bio": "Multi-Strategy-Plattform aus Chicago."},
    {"slug": "marshall-wace", "cik": "0001318757", "match": "MARSHALL WACE",
     "name": "Marshall Wace", "manager": "Paul Marshall", "role": "Mitgründer",
     "wiki": "Paul_Marshall_(investor)", "style": "Long/Short",
     "bio": "Einer der größten europäischen Hedgefonds."},
    {"slug": "de-shaw", "cik": "0001009207", "match": "SHAW",
     "name": "D. E. Shaw & Co.", "manager": "David E. Shaw", "role": "Gründer",
     "wiki": "David_E._Shaw", "style": "Quant",
     "bio": "Pionier des computergestützten Handels."},
    {"slug": "two-sigma", "cik": "0001179392", "match": "TWO SIGMA INVESTMENTS",
     "name": "Two Sigma Investments", "manager": "John Overdeck & David Siegel", "role": "Gründer",
     "wiki": "John_Overdeck", "style": "Quant",
     "bio": "Datengetriebener Quant-Fonds aus New York."},
    {"slug": "renaissance", "cik": "0001037389", "match": "RENAISSANCE TECHNOLOGIES",
     "name": "Renaissance Technologies", "manager": "Jim Simons (†2024)", "role": "Gründer (CEO: Peter Brown)",
     "wiki": "Jim_Simons", "style": "Quant",
     "bio": "Legendärer Quant-Fonds; der Medallion Fund gilt als erfolgreichster aller Zeiten."},
    {"slug": "aqr", "cik": "0001167557", "match": "AQR CAPITAL",
     "name": "AQR Capital Management", "manager": "Cliff Asness", "role": "Gründer & CIO",
     "wiki": "Cliff_Asness", "style": "Quant",
     "bio": "Faktor-Investing (Value, Momentum, Qualität) im großen Stil."},
    {"slug": "man-group", "photoSearch": False, "cik": "0001637460", "match": "MAN GROUP",
     "name": "Man Group", "manager": "Robyn Grew", "role": "CEO",
     "wiki": None, "style": "Quant",
     "bio": "Börsennotierter britischer Hedgefonds-Konzern (u. a. Man AHL)."},
    {"slug": "saba", "cik": "0001510281", "match": "SABA CAPITAL",
     "name": "Saba Capital Management", "manager": "Boaz Weinstein", "role": "Gründer & CIO",
     "wiki": "Boaz_Weinstein", "style": "Event-Driven",
     "bio": "Kredit- und Closed-End-Fonds-Aktivist."},
    {"slug": "fisher", "cik": "0000850529", "match": "FISHER ASSET",
     "name": "Fisher Asset Management", "manager": "Ken Fisher", "role": "Gründer & Chairman",
     "wiki": "Kenneth_Fisher", "style": "Wachstum",
     "bio": "Großer Vermögensverwalter, Kolumnist und Buchautor."},

    # --- Zweite Reihe: bekannte Stock-Picker, CIK über den Sammeldatensatz --
    {"slug": "valueact", "cik": None, "match": "VALUEACT", "name": "ValueAct Capital",
     "manager": "Mason Morfit", "role": "CEO & CIO", "wiki": "Mason_Morfit", "style": "Aktivist",
     "bio": "Konstruktiver Aktivist, oft mit Sitz im Aufsichtsgremium."},
    {"slug": "glenview", "cik": None, "match": "GLENVIEW CAPITAL", "name": "Glenview Capital",
     "manager": "Larry Robbins", "role": "Gründer & CEO", "wiki": None, "style": "Long/Short",
     "bio": "Fundamentaler Fonds mit Schwerpunkt Gesundheitswesen."},
    {"slug": "lindsell-train", "cik": None, "match": "LINDSELL TRAIN", "name": "Lindsell Train",
     "manager": "Nick Train", "role": "Mitgründer", "wiki": "Nick_Train", "style": "Qualität",
     "bio": "Britischer Qualitätsinvestor mit sehr langen Haltedauern."},
    {"slug": "atreides", "cik": None, "match": "ATREIDES", "name": "Atreides Management",
     "manager": "Gavin Baker", "role": "Gründer & CIO", "wiki": None, "style": "Wachstum",
     "bio": "Tech- und Halbleiter-Spezialist, früher Fidelity OTC Fund."},
    {"slug": "whale-rock", "cik": None, "match": "WHALE ROCK", "name": "Whale Rock Capital",
     "manager": "Alex Sacerdote", "role": "Gründer", "wiki": None, "style": "Wachstum",
     "bio": "Technologie-fokussierter Long/Short-Fonds."},
    {"slug": "durable", "cik": None, "match": "DURABLE CAPITAL", "name": "Durable Capital Partners",
     "manager": "Henry Ellenbogen", "role": "Gründer & CIO", "wiki": None, "style": "Wachstum",
     "bio": "Langfristige Wachstumsinvestments, früher T. Rowe Price."},
    {"slug": "light-street", "cik": None, "match": "LIGHT STREET", "name": "Light Street Capital",
     "manager": "Glen Kacher", "role": "Gründer & CIO", "wiki": None, "style": "Wachstum",
     "bio": "Tiger-Cub-Schüler mit Tech-Fokus."},
    {"slug": "egerton", "photoSearch": False, "cik": None, "match": "EGERTON", "name": "Egerton Capital",
     "manager": "John Armitage", "role": "Gründer", "wiki": None, "style": "Long/Short",
     "bio": "Konzentrierter Qualitäts-Stock-Picker aus London."},
    {"slug": "lansdowne", "photoSearch": False, "cik": None, "match": "LANSDOWNE PARTNERS", "name": "Lansdowne Partners",
     "manager": "Peter Davies", "role": "Senior Partner", "wiki": None, "style": "Long/Short",
     "bio": "Einer der traditionsreichsten Londoner Hedgefonds."},
    {"slug": "cantillon", "cik": None, "match": "CANTILLON", "name": "Cantillon Capital",
     "manager": "William von Mueffling", "role": "Gründer & CIO", "wiki": None, "style": "Qualität",
     "bio": "Globale Qualitätsaktien mit wenigen Positionen."},
    {"slug": "valley-forge", "cik": None, "match": "VALLEY FORGE CAPITAL", "name": "Valley Forge Capital",
     "manager": "Dev Kantesaria", "role": "Gründer", "wiki": None, "style": "Qualität",
     "bio": "Hochkonzentriert in Monopol-ähnlichen Geschäftsmodellen."},
    {"slug": "brave-warrior", "cik": None, "match": "BRAVE WARRIOR", "name": "Brave Warrior Advisors",
     "manager": "Glenn Greenberg", "role": "Gründer", "wiki": None, "style": "Value",
     "bio": "Value-Investor mit sehr wenigen, großen Positionen."},
    {"slug": "semper-augustus", "cik": None, "match": "SEMPER AUGUSTUS", "name": "Semper Augustus",
     "manager": "Christopher Bloomstran", "role": "Gründer & CIO", "wiki": None, "style": "Value",
     "bio": "Bekannt für ausführliche Jahresbriefe, großer Berkshire-Anteil."},
    {"slug": "giverny", "cik": None, "match": "GIVERNY CAPITAL", "name": "Giverny Capital",
     "manager": "François Rochon", "role": "Gründer", "wiki": None, "style": "Qualität",
     "bio": "Kanadischer Qualitätsinvestor."},
    {"slug": "gardner-russo", "photoSearch": False, "cik": None, "match": "GARDNER RUSSO", "name": "Gardner Russo & Quinn",
     "manager": "Tom Russo", "role": "Partner", "wiki": None, "style": "Value",
     "bio": "Globale Markenkonzerne, sehr lange Haltedauern."},
    {"slug": "ruane", "photoSearch": False, "cik": None, "match": "RUANE", "name": "Ruane, Cunniff & Goldfarb",
     "manager": "Sequoia Fund", "role": "Fondsgesellschaft", "wiki": None, "style": "Value",
     "bio": "Verwalter des legendären Sequoia Fund (Buffett-Empfehlung 1969)."},
    {"slug": "gamco", "cik": None, "match": "GAMCO INVESTORS", "name": "GAMCO Investors",
     "manager": "Mario Gabelli", "role": "Gründer & CEO", "wiki": "Mario_Gabelli", "style": "Value",
     "bio": "Private-Market-Value-Ansatz mit sehr breitem Portfolio."},
    {"slug": "harris", "photoSearch": False, "cik": None, "match": "HARRIS ASSOCIATES", "name": "Harris Associates (Oakmark)",
     "manager": "Bill Nygren", "role": "CIO US-Aktien", "wiki": None, "style": "Value",
     "bio": "Verwalter der Oakmark-Fonds."},
    {"slug": "davis", "photoSearch": False, "cik": None, "match": "DAVIS SELECTED", "name": "Davis Selected Advisers",
     "manager": "Chris Davis", "role": "Chairman", "wiki": None, "style": "Value",
     "bio": "Familiengeführter Value-Verwalter (Davis New York Venture)."},
    {"slug": "miller-value", "cik": None, "match": "MILLER VALUE", "name": "Miller Value Partners",
     "manager": "Bill Miller", "role": "Gründer", "wiki": "Bill_Miller_(investor)", "style": "Value",
     "bio": "Schlug den S&P 500 15 Jahre in Folge."},
    {"slug": "yacktman", "cik": None, "match": "YACKTMAN", "name": "Yacktman Asset Management",
     "manager": "Stephen Yacktman", "role": "CIO", "wiki": None, "style": "Value",
     "bio": "Qualitäts-Value mit Fokus auf Konsumgüter."},
    {"slug": "weitz", "photoSearch": False, "cik": None, "match": "WEITZ", "name": "Weitz Investment Management",
     "manager": "Wally Weitz", "role": "Gründer", "wiki": None, "style": "Value",
     "bio": "Value-Investor aus Omaha."},
    {"slug": "jericho", "cik": None, "match": "JERICHO CAPITAL", "name": "Jericho Capital",
     "manager": "Josh Resnick", "role": "Gründer", "wiki": None, "style": "Wachstum",
     "bio": "Tech-, Medien- und Telekom-Spezialist."},
    {"slug": "discovery", "cik": None, "match": "DISCOVERY CAPITAL", "name": "Discovery Capital Management",
     "manager": "Rob Citrone", "role": "Gründer", "wiki": None, "style": "Macro",
     "bio": "Tiger-Cub mit Schwerpunkt Schwellenländer und Macro."},
    # --- Deutschland / DACH: nur falls bei der SEC gemeldet -----------------
    {"slug": "bit-capital", "cik": None, "match": "BIT CAPITAL", "name": "BIT Capital",
     "manager": "Jan Beckers", "role": "Gründer", "wiki": "Jan_Beckers", "style": "Wachstum",
     "bio": "Berliner Tech-Investor (BIT Global Technology Leaders).", "optional": True, "region": "DE"},
    {"slug": "freigeist", "cik": None, "match": "FREIGEIST", "altMatch": ["10XDNA"], "name": "Freigeist / 10xDNA",
     "manager": "Frank Thelen", "role": "Gründer", "wiki": "Frank_Thelen", "style": "Wachstum",
     "bio": "Tech-Investor, bekannt aus „Die Höhle der Löwen“.", "optional": True, "region": "DE"},
    {"slug": "flossbach", "cik": None, "match": "FLOSSBACH", "name": "Flossbach von Storch",
     "manager": "Bert Flossbach", "role": "Gründer", "wiki": "Bert_Flossbach", "style": "Qualität",
     "bio": "Größter bankenunabhängiger Vermögensverwalter Deutschlands.", "optional": True, "region": "DE"},
    {"slug": "acatis", "cik": None, "match": "ACATIS", "name": "ACATIS Investment",
     "manager": "Hendrik Leber", "role": "Gründer", "wiki": "Hendrik_Leber", "style": "Value",
     "bio": "Frankfurter Value-Investor.", "optional": True, "region": "DE"},
    {"slug": "dje", "cik": None, "match": "DJE KAPITAL", "name": "DJE Kapital",
     "manager": "Jens Ehrhardt", "role": "Gründer", "wiki": "Jens_Ehrhardt", "style": "Value",
     "bio": "Münchner Vermögensverwalter, Dr. Jens Ehrhardt.", "optional": True, "region": "DE"},
    {"slug": "shareholder-value", "cik": None, "match": "SHAREHOLDER VALUE MANAGEMENT", "name": "Shareholder Value Management",
     "manager": "Frank Fischer", "role": "Vorstand & CIO", "wiki": None, "style": "Value",
     "bio": "Frankfurter Value-Investor (Frankfurter Aktienfonds für Stiftungen).", "optional": True, "region": "DE"},
]
