import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateCloseChart } from '../../../scripts/marketstack/europe-discover-chart-quality.mjs';
const sha='a'.repeat(64), alt='b'.repeat(64);
const listing={listingKey:'marketstack:XETR:SAP.DE',mic:'XETR',providerSymbol:'SAP.DE',isin:'DE0007164600',currency:'EUR',quoteUnit:'EUR',quoteBasis:{kind:'OFFICIAL_LISTING_QUOTE_REFERENCE',mic:'XETR',providerSymbol:'SAP.DE',isin:'DE0007164600',currency:'EUR',quoteUnit:'EUR',sourceSha256:sha}};
const sessions=[];for(let t=Date.parse('2025-08-01');t<=Date.parse('2026-10-12');t+=86400000){const d=new Date(t);if(![0,6].includes(d.getUTCDay()))sessions.push({date:d.toISOString().slice(0,10),close:d.toISOString().slice(0,10)+'T16:00:00Z'});}
const calendar={verified:true,mic:'XETR',source:'independent-test-schedule',sessions};
function row(date,close=100,id=sha){return {raw:{date:date+'T00:00:00Z',symbol:'SAP.DE',exchange:'XETR',close,price_currency:null},normalized:{providerTicker:'SAP.DE',providerExchange:'XETR',tradingDate:date,close,currency:null},provenance:{normalizedSha256:id,rawSha256:sha,rawResponseId:'000001',responses:[{id:'000001',sha256:sha,status:200,endpoint:'/eod',params:{symbols:'SAP.DE',exchange:'XETR',date_from:'2025-08-01',date_to:'2026-10-09'}}]}};}
const rows=sessions.filter(s=>s.date>='2025-10-10'&&s.date<='2026-10-09').map((s,i)=>row(s.date,100+i/100));
const call=(o={})=>evaluateCloseChart({listing,observations:rows,calendar,now:'2026-10-10T07:00:00Z',excludedQuarantineDates:[],...o});
test('Close-only full-year chart works without OHLC volume actions adjustments or Technical certification',()=>{const r=call();assert.equal(r.chartStatus,'CHART_READY');assert.equal(r.freshness,'CURRENT_LAST_SESSION');assert.equal(r.points.length,261);assert.equal(r.points.at(-1)[0],'2026-10-09');assert.equal(r.technicalCertified,false);assert.equal(r.adjustmentCertified,false);assert.equal(r.publicationAllowed,false);assert.equal(r.priceBasis,'RAW_UNADJUSTED');});
test('ALL prior quarantines remain excluded even when a positive Close would otherwise be accepted',()=>{const r=call({excludedQuarantineDates:['2026-03-10']});assert(!r.points.some(p=>p[0]==='2026-03-10'));assert.equal(r.rejectedObservations[0].originalObservation,rows.find(r=>r.normalized.tradingDate==='2026-03-10'));assert.equal(r.chartStatus,'CHART_LIMITED');assert(r.pointRecords.find(r=>r.date==='2026-03-11').breakBefore);assert.equal(r.segments.length,2);});
test('within-operation duplicated dates and contrary distinct-operation Close observations block',()=>{let r=call({observations:[...rows,row('2026-10-09',102.6)]});assert.equal(r.chartStatus,'CHART_BLOCKED');assert(r.criticalIssues.some(i=>i.code==='DUPLICATE_OR_CONFLICTING_DATE'));r=call({observations:[...rows,row('2026-10-09',900,alt)]});assert.equal(r.chartStatus,'CHART_BLOCKED');});
test('coherent distinct-operation observations retain both source bindings without manufacturing a point',()=>{const r=call({observations:[...rows,row('2026-10-09',102.6,alt)]});assert.equal(r.points.length,261);assert.equal(r.pointRecords.at(-1).sourceBindings.length,2);assert.equal(r.chartStatus,'CHART_READY');});
test('malformed currency declarations and unproven quote units fail closed',()=>{for(const v of [false,0,'','USD']){const altered=structuredClone(rows);altered.at(-1).raw.price_currency=v;assert(!call({observations:altered}).points.some(p=>p[0]==='2026-10-09'));}const l={...listing,currency:'GBP',quoteUnit:'GBP',quoteBasis:{...listing.quoteBasis,currency:'GBP',quoteUnit:'GBP'}};assert.equal(call({listing:l}).chartStatus,'CHART_BLOCKED');});
test('exact symbol/MIC and origin request range guard each retained source',()=>{for(const mutate of [r=>r.raw.symbol='WRONG',r=>r.raw.exchange='XNAS',r=>r.provenance.responses[0].params.exchange='XNAS']){const altered=structuredClone(rows);mutate(altered.at(-1));assert(!call({observations:altered}).points.some(p=>p[0]==='2026-10-09'));}const r=call({sourceRequestRanges:{[sha]:{from:'2026-10-09',to:'2026-10-09'}}});assert.equal(r.points.length,1);assert.equal(r.chartStatus,'CHART_BLOCKED');assert(r.rejectedObservations.some(r=>r.reasonCodes.includes('OUTSIDE_REQUESTED_RANGE')));});
test('future and non-session rows are rejected without moving dates',()=>{const r=call({observations:[...rows,row('2026-10-10'),row('2026-10-12')]});assert.equal(r.points.length,261);assert.equal(r.rejectedObservations.length,2);assert(r.rejectedObservations.every(r=>r.reasonCodes.includes('NON_SESSION_OR_UNCOMPLETED_DATE')));});
test('real exchange sessions determine weekend age: one delayed, two-three limited, older blocked',()=>{for(const [lag,expected,fresh]of[[0,'CHART_READY','CURRENT_LAST_SESSION'],[1,'CHART_READY','DELAYED'],[2,'CHART_LIMITED','DELAYED'],[3,'CHART_LIMITED','DELAYED'],[4,'CHART_BLOCKED','STALE']]){const r=call({observations:lag?rows.slice(0,-lag):rows});assert.equal(r.chartStatus,expected);assert.equal(r.freshness,fresh);assert.equal(r.sessionLag,lag);}});
test('minimum meaningful history needs both 20 points and 30 actual calendar days',()=>{assert.equal(call({observations:rows.slice(-20)}).chartStatus,'CHART_BLOCKED');const r=call({observations:rows.slice(-24)});assert.equal(r.chartStatus,'CHART_LIMITED');assert.equal(r.points.length,24);});
test('recent independent range can be safe while older MAX serious discontinuity remains blocked',()=>{const older=[row('2025-08-01',1),row('2025-08-04',100)];assert.equal(call({observations:[...older,...rows]}).chartStatus,'CHART_BLOCKED');const recent=call({observations:[...older,...rows],displayRange:{from:'2025-10-10',to:'2026-10-10'}});assert.equal(recent.chartStatus,'CHART_READY');assert.equal(recent.firstDate,'2025-10-10');});
test('source-backed split labels a RAW break without changing any Close; unknown split never inferred',()=>{const changed=rows.map(r=>structuredClone(r));for(const r of changed)if(r.normalized.tradingDate>='2026-03-10'){r.raw.close/=3;r.normalized.close/=3;}assert.equal(call({observations:changed}).chartStatus,'CHART_BLOCKED');const r=call({observations:changed,corporateActions:[{type:'SPLIT',date:'2026-03-10',mic:'XETR',symbol:'SAP.DE',ratio:3,sourceSha256:sha}]});assert.equal(r.chartStatus,'CHART_LIMITED');assert.equal(r.annotations.length,1);assert.equal(r.annotations[0].pricesAdjusted,false);assert.equal(r.points.find(p=>p[0]==='2026-03-10')[1],changed.find(r=>r.normalized.tradingDate==='2026-03-10').raw.close);});
test('missing authenticated scope and mismatched calendar block',()=>{assert.equal(call({calendar:{...calendar,mic:'XNAS'}}).chartStatus,'CHART_BLOCKED');const altered=structuredClone(rows);for(const r of altered)delete r.provenance.rawSha256;assert.equal(call({observations:altered}).chartStatus,'CHART_BLOCKED');});

test('documented ISO currency case comparison preserves exact raw lowercase provider values',()=>{const altered=structuredClone(rows);for(const r of altered){r.raw.price_currency='eur';r.normalized.currency='EUR';}const r=call({observations:altered});assert.equal(r.chartStatus,'CHART_READY');assert.equal(altered[0].raw.price_currency,'eur');});

test('raw date cannot be hidden behind a different normalized trading date',()=>{const altered=structuredClone(rows);altered.at(-1).raw.date='2026-10-12T00:00:00Z';const r=call({observations:altered});assert(!r.points.some(p=>p[0]==='2026-10-09'));assert(r.rejectedObservations.at(-1).reasonCodes.includes('RAW_NORMALIZED_DATE_CONFLICT'));});

test('misdated calendar completion cannot admit future session dates or claim current',()=>{const forged={verified:true,mic:'XETR',source:'test-schedule',sessions:Array.from({length:25},(_,i)=>({date:new Date(Date.parse('2026-11-01')+i*86400000).toISOString().slice(0,10),close:'2026-10-01T16:00:00Z'}))};const r=call({calendar:forged,observations:forged.sessions.map(s=>row(s.date))});assert.equal(r.chartStatus,'CHART_BLOCKED');assert.equal(r.freshness,'UNKNOWN');assert.equal(r.points.length,0);assert(r.reasonCodes.includes('CURRENT_EXACT_MIC_SESSION_CALENDAR_REQUIRED'));});

test('calendar truncated before current evaluation cannot falsely mark stale Close current',()=>{const r=call({calendar:{...calendar,sessions:calendar.sessions.filter(s=>s.date<='2026-10-08')},observations:rows.slice(0,-1)});assert.equal(r.chartStatus,'CHART_BLOCKED');assert.equal(r.freshness,'UNKNOWN');assert.equal(r.calendarProof.verified,false);const actual=call();assert.equal(actual.calendarProof.expectedLastCompletedSession,'2026-10-09');assert.equal(actual.calendarProof.nextScheduledSession.date,'2026-10-12');});

test('GBP pence proof does not imply a GBP-major-unit display contract',()=>{const l={...listing,currency:'GBP',quoteUnit:'GBX',quoteBasis:{...listing.quoteBasis,kind:'PROVIDER_DOCUMENTED_QUOTE_CONTRACT',currency:'GBP',quoteUnit:'GBX',unitContractSha256:sha}};assert.equal(call({listing:l}).chartStatus,'CHART_BLOCKED');});
