import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const Core=require('../../../core/europe-market-data.js');
import test from 'node:test';
import assert from 'node:assert/strict';
import { buildEuropeDiscoverCatalog, buildEuropeDiscoverCatalogAsync, sha256, readEuropeDiscoverCatalogFromPaths } from '../../../scripts/marketstack/europe-discover-catalog.mjs';
const hash='a'.repeat(64), now='2026-10-10T08:00:00Z';
function fixture() {
 const key='marketstack:XETR:SAP.DE',id='ref_SAP_DE_XETR',company='LEI:529900D6BF99LW9R2E68',isin='DE0007164600';
 const admissionProof={version:'europe-discover-identity-2.0.0',status:'UNIVERSE_IDENTITY_READY',securityId:id,companyId:company,listingId:key,isin,securityKey:'ISIN:'+isin,mic:'XETR',providerSymbol:'SAP.DE',currency:null,issuerCountry:'DE',assetType:'EQUITY',issuerBinding:'VERIFIED_LEGAL_ISSUER',active:true,localListingPlausible:true,duplicateResolved:true,evidenceRefs:[{sha256:hash,verified:true}]};
 const l={listingKey:key,listingId:key,securityId:id,companyKey:company,companyId:company,isin,mic:'XETR',providerSymbol:'SAP.DE',currency:null,issuerCountry:'DE',isPrimary:true,verifiedAliases:['SAP.DE','SAP'],admissionProof};
 const s={securityId:id,securityKey:'ISIN:'+isin,isin,companyKey:company,listings:[key],primaryListing:key,canonicalTicker:'SAP.DE.XETR',shareClassDetail:'UNKNOWN',aliases:['SAP.DE']};
 const c={companyKey:company,companyId:company,issuerCountry:'DE',displayName:'SAP SE',legalName:'SAP SE',securities:[s.securityKey]};
 const points=Array.from({length:31},(_,i)=>[new Date(Date.UTC(2026,8,i)).toISOString().slice(0,10),100+i]);
 const p={version:'europe-discover-close-chart-1',listingKey:key,listingId:key,securityId:id,companyId:company,mic:'XETR',providerSymbol:'SAP.DE',isin,currency:'EUR',quoteUnit:'EUR',priceBasis:'RAW_UNADJUSTED',quoteBasis:{kind:'OFFICIAL_LISTING_QUOTE_REFERENCE',mic:'XETR',providerSymbol:'SAP.DE',isin,currency:'EUR',quoteUnit:'EUR',sourceSha256:hash},points,segments:[points.slice(0,15),points.slice(15)],pointsSha256:sha256(points),observationCount:31,firstDate:points[0][0],lastDate:points.at(-1)[0],sessionLag:1,calendarSource:'official-calendar',calendarSourceSha256:hash,calendarProof:{evaluatedAt:now,source:'official-calendar',mic:'XETR',sourceSha256:hash,coverageFrom:'2026-01-01',coverageTo:'2026-12-31',expectedLastCompletedSession:'2026-10-09',nextScheduledSession:{date:'2026-10-12',close:'2026-10-12T15:30:00Z'},verified:true},sourceInputSha256:hash,immutableExclusionsSha256:hash,chartStatus:'CHART_LIMITED',criticalIssues:[],reasonCodes:[],evaluatedAt:now,publicationAllowed:false};
 return {identityArtifact:{mode:'PRIVATE_RESEARCH',publicationAllowed:false,knownReferenceGraph:{companies:[c],securities:[s],listings:[l]}},priorUniverse:{mode:'PRIVATE_RESEARCH',publicationAllowed:false,securities:[],listings:[]},priorProjection:{mode:'PRIVATE_RESEARCH',publicationAllowed:false,generatedAt:'2026-10-09T16:00:00Z',listingEvidence:{}},chartProofs:[{listingKey:key,proofSha256:sha256(p),proof:p}],protectedIds:[],sourceBindings:{identitySha256:hash,protectedIdsSha256:hash},now};
}
function oldFixture(){const f=fixture(),g=f.identityArtifact.knownReferenceGraph,s=g.securities[0],l=g.listings[0];f.priorUniverse.securities=[structuredClone(s)];f.priorUniverse.listings=[{...structuredClone(l),status:'ACCEPTED',identityEvidence:[{verified:true,source:'official',issuerName:'SAP SE',lei:'529900D6BF99LW9R2E68'}],name:'SAP SE',currency:'EUR'}];f.priorProjection.listingEvidence[l.listingKey]={history:{valid:true,observations:2500},priceQuality:{status:'VALIDATED',evidenceRef:hash},latest:{date:'2026-09-30',volume:400},technical:{status:'TECHNICAL_PARTIAL',asOf:'2026-09-30',metrics:{sma20:123},evidenceRef:hash},adjustment:{status:'ADJUSTMENT_PARTIAL'}};return f;}
test('new close-only Discover class keeps analytics unknown, resolves only scoped quote, serves exact segmented1Y',()=>{const f=fixture(),r=buildEuropeDiscoverCatalog(f),s=r.catalog.securities[0],l=s.listings[0];assert.equal(s.acceptance,'DISCOVER_ONLY');assert.equal(l.identityAdmission.currency,'EUR');assert.equal(f.identityArtifact.knownReferenceGraph.listings[0].currency,null);assert.equal(l.history.valid,false);assert.deepEqual(l.technical,{});assert.equal(l.latest.volume,null);assert.equal(r.catalog.counts.discoverEligible,1);assert.deepEqual(r.series[0].points,f.chartProofs[0].proof.points);assert.deepEqual(r.series[0].segments,f.chartProofs[0].proof.segments);assert.equal(r.series[0].range,'1Y');assert.equal(s.aliases.includes('SAP'),true);});
test('prior canonical ID and strict evidence retained without re-dating technical metrics',()=>{const r=buildEuropeDiscoverCatalog(oldFixture()),s=r.catalog.securities[0],l=s.listings[0];assert.equal(s.securityId,'ref_SAP_DE_XETR');assert.equal(s.acceptance,'ACCEPTED');assert.equal(l.history.observations,2500);assert.equal(l.technical.asOf,'2026-09-30');assert.equal(l.technical.metrics.sma20,123);assert.equal(l.latest.volume,400);});
test('old volume is absent when latest chart observation changes',()=>{const f=oldFixture();f.priorProjection.listingEvidence['marketstack:XETR:SAP.DE'].latest.date='2026-09-29';assert.equal(buildEuropeDiscoverCatalog(f).catalog.securities[0].listings[0].latest.volume,null);});
test('blocked old identity retains canonical ID and ACCEPTED legacy lineage but is excluded from Discover/series',()=>{const f=oldFixture(),a=f.identityArtifact.knownReferenceGraph.listings[0].admissionProof;a.status='BLOCKED';a.evidenceRefs=[];a.reasonCodes=['CONFLICTING_PROVIDER_LEGAL_ISSUER'];const r=buildEuropeDiscoverCatalog(f);assert.equal(r.catalog.securities[0].acceptance,'ACCEPTED');assert.equal(r.catalog.securities[0].identity.status,'BLOCKED');assert.equal(r.catalog.counts.discoverEligible,0);assert.equal(r.series.length,0);});
test('wrong current company/MIC/ISIN proof cannot borrow a chart',()=>{for(const field of ['companyId','mic','isin','listingId']){const f=fixture();f.chartProofs[0].proof[field]='wrong';assert.throws(()=>buildEuropeDiscoverCatalog(f),/CHART_CANONICAL_BINDING/);}});
test('identity proof cannot change company independently from graph',()=>{const f=fixture();f.identityArtifact.knownReferenceGraph.listings[0].admissionProof.companyId='wrong';assert.throws(()=>buildEuropeDiscoverCatalog(f),/IDENTITY_PROOF_BINDING/);});
test('quote resolution cannot transfer Xetra currency to another MIC',()=>{const f=fixture();f.chartProofs[0].proof.quoteBasis.mic='XSWX';assert.throws(()=>buildEuropeDiscoverCatalog(f),/CURRENCY_RESOLUTION_PROOF/);});
test('nonnull identity currency conflicts remain hard failures',()=>{const f=fixture(),a=f.identityArtifact.knownReferenceGraph.listings[0];a.currency='CHF';a.admissionProof.currency='CHF';assert.throws(()=>buildEuropeDiscoverCatalog(f),/CONFLICTING_CANONICAL_QUOTE/);});
test('safe chart content and segment tampering reject rather than repairing',()=>{const f=fixture();f.chartProofs[0].proof.points[0][1]=999;assert.throws(()=>buildEuropeDiscoverCatalog(f),/POINTS_HASH/);const g=fixture();g.chartProofs[0].proof.segments.pop();assert.throws(()=>buildEuropeDiscoverCatalog(g),/SEGMENTS_MISMATCH/);});
test('stale proof is blocked even when existing old OHLC history is valid',()=>{const f=oldFixture();f.chartProofs[0].proof.sessionLag=4;const r=buildEuropeDiscoverCatalog(f);assert.equal(r.catalog.securities[0].listings[0].latest.status,'STALE');assert.equal(r.series.length,0);});
test('range summaries are never exposed as additional available series',()=>{const f=fixture();f.chartProofs[0].proof.ranges={MAX:{chartStatus:'CHART_READY'}};f.chartProofs[0].proof.rangeProofs=[{range:'MAX'}];const r=buildEuropeDiscoverCatalog(f);assert.equal(r.catalog.securities[0].listings[0].discoverChart.ranges,undefined);assert.equal(r.series.length,1);});
test('current-main company/security/listing collisions reject',()=>{for(const id of ['ref_SAP_DE_XETR','LEI:529900D6BF99LW9R2E68','marketstack:XETR:SAP.DE']){const f=fixture();f.protectedIds=[id];assert.throws(()=>buildEuropeDiscoverCatalog(f),/PROTECTED_ID_COLLISION/);}});
test('omitting any retained prior canonical ID rejects',()=>{const f=oldFixture();f.identityArtifact.knownReferenceGraph.securities[0].securityId='ref_replaced';assert.throws(()=>buildEuropeDiscoverCatalog(f),/PRIOR_CANONICAL_ID/);});
test('missing original chart receipt and private source gates reject',()=>{const f=fixture();f.chartProofs[0].proofSha256=null;assert.throws(()=>buildEuropeDiscoverCatalog(f),/CHART_PROOF_RECEIPT/);const g=fixture();g.identityArtifact.publicationAllowed=true;assert.throws(()=>buildEuropeDiscoverCatalog(g),/PRIVATE_ARTIFACT/);});
test('async pure API matches sync and all inputs remain unchanged',async()=>{const f=fixture(),before=JSON.stringify(f);assert.deepEqual(await buildEuropeDiscoverCatalogAsync(f),buildEuropeDiscoverCatalog(f));assert.equal(JSON.stringify(f),before);});
test('filesystem wrapper requires original byte hashes before reading inputs',()=>{assert.throws(()=>readEuropeDiscoverCatalogFromPaths({identity:{path:'/tmp/no-file',sha256:null}}),/INPUT_SHA_REQUIRED/);});
test('same ISIN cannot create two canonical security records',()=>{const f=fixture(),s=f.identityArtifact.knownReferenceGraph.securities[0];f.identityArtifact.knownReferenceGraph.securities.push({...s,securityId:'ref_duplicate'});assert.throws(()=>buildEuropeDiscoverCatalog(f),/DUPLICATE_OR_MISSING_SECURITY_ISIN/);});
test('explicit provider-currency basis requires both observation and contract hashes',()=>{const f=fixture(),q=f.chartProofs[0].proof.quoteBasis;q.kind='PROVIDER_EXPLICIT_QUOTE_CURRENCY';assert.throws(()=>buildEuropeDiscoverCatalog(f),/CURRENCY_RESOLUTION_PROOF/);q.providerCurrencyObservationSha256=hash;q.contractSchemaSha256=hash;assert.equal(buildEuropeDiscoverCatalog(f).catalog.counts.discoverEligible,1);});
test('identity and chart artifact bindings preserve original source currency in receipts',()=>{const f=fixture();f.chartProofs[0].proof.canonicalBinding={identitySourceSha256:'b'.repeat(64),originalIdentityFileUnchanged:true};assert.throws(()=>buildEuropeDiscoverCatalog(f),/CHART_IDENTITY_SOURCE_MISMATCH/);f.chartProofs[0].proof.canonicalBinding.identitySourceSha256=hash;const l=buildEuropeDiscoverCatalog(f).catalog.securities[0].listings[0];assert.equal(l.provenance.identityOriginalCurrency,null);assert.equal(l.provenance.identityArtifactSha256,hash);});

test('newer close-only latest cannot recertify old strict history or strategy inputs',()=>{const f=oldFixture(),key='marketstack:XETR:SAP.DE';f.priorProjection.listingEvidence[key].latest.date='2026-09-29';const l=buildEuropeDiscoverCatalog(f).catalog.securities[0].listings[0];assert.equal(l.latest.date,'2026-09-30');assert.equal(l.history.valid,false);assert.equal(l.priceQuality.status,'UNKNOWN');assert.equal(l.strictHistoricalEvidence.history.valid,true);assert.equal(l.strictHistoricalEvidence.latest.date,'2026-09-29');assert.equal(l.technical.asOf,'2026-09-30');});

test('actual Core consumes exact1Y segmented tuples and refuses unserved MAX range',async()=>{const f=fixture(),r=buildEuropeDiscoverCatalog(f),id=r.catalog.securities[0].securityId;let loads=0;const client=Core.create({catalog:r.catalog,usClient:{},audience:'research',now,loadSeries:request=>{loads++;return r.series.find(s=>s.securityId===request.securityId && s.listingId===request.listingId && s.range===request.range);}});const one=await client.getPriceSeries({region:'EUROPE',securityId:id},{range:'1Y'});assert.equal(one.state,'AVAILABLE');assert.deepEqual(one.data.points,f.chartProofs[0].proof.points);const max=await client.getPriceSeries({region:'EUROPE',securityId:id},{range:'MAX'});assert.equal(max.state,'UNAVAILABLE');assert.equal(loads,1);});
test('path compiler checks every original file hash and exact summary/proof binding',async()=>{
 const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vu-discover-catalog-'));
 try{const f=fixture();const save=(name,value)=>{const file=path.join(dir,name),text=JSON.stringify(value)+'\n';fs.writeFileSync(file,text);return {path:file,sha256:sha256(text)};};
 const universe=save('marketstack_europe_equity_universe.json',f.priorUniverse),projection=save('marketstack_europe_core_projection.json',f.priorProjection),protection=save('protection.json',{securityIds:[]});
 const manifest=save('prior-manifest.json',{publicationAllowed:false,files:[{name:path.basename(universe.path),sha256:universe.sha256},{name:path.basename(projection.path),sha256:projection.sha256}]});
 f.identityArtifact.candidates=[{}];f.identityArtifact.sourceBindings={priorIdentity:{sha256:universe.sha256},protectedIdentitySources:[{sha256:protection.sha256}]};const identity=save('identity.json',f.identityArtifact),proof=save('proof.json',f.chartProofs[0].proof);
 const key=f.chartProofs[0].listingKey,chartManifest=save('chart-manifest.json',{files:[{listingKey:key,path:proof.path,sha256:proof.sha256}]}),chartSummary=save('chart-summary.json',{publicationAllowed:false,noProviderCalls:true,rows:[{listingKey:key,proofSha256:proof.sha256}]});
 const config={identity,prior:{manifest,directory:dir},protectedIds:protection,chartManifest,chartSummary,now};assert.equal(readEuropeDiscoverCatalogFromPaths(config).catalog.counts.discoverEligible,1);
 fs.appendFileSync(proof.path,' ');assert.throws(()=>readEuropeDiscoverCatalogFromPaths(config),/INPUT_SHA_MISMATCH/);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('path compiler refuses symlink leaves even when target bytes have the expected hash',async()=>{const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vu-catalog-symlink-'));try{const target=path.join(dir,'target.json'),link=path.join(dir,'link.json');fs.writeFileSync(target,'{}');fs.symlinkSync(target,link);assert.throws(()=>readEuropeDiscoverCatalogFromPaths({identity:{path:link,sha256:sha256('{}')}}),/SYMLINK/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('blocked reference may retain an unbound C source proof but never receives canonical chart attestation',()=>{const f=oldFixture();f.identityArtifact.knownReferenceGraph.listings[0].admissionProof.status='BLOCKED';f.chartProofs[0].proof.securityId=null;f.chartProofs[0].proof.companyId=null;const r=buildEuropeDiscoverCatalog(f),l=r.catalog.securities[0].listings[0];assert.equal(l.discoverChart.securityId,null);assert.equal(l.discoverChart.chartStatus,'CHART_BLOCKED');assert.equal(r.series.length,0);});
