import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {replayCommittedClassification} from '../../scripts/universe/company-master-snapshot-replay.mjs';
const require=createRequire(import.meta.url),Master=require('../engines/company-master.js');
function sample(ticker){const shard=ticker.slice(0,2);return JSON.parse(readFileSync(new URL('../data/universe/instruments/'+shard+'.json',import.meta.url))).instruments.find(row=>row.symbol===ticker);}
function classified(prior){const incoming=Master.toInstrument({ticker:prior.symbol,exchange:prior.exchange,name:prior.companyName,assetType:prior.assetTypeRaw,currency:prior.currency,startDate:prior.firstTradeDate,endDate:prior.lastTradeDate},{today:'2026-10-02'});for(const field of ['active','productEligibility','productEligibilityReason','securityClass','masterMemberId'])incoming[field]=prior[field];incoming.classificationAgrees=incoming.securityType===prior.securityType;return incoming;}
for(const ticker of ['PFBC','AAPGV'])test(ticker+' offline snapshot replay preserves reviewed canonical classification and exposes a staged proposal',()=>{const previous=sample(ticker),incoming=classified(previous);assert.notEqual(incoming.securityType,previous.securityType);const replay=replayCommittedClassification(previous,incoming,{sourceKind:'COMMITTED_GATE_UNIVERSES'});assert.equal(replay.instrument.securityType,previous.securityType);assert.equal(replay.proposal.decision,'STAGED_CLASSIFICATION_REVIEW');assert.equal(replay.proposal.instrumentId,previous.instrumentId);assert.ok(replay.proposal.changes.some(row=>row.field==='securityType'&&row.proposed===incoming.securityType));assert.equal(incoming.securityType,classified(previous).securityType);});
test('fresh provider discovery retains the corrected Preferred Bank common classification',()=>{const previous=sample('PFBC'),incoming=classified(previous),result=replayCommittedClassification(previous,incoming,{sourceKind:'TIINGO_PROVIDER_DIRECTORY'});assert.equal(result.instrument.securityType,'COMMON_STOCK');assert.equal(result.proposal,null);});
test('changed listing or policy inputs cannot replay stale classification',()=>{const previous=sample('PFBC'),incoming=classified(previous);for(const field of ['companyName','exchange','assetTypeRaw','firstTradeDate','lastTradeDate','currency','active','securityClass','productEligibility','masterMemberId']){const changed={...incoming,[field]:field==='active'?false:'changed'};assert.equal(replayCommittedClassification(previous,changed,{sourceKind:'COMMITTED_GATE_UNIVERSES'}).instrument,changed,field);}assert.equal(replayCommittedClassification(null,incoming,{sourceKind:'COMMITTED_GATE_UNIVERSES'}).instrument,incoming);});
