import test from 'node:test';
import assert from 'node:assert/strict';
import {importEvidence} from '../../scripts/market/import-marketstack-evidence.mjs';
const probe=(symbol='SAP.DE',mic='XETR',country='DE',type='equity')=>({generatedAt:'2026-10-01T12:00:00Z',endpoints:[
 {label:'listing-identity',ok:true,data:{symbol,name:'Issuer',item_type:type,isin:'DE0007164600',stock_exchange:{mic,country_code:country,name:'Venue'}}},
 {label:'global-qualified-eod',ok:true,checkedAt:'2026-10-01T12:00:00Z',params:{symbols:symbol},data:{data:['2026-09-28','2026-09-29'].map(date=>({date,symbol,exchange:mic,open:10,high:12,low:9,close:11,volume:100,price_currency:null}))}}]});
const ref=(symbol='SAP.DE',mic='XETR')=>[{matches:[{provider_symbol:symbol,mic,isin:'DE0007164600',trading_currency:'EUR',instrument_status:'Active',source:{source_system:'OFFICIAL'}}]}];
test('null trading currencies need exact official instrument evidence; price currency contamination blocks series',()=>{assert.equal(importEvidence(probe(),[]).summary.imported,0);assert.equal(importEvidence(probe(),ref()).summary.imported,1);const p=probe();p.endpoints[1].data.data[0].price_currency='MXN';assert.equal(importEvidence(p,ref()).summary.imported,0);});
test('malformed candles are quarantined and coverage remains PARTIAL without fabricating a replacement',()=>{const p=probe();p.endpoints[1].data.data.push({...p.endpoints[1].data.data[0],date:'2026-09-30',close:0});const r=importEvidence(p,ref());assert.equal(r.summary.imported,1);const h=Object.values(r.histories)[0];assert.equal(h.bars.length,2);assert.equal(h.quarantined.length,1);assert.equal(h.quality.status,'PARTIAL');assert.equal(r.layer.listings[0].coverage.technical,'NONE');});
test('accepted listing/company/security identifiers are retained; shares class dots are not stripped',()=>{const r=importEvidence(probe('BRK.B','XNYS','US'),ref('BRK.B','XNYS'),[{ticker:'BRK.B',mic:'XNYS',listingId:'vu_abc123',companyId:'issuer_a',securityId:'sec_a'}]);assert.equal(r.layer.listings[0].ticker,'BRK.B');assert.equal(r.layer.listings[0].listingId,'vu_abc123');assert.equal(r.layer.listings[0].companyId,'issuer_a');assert.equal(r.layer.listings[0].securityId,'sec_a');});
test('Europe region uses accepted global classifier; ETFs cannot receive company identity',()=>{const r=importEvidence(probe('FUND','XHEL','FI','etf'),ref('FUND','XHEL'),[{ticker:'FUND',mic:'XHEL',companyId:'bogus',listingId:'vu_abc123'}]);assert.equal(r.layer.listings[0].listingRegion,'EUROPE');assert.equal(r.layer.listings[0].companyId,null);assert.ok(r.layer.listings[0].fundId);assert.equal(r.layer.listings[0].coverage.corporate_actions,'UNKNOWN');});

test('existing issuer country, reporting currency and ADR safeguards survive; future candles never enter history',()=>{const p=probe();p.endpoints[1].data.data.push({...p.endpoints[1].data.data[0],date:'2027-01-01'});const r=importEvidence(p,ref(),[{ticker:'SAP',mic:'XETR',listingId:'vu_abc123',companyId:'issuer_a',country:'US',reportingCurrency:'USD',primaryListing:false,listingType:'ADR',adrRatio:2,adrRatioSource:'verified'}]);const l=r.layer.listings[0];assert.equal(l.country,'US');assert.equal(l.listingCountry,'DE');assert.equal(l.reportingCurrency,'USD');assert.equal(l.listingType,'ADR');assert.equal(l.adrRatio,2);assert.equal(l.coverage.price_eod,'PARTIAL');assert.equal(Object.values(r.histories)[0].bars.length,2);});
test('same ticker and venue cannot overwrite a contradictory existing security ISIN',()=>{const existing=[{ticker:'SAP',mic:'XETR',isin:'DE0000000001',listingId:'vu_wrong',securityId:'sec_wrong'}];const before=JSON.stringify(existing);const r=importEvidence(probe(),ref(),existing);assert.equal(r.summary.imported,0);assert.equal(r.summary.decisions[0].reason,'EXISTING_SECURITY_IDENTITY_MISMATCH');assert.equal(JSON.stringify(existing),before);});
