import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';
const require=createRequire(import.meta.url),C=require('../api/market-signal-contract.js'),Service=require('../api/product-services.js'),Policy=require('../engines/display-policy.js'),Query=require('../engines/query.js');
const api=Service.create({loadJSON:p=>Promise.resolve(JSON.parse(readFileSync(new URL('../..'+p,import.meta.url)))),displayPolicy:Policy,queryEngine:Query}),recipes=api.getRecipes();
const source=t=>JSON.parse(readFileSync(new URL('../data/market/golden-preview/daily/ref_'+t+'.json',import.meta.url)));
test('real observations reproduce two known MSFT rule transitions and unchanged dates produce no new event',()=>{const r=C.build(source('MSFT'),{ticker:'MSFT',recipes,lookback:60});assert.equal(r.state,'AVAILABLE');assert.deepEqual(r.events.map(e=>[e.asOf,e.definitionId]),[['2026-07-31','positive-momentum'],['2026-07-30','above-long-trend']]);for(const e of r.events){const previous=Object.fromEntries(e.evidence.map(m=>[m.metricId,m.previous])),current=Object.fromEntries(e.evidence.map(m=>[m.metricId,m.current]));assert.notEqual(Query.matches(previous,e.query.filters),Query.matches(current,e.query.filters));assert.equal(e.queryHash,Query.queryHash(recipes.find(r=>r.id===e.definitionId).query));assert.ok(e.expiration.at>e.asOf);assert.equal(e.status,'HISTORICAL');}assert.equal(C.build(source('MSFT'),{ticker:'MSFT',recipes}).events.length,0);});
test('later prices cannot change earlier observed transitions',()=>{const s=source('MSFT'),before=C.build(s,{ticker:'MSFT',recipes,lookback:60});s.bars.at(-1).close*=2;s.bars.at(-1).adjustedClose*=2;const after=C.build(s,{ticker:'MSFT',recipes,lookback:60});assert.deepEqual(after.events.filter(e=>e.asOf<after.asOf),before.events.filter(e=>e.asOf<before.asOf));});
test('future, duplicate, nonfinite, unknown adjustments and split windows are not signal evidence',()=>{for(const mutate of [s=>s.bars.at(-1).date='2099-01-01',s=>s.bars.at(-1).date=s.bars.at(-2).date,s=>s.bars.at(-1).close=NaN,s=>s.adjustmentStatus='unknown',s=>s.bars.at(-1).splitFactor=2,s=>s.updatedAt='2099-01-01T00:00:00Z']){const s=source('NVDA');mutate(s);assert.equal(C.build(s,{ticker:'NVDA',recipes}).state,'UNAVAILABLE');}});
test('approved scope is preserved and denied raw display prevents history reads',async()=>{const result=await api.getSignals({lookback:60});assert.equal(result.results.length,5);assert.equal(result.partial,false);assert.equal(result.events.length,4);let rawReads=0;const denied=Service.create({loadJSON:p=>{if(p.includes('/golden-preview/'))rawReads++;return Promise.resolve(JSON.parse(readFileSync(new URL('../..'+p,import.meta.url))));},displayPolicy:{...Policy,check:args=>({allowed:args.form==='derived'})},queryEngine:Query});assert.equal((await denied.getSignals()).state,'UNAVAILABLE');assert.equal(rawReads,0);});

test('overflow, insufficient comparison history and pre-close snapshots fail closed',()=>{const overflow=source('MSFT');overflow.bars.at(-1).close=1e100;assert.equal(C.build(overflow,{ticker:'MSFT',recipes}).reason,'INVALID_SIGNAL_PANEL');const short=source('MSFT');short.bars=short.bars.slice(-202);assert.equal(C.build(short,{ticker:'MSFT',recipes,lookback:60}).reason,'INSUFFICIENT_HISTORY');const early=source('MSFT');early.updatedAt=early.bars.at(-1).date+'T13:00:00Z';assert.equal(C.build(early,{ticker:'MSFT',recipes}).reason,'SESSION_NOT_CLOSED_AT_SNAPSHOT');});

test('unavailable coverage retains the requested company identity',async()=>{const broken=Service.create({loadJSON:p=>{const data=JSON.parse(readFileSync(new URL('../..'+p,import.meta.url)));if(p.endsWith('ref_MSFT.json'))data.updatedAt='2099-01-01T00:00:00Z';return Promise.resolve(data);},displayPolicy:Policy,queryEngine:Query});const result=await broken.getSignals();assert.equal(result.partial,true);assert.equal(result.results.find(r=>r.state==='UNAVAILABLE').ticker,'MSFT');});
