import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const require=createRequire(import.meta.url),Health=require('../api/market-health-contract.js'),Gate=require('../engines/market-eod-gate.js'),calendar=require('../config/market-calendar.json');
const stock=(asOf,extra={})=>({ticker:'NVDA',state:'AVAILABLE',marketState:'AVAILABLE',asOf,...extra});
test('freshness follows completed sessions including weekend, holiday and early close',()=>{for(const [now,day] of [['2026-09-12T15:00:00Z','2026-09-11'],['2026-09-07T15:00:00Z','2026-09-04'],['2026-11-27T17:59:00Z','2026-11-25'],['2026-11-27T18:00:00Z','2026-11-27']]){const x=Health.build([stock(day)],calendar,now);assert.equal(x.state,'AVAILABLE');assert.equal(x.expectedThrough,day);assert.equal(x.isLive,false);assert.equal(x.providerFinality,'NOT_CERTIFIED');assert.equal(x.qualityChecks,'NOT_EVALUATED');}});
test('older EOD is stale, not a missing price replacement',()=>{const x=Health.build([stock('2026-09-08')],calendar,'2026-09-12T15:00:00Z');assert.equal(x.state,'STALE');assert.equal(x.members[0].observedThrough,'2026-09-08');assert.equal(x.expectedThrough,'2026-09-11');assert.equal('price' in x.members[0],false);});
test('invalid, non-trading and not-yet-closed observations cannot be called current',()=>{for(const date of ['2026-02-30','2026-09-07','2026-09-12']){const x=Health.build([stock(date)],calendar,'2026-09-12T15:00:00Z');assert.equal(x.state,'PIPELINE_ERROR');}});
test('missing calendar or market permission never asserts freshness',()=>{for(const c of [null,{}, {...calendar,calendarId:'unknown'}])assert.equal(Health.build([stock('2026-09-11')],c).state,'UNAVAILABLE');const x=Health.build([stock('2026-09-11',{marketState:'UNAVAILABLE'})],calendar,'2026-09-12T15:00:00Z');assert.equal(x.state,'UNAVAILABLE');assert.equal(x.members[0].observedThrough,null);assert.equal(Health.build([],calendar,'2026-09-12T15:00:00Z').state,'UNAVAILABLE');});
test('partial coverage retains unavailable identities and never reports all current',()=>{const x=Health.build([stock('2026-09-11'),stock('2026-09-11',{ticker:'MSFT',state:'UNAVAILABLE'})],calendar,'2026-09-12T15:00:00Z');assert.equal(x.state,'UNAVAILABLE');assert.equal(x.members.length,2);assert.equal(x.members[1].ticker,'MSFT');});
test('browser wrapper executes the same accepted EOD calendar algorithm',()=>{const context=vm.createContext({Date,Intl});context.window=context;for(const path of ['../engines/realtime/market-hours.js','../engines/market-eod-gate.js'])vm.runInContext(readFileSync(new URL(path,import.meta.url),'utf8'),context);for(const now of ['2026-09-12T15:00:00Z','2026-11-27T18:00:00Z'])assert.deepEqual(JSON.parse(JSON.stringify(context.VUMarketEodGate.latestClosedSession(now,calendar))),Gate.latestClosedSession(now,calendar));});
