import test from'node:test';import assert from'node:assert/strict';import{buildEuropeFoundation}from'../../scripts/market/build-europe-foundation.mjs';
const ref={mic:'XPAR',referenceMic:'XPAR',symbol:'AIR',name:'Airbus',isin:'NL0000235190',tradingCurrency:'EUR',assetType:'EQUITY',listingType:'COMMON_STOCK',sourceId:'OFFICIAL_CSV',classificationSourceId:'EURONEXT_OFFICIAL_COMMON_STOCK_101',classificationEvidenceSourceId:'euronext-common-XPAR'};
const sources={OFFICIAL_CSV:{url:'https://official.example/currency.csv',sha256:'1'.repeat(64),retrievedAt:'2026-10-01T00:00:00Z'},'euronext-common-XPAR':{url:'https://official.example/stocks',sha256:'2'.repeat(64),method:'POST',filter:{issueType:'101'},observedRows:1,total:1}};
const row={providerSymbol:'AIR.XPAR',providerName:'AIRBUS',mic:'XPAR',listingCountry:'FR',isin:ref.isin,tradingCurrency:'EUR',assetType:'EQUITY',classificationState:'REFERENCE_CLASSIFIED',referenceMatch:'EXACT_REFERENCE_MATCH'};
const input=(rows=[row],refs=[ref])=>({universe:{generatedAt:'2026-10-01T00:00:00Z',listings:rows},references:{rows:refs,sources}});
test('official typed equity creates deterministic metadata-only identity without issuer inference',()=>{const result=buildEuropeFoundation(input()),r=result.layer.listings[0];assert.equal(result.summary.metadataRecordsAdded,1);assert.equal(r.country,null);assert.equal(r.reportingCurrency,null);assert.equal(r.listingCountry,'FR');assert.equal(r.companyId,null);assert.equal(Object.hasOwn(r,'price'),false);assert.equal(r.coverage.price_history,'NONE');assert.equal(r.coverage.intraday,'UNKNOWN');assert.equal(r.coverage.corporate_actions,'UNKNOWN');assert.equal(r.listingId,buildEuropeFoundation(input()).layer.listings[0].listingId);});
test('strict existing key/ISIN/MIC/currency preserves exact accepted record and history gates',()=>{const base=buildEuropeFoundation(input()).layer;base.listings[0].coverage.price_history='PARTIAL';base.listings[0].quality={status:'PARTIAL',quarantinedCandles:2};const result=buildEuropeFoundation({...input(),existing:base});assert.equal(result.summary.metadataRecordsAdded,0);assert.deepEqual(result.layer.listings,base.listings);for(const change of [{isin:'FR0000121014'},{tradingCurrency:'USD'},{assetType:'ETF'}]){const changed={...row,...change};const rejected=buildEuropeFoundation({...input([changed]),existing:base});assert.equal(rejected.summary.blocked,1);assert.deepEqual(rejected.layer.listings,base.listings);}});
test('unfiltered category, contradictory currency/type/ISIN and metadata conflict do not grant identities',()=>{for(const [changed,refs,changedSources]of [[{...row,tradingCurrency:'USD'},[ref],sources],[{...row,isin:'USN070592100'},[ref],sources],[{...row,assetType:'ETF'},[ref],sources],[row,[{...ref,classificationSourceId:null}],sources],[row,[ref],{...sources,'euronext-common-XPAR':{...sources['euronext-common-XPAR'],method:'GET'}}],[{...row,referenceMatch:'PROVIDER_ISIN_CONFLICT',metadataEvidenceEndpoint:'tickers/AIR.XPAR'},[ref],sources]]){const result=buildEuropeFoundation({...input([changed],refs),references:{rows:refs,sources:changedSources}});assert.equal(result.layer.listings.length,0);assert.equal(result.summary.blocked,1);}});
test('explicit official ETF reference creates separate fund identity and no company fundamentals',()=>{const etf={...ref,assetType:'ETF',listingType:null,sourceId:'SIX_OFFICIAL_ETF_EXPLORER',sourceReference:{instrumentType:'ETF',source:{url:'https://official.example/funds',sha256:'3'.repeat(64)}}};const result=buildEuropeFoundation(input([{...row,assetType:'ETF'}],[etf])),r=result.layer.listings[0];assert.equal(r.companyId,null);assert.match(r.fundId,/^fund_[a-f0-9]{24}$/);assert.equal(r.coverage.fundamentals,'NONE');assert.equal(r.coverage.etf_holdings,'UNKNOWN');assert.equal(r.listingType,'UNKNOWN');});

test('offline analyzer CLI writes a private foundation and never publishes canonical files',async()=>{
 const{mkdtempSync,writeFileSync,readFileSync,rmSync}=await import('node:fs'),{join}=await import('node:path'),{tmpdir}=await import('node:os'),{execFileSync}=await import('node:child_process');const dir=mkdtempSync(join(tmpdir(),'europe-foundation-cli-'));try{
 const probe=join(dir,'probe.json'),reference=join(dir,'refs.json'),out=join(dir,'reports'),foundation=join(dir,'private-foundation.json');writeFileSync(probe,JSON.stringify({endpoints:[{endpoint:'exchanges/XPAR/tickers',ok:true,data:{pagination:{offset:0,count:1,total:1},data:{tickers:[{symbol:row.providerSymbol,name:row.providerName}]}}}]}));writeFileSync(reference,JSON.stringify({rows:[ref],sources}));const stdout=execFileSync(process.execPath,['scripts/market/analyze-marketstack-europe.mjs','--probe='+probe,'--references='+reference,'--out='+out,'--foundation-out='+foundation],{cwd:new URL('../..',import.meta.url),timeout:10000,encoding:'utf8'});assert.match(stdout,/"added":1/);const layer=JSON.parse(readFileSync(foundation));assert.equal(layer.listings.length,1);assert.equal(layer.listings[0].coverage.price_history,'NONE');assert.equal(JSON.parse(readFileSync(join(out,'europe_canonical_foundation_summary.json'))).productionActivated,false);
 }finally{rmSync(dir,{recursive:true,force:true});}
});

test('preferred provenance requires its actual classification evidence source instead of any complete106 query',()=>{const preferred={...ref,listingType:'PREFERRED',classificationSourceId:'EURONEXT_OFFICIAL_PREFERRED_STOCK_106',classificationEvidenceSourceId:null};const other={...sources,unrelated:{url:'https://official.example/other-market',sha256:'4'.repeat(64),method:'POST',filter:{issueType:'106'},observedRows:1,total:1}};let result=buildEuropeFoundation({...input([row],[preferred]),references:{rows:[preferred],sources:other}});assert.equal(result.layer.listings.length,0);preferred.classificationEvidenceSourceId='unrelated';result=buildEuropeFoundation({...input([row],[preferred]),references:{rows:[preferred],sources:other}});assert.equal(result.layer.listings[0].listingType,'PREFERRED');assert.equal(result.layer.listings[0].classificationProvenance.url,other.unrelated.url);});

test('multiple directory aliases of one newly prepared listing do not inflate protected-base counts',()=>{const result=buildEuropeFoundation(input([row,{...row,providerSymbol:'AIR.PA'}]));assert.equal(result.layer.listings.length,1);assert.equal(result.summary.metadataRecordsAdded,1);assert.equal(result.summary.protectedBaseOverlapListings,0);assert.equal(result.summary.overlapPreserved,0);assert.equal(result.summary.metadataAliasObservationsCollapsed,1);});

test('regional German census-only observations cannot automatically expand the canonical foundation',()=>{const result=buildEuropeFoundation(input([{...row,foundationEligibility:'CENSUS_ONLY_SECONDARY_GERMAN_VENUE'}]));assert.equal(result.layer.listings.length,0);assert.equal(result.summary.metadataRecordsAdded,0);assert.equal(result.summary.censusOnlyCandidates,1);});

test('official T7 CS grants generic equity identity while issuer and preference rights remain unresolved',()=>{const t7={...ref,mic:'XETR',sourceId:'T7',symbol:'LOCAL',classificationSourceId:null,classificationEvidenceSourceId:null,classificationState:'OFFICIAL_XETRA_CS_SHARE_SUBTYPE_UNRESOLVED',officialSecurityTypeCode:'CS',listingType:'PREFERRED_HINT'};const official={source_system:'DEUTSCHE_BOERSE_XETRA_T7_REFERENCE',source_url:'https://official.example/t7.csv',sha256:'5'.repeat(64)};const result=buildEuropeFoundation({universe:{listings:[{...row,providerSymbol:'LOCAL.DE',mic:'XETR',listingCountry:'DE'}]},references:{rows:[t7],sources:{T7:official}}});assert.equal(result.layer.listings[0].listingType,'PREFERRED_HINT');assert.equal(result.layer.listings[0].country,null);assert.equal(result.layer.listings[0].coverage.price_history,'NONE');});
