import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createCollector,seedPages,requestKey,verifiedTaskMetadata} from '../../scripts/market/scale-marketstack.mjs';
const roots=[];const root=()=>{const p=mkdtempSync(join(tmpdir(),'vu-scale-'));roots.push(p);return p;};
process.on('exit',()=>roots.forEach(p=>rmSync(p,{recursive:true,force:true})));
const response=(offset,total,rows)=>({ok:true,data:{pagination:{limit:1000,offset,count:rows.length,total},data:{tickers:rows}}});
test('request cache keys preserve qualified venue and sorted parameters',()=>{assert.equal(requestKey('/eod',{symbols:'SAP.DE',exchange:'XETR'}),requestKey('eod',{exchange:'XETR',symbols:'SAP.DE'}));assert.notEqual(requestKey('eod',{exchange:'XETR'}),requestKey('eod',{exchange:'XFRA'}));});
test('seeded partial directory resumes without downloading cached first page',async()=>{const out=root();let calls=[];const rows=Array.from({length:1000},(_,i)=>({symbol:'S'+i}));const seed={endpoints:[{endpoint:'exchanges/XETR/tickers',params:{limit:1000,offset:0},...response(0,1001,rows)}]};const client={request:async(e,p)=>{calls.push(p.offset);return response(p.offset,1001,[{symbol:'LAST'}]);},stats:()=>({requestsAttempted:1,estimatedCreditsConsumed:1})};const c=createCollector({output:out,phase:'discovery',seeds:[seed],client});assert.equal((await c.directory('XETR')).complete,true);assert.deepEqual(calls,[1000]);});
test('unknown seed total never becomes a measured complete directory',async()=>{const seed={endpoints:[{ok:true,endpoint:'exchanges/XETR/tickers',data:{data:{tickers:[{symbol:'SAP.DE'}]}}}]};assert.equal(seedPages(seed)[0].data.pagination.total,null);const c=createCollector({output:root(),seeds:[seed],client:{stats:()=>({requestsAttempted:0,estimatedCreditsConsumed:0})}});assert.equal((await c.directory('XETR')).reason,'invalidPaginationTotal');});
test('changing totals abort pagination without claiming completeness',async()=>{let n=0;const c=createCollector({output:root(),client:{request:async()=>response(n++?1000:0,n===1?1002:1003,Array.from({length:n===1?1000:3},()=>({symbol:'S'}))),stats:()=>({requestsAttempted:n,estimatedCreditsConsumed:n})}});const r=await c.directory('XETR');assert.equal(r.complete,false);assert.equal(r.reason,'invalidPaginationTotal');});
test('same run resume reserves opening credits and attempts against total ceiling',async()=>{const out=root();writeFileSync(join(out,'checkpoint.json'),JSON.stringify({tasks:{},runs:{same:{phase:'test',requestsAttempted:2,estimatedCreditsConsumed:2},other:{phase:'test',requestsAttempted:1,estimatedCreditsConsumed:1}}}));const c=createCollector({output:out,runId:'same',phase:'test',clientOptions:{apiKey:'test-only',fetchImpl:()=>{throw Error('unexpected fetch');}},maxCredits:3,maxRequests:3,totalCredits:4});const r=await c.query('eod',{symbols:'A,B'});assert.equal(r.reason,'budgetExceeded');assert.equal(c.finish().totalScaleCredits,3);});
test('corrupt request ledger fails before external fetch',()=>{const out=root();writeFileSync(join(out,'checkpoint.json'),JSON.stringify({tasks:{},runs:{old:{requestsAttempted:1,estimatedCreditsConsumed:-1}}}));assert.throws(()=>createCollector({output:out}),/INVALID_REQUEST_LEDGER/);});
test('production dataset outputs are rejected',()=>{assert.throws(()=>createCollector({output:'/tmp/quant/data/scale'}),/PRIVATE_WORKING/);});
test('cached provider failures are retained without automatic credit-wasting retries',async()=>{let attempts=0;const c=createCollector({output:root(),client:{request:async()=>{attempts++;return {ok:false,reason:'dataUnavailable'};},stats:()=>({requestsAttempted:attempts,estimatedCreditsConsumed:attempts})}});await c.query('tickers/NO');await c.query('tickers/NO');assert.equal(attempts,1);assert.equal(c.allEntries().length,1);assert.equal(c.finish().totalScaleCredits,1);});

test('holdings require successful exact symbol ETF metadata at an explicit matching MIC',()=>{const task={endpoint:'etfholdings',params:{ticker:'FUND'},mic:'XETR',requiresAssetType:'ETF'};const e={ok:true,data:{symbol:'FUND',item_type:'etf',stock_exchange:{mic:'XETR'}}};assert.equal(verifiedTaskMetadata(e,task),true);assert.equal(verifiedTaskMetadata(e,{...task,mic:null}),false);assert.equal(verifiedTaskMetadata({...e,ok:false},task),false);assert.equal(verifiedTaskMetadata(e,{...task,mic:'XLON'}),false);assert.equal(verifiedTaskMetadata({...e,data:{...e.data,item_type:'equity'}},task),false);assert.equal(verifiedTaskMetadata({...e,data:{...e.data,symbol:'OTHER'}},task),false);});

test('provider account quota and authentication failure stop further external attempts',async()=>{for(const reason of ['quotaExceeded','authError','accountingPersistenceFailed','rateLimited']){let attempts=0;const c=createCollector({output:root(),client:{request:async()=>{attempts++;return {ok:false,reason};},stats:()=>({requestsAttempted:attempts,estimatedCreditsConsumed:attempts})}});await c.query('tickers/A');const r=await c.query('tickers/B');assert.equal(attempts,1);assert.equal(r.reason,reason);assert.equal(c.finish().terminalReason,reason);}});
