import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtempSync,rmSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ingestListings} from '../../scripts/market/ingest-marketstack.mjs';
const {createMarketStore}=createRequire(import.meta.url)('../engines/market-store.js');
const listing={listingId:'vu_123abc',securityId:'sec_123',ticker:'SAP',exchange:'Xetra',mic:'XETR',assetType:'EQUITY',classificationSource:'official',listingCountry:'DE',tradingCurrency:'EUR',source:'reference',sourceUpdatedAt:'2026-10-01T00:00:00Z'};
const layer={schemaVersion:'global-market-1.0.0',listings:[listing]};
function make(){const root=mkdtempSync(join(tmpdir(),'vu-ingest-'));const store=createMarketStore({root,providerId:'marketstack'});return {root,store};}
const bar=date=>({securityId:listing.securityId,date,open:100,high:102,low:99,close:101,volume:null,currency:'EUR'});
test('backfill checkpoints completed windows and resumes after budget exhaustion',async()=>{const {root,store}=make();try{let calls=[];let fail=true;const provider={stats:()=>({requestsAttempted:calls.length}),getDailyBars:async(id,opts)=>{calls.push(opts);if(fail&&calls.length===2)return {available:false,reason:'budgetExceeded'};return {available:true,complete:true,data:{bars:[bar(opts.from)],adjustmentStatus:'unknown'},provenance:{}};}};
const first=await ingestListings({layer,store,provider,initial:true,from:'2024-01-01',to:'2026-01-01'});assert.equal(first.remaining,1);assert.equal(store.readBars(listing.listingId).bars.length,1);assert.equal(store.readBars(listing.listingId).securityId,listing.securityId);assert.equal(store.readBars(listing.listingId).storageKey,listing.listingId);assert.equal(calls[0].to,'2024-12-30');const resumeFrom=calls[1].from;fail=false;calls=[];const second=await ingestListings({layer,store,provider,initial:true,from:'2024-01-01',to:'2026-01-01'});assert.equal(calls[0].from,resumeFrom);assert.equal(second.remaining,0);const total=store.readBars(listing.listingId).bars.length;calls=[];await ingestListings({layer,store,provider,initial:true,from:'2024-01-01',to:'2026-01-01'});assert.equal(calls.length,0);assert.equal(store.readBars(listing.listingId).bars.length,total);assert.equal(existsSync(join(root,'quant/data/market/daily')),false);}finally{rmSync(root,{recursive:true,force:true});}});
test('invalid currency, incomplete page sets and impossible OHLC never overwrite history',async()=>{for(const mode of ['currency','incomplete','ohlc']){const {root,store}=make();try{const provider={stats:()=>({requestsAttempted:1}),getDailyBars:async()=>({available:true,complete:mode!=='incomplete',data:{bars:[{...bar('2026-09-30'),...(mode==='currency'?{currency:'USD'}:{}),...(mode==='ohlc'?{low:200}:{})}]}})};const r=await ingestListings({layer,store,provider,from:'2026-09-30',to:'2026-09-30'});assert.equal(r.remaining,1);assert.equal(store.readBars(listing.listingId),null);}finally{rmSync(root,{recursive:true,force:true});}}});
test('incremental runs fetch after last stored date and preserve prior bars',async()=>{const {root,store}=make();try{store.mergeBars(listing.listingId,[bar('2026-09-29')]);const calls=[];const provider={stats:()=>({requestsAttempted:1}),getDailyBars:async(id,opts)=>{calls.push(opts);return {available:true,data:{bars:[bar('2026-09-30')]}};}};await ingestListings({layer,provider,store,from:'2020-01-01',to:'2026-09-30',runId:'incremental-2026-10-01'});assert.equal(calls[0].from,'2026-09-30');assert.equal(store.readBars(listing.listingId).bars.length,2);}finally{rmSync(root,{recursive:true,force:true});}});
test('changed backfill scope retries earlier dates and explicit checkpoint scope mismatch fails closed',async()=>{const {root,store}=make();try{let calls=[];const provider={stats:()=>({requestsAttempted:calls.length}),getDailyBars:async(id,opts)=>{calls.push(opts);return {available:true,data:{bars:[bar(opts.from)]}};}};await ingestListings({layer,store,provider,initial:true,from:'2026-09-29',to:'2026-09-29',runId:'explicit'});await assert.rejects(ingestListings({layer,store,provider,initial:true,from:'2026-09-28',to:'2026-09-29',runId:'explicit'}),/CHECKPOINT_SCOPE/);calls=[];await ingestListings({layer,store,provider,initial:true,from:'2026-09-28',to:'2026-09-29'});assert.equal(calls[0].from,'2026-09-28');}finally{rmSync(root,{recursive:true,force:true});}});
test('normalization anomalies leave window unresolved instead of silently dropping candles',async()=>{const {root,store}=make();try{const provider={stats:()=>({requestsAttempted:1}),getDailyBars:async()=>({available:true,complete:true,data:{bars:[bar('2026-09-30')],anomalies:[{date:'2026-09-29',reason:'invalidOHLC'}]}})};const result=await ingestListings({layer,store,provider,from:'2026-09-29',to:'2026-09-30'});assert.equal(result.remaining,1);assert.equal(store.readBars(listing.listingId),null);}finally{rmSync(root,{recursive:true,force:true});}});

test('a reused working storage key cannot mix canonical securities or currencies',async()=>{const {root,store}=make();try{store.mergeBars(listing.listingId,[{...bar('2026-09-29'),currency:'USD'}]);const provider={stats:()=>({requestsAttempted:0}),getDailyBars:async()=>{throw Error('must not fetch');}};await assert.rejects(ingestListings({layer,provider,store,from:'2026-09-30',to:'2026-09-30'}),/STORED_LISTING_IDENTITY_OR_CURRENCY_MISMATCH/);assert.equal(store.readBars(listing.listingId).bars[0].currency,'USD');}finally{rmSync(root,{recursive:true,force:true});}});
