import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),P=require('../api/portfolio-workspace.js');
const quote=(ticker,price,asOf='2026-09-08')=>({ticker,name:ticker,state:'AVAILABLE',marketState:'AVAILABLE',asOf,price:{state:'AVAILABLE',unit:'USD',value:price}});
const universe={state:'AVAILABLE',stocks:[quote('NVDA',225.73),quote('MSFT',500)]};
test('manual quantities use scoped real prices and complete weights',()=>{const m=P.build([{ticker:'NVDA',quantity:10},{ticker:'MSFT',quantity:2}],universe);assert.equal(m.state,'AVAILABLE');assert.ok(Math.abs(m.total-3257.3)<1e-9);assert.ok(Math.abs(m.positions.reduce((s,p)=>s+p.weight,0)-1)<1e-12);assert.equal(m.asOf,'2026-09-08');assert.equal(P.build([],universe).state,'EMPTY');});
test('missing, future, denied, mixed-date and wrong-currency prices never produce a partial total',()=>{
 for(const u of [{state:'UNAVAILABLE',stocks:[]},{state:'AVAILABLE',stocks:[quote('NVDA',225.73)]},{state:'AVAILABLE',stocks:[quote('NVDA',225.73),quote('MSFT',500,'2099-01-01')]},{state:'AVAILABLE',stocks:[quote('NVDA',225.73),quote('MSFT',500,'2026-09-07')]},{state:'AVAILABLE',stocks:[quote('NVDA',225.73),{...quote('MSFT',500),marketState:'UNAVAILABLE'}]},{state:'AVAILABLE',stocks:[quote('NVDA',225.73),{...quote('MSFT',500),price:{state:'AVAILABLE',unit:'EUR',value:500}}]}]){const m=P.build([{ticker:'NVDA',quantity:1},{ticker:'MSFT',quantity:1}],u);assert.equal(m.state,'INCOMPLETE');assert.equal(m.total,null);assert.ok(m.positions.every(p=>p.weight===null));assert.equal(m.positions.length,2);}
});
test('invalid quantities, duplicate tickers and valuation overflow fail explicitly',()=>{for(const ps of [[{ticker:'NVDA',quantity:0}],[{ticker:'NVDA',quantity:NaN}],[{ticker:'../NVDA',quantity:1}],[{ticker:'NVDA',quantity:1},{ticker:'NVDA',quantity:2}]])assert.throws(()=>P.validate(ps));assert.equal(P.build([{ticker:'NVDA',quantity:1e308}],universe).total,null);});
test('holdings persist without seed positions; corrupt data is not overwritten by reading',()=>{let raw=null;const storage={getItem:()=>raw,setItem:(k,v)=>{raw=v;}};assert.deepEqual(P.load(storage),[]);const ps=[{ticker:'NVDA',quantity:1.5}];P.save(storage,ps);assert.deepEqual(P.load(storage),ps);raw='broken';assert.throws(()=>P.load(storage),/INVALID_SAVED/);assert.equal(raw,'broken');});
