import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";
import { createRequire } from "node:module";
import { materialize } from "../../scripts/technical/materialize-product-intelligence.mjs";

const require = createRequire(import.meta.url);
const Product = require("../engines/technical/product-materialization.js");
const TechnicalWorkspace = require("../api/technical-workspace-contract.js");
const Service = require("../api/product-services.js");
const Policy = require("../engines/display-policy.js");
const Query = require("../engines/query.js");
const root = new URL("../../", import.meta.url).pathname;

test("existing canonical histories materialize static Technical, Signals and Elliott Product Data", async () => {
  const dir = mkdtempSync(join(tmpdir(), "vu-product-intelligence-"));
  const work = join(dir, "work", "tiingo", "daily"), out = join(dir, "out");
  mkdirSync(work, { recursive: true });
  for (const ticker of ["NVDA", "MSFT"]) copyFileSync(join(root, "quant/data/market/golden-preview/daily/ref_" + ticker + ".json"), join(work, "ref_" + ticker + ".json"));
  const summary = materialize({ workDir: join(dir, "work"), outDir: out, tickers: ["NVDA", "MSFT"] });
  assert.equal(summary.counts.productUniverse, 2);
  assert.equal(summary.counts.historiesValidated, 2);
  assert.equal(summary.counts.technicalFullBundles, 2);
  assert.equal(summary.counts.signalsCapable, 2);
  assert.equal(summary.counts.elliottCapable, 2);
  assert.equal(summary.counts.corporateActionsValidated, 2);
  assert.equal(summary.counts.calendarValidated, 2);
  const shard = JSON.parse(gunzipSync(readFileSync(join(out, "NV.json.gz"))));
  assert.equal(Product.validateShard(shard, "NV"), true);
  const source = shard.instruments.NVDA;
  assert.equal(source.provenance.historyOwner, "quant/engines/history-store.js");
  assert.equal(source.provenance.corporateActionReconciliation.status, "PASS");
  assert.equal(source.bars.timestamps.length, 270);
  assert.equal(TechnicalWorkspace.build(source, { ticker: "NVDA" }).state, "AVAILABLE");
  const signals = JSON.parse(gunzipSync(readFileSync(join(out, "signals-60.json.gz"))));
  assert.equal(signals.scope, "CANONICAL_PRODUCT_UNIVERSE");
  assert.equal(signals.counts.requested, 2);
  assert.equal(signals.counts.available, 2);
  const loadJSON = async path => JSON.parse(readFileSync(join(root, path.slice(1)), "utf8"));
  const loadCompressedJSON = async path => JSON.parse(gunzipSync(readFileSync(join(out, path.split("/").at(-1)))));
  const api = Service.create({ loadJSON, loadCompressedJSON, displayPolicy: Policy, queryEngine: Query });
  assert.equal((await api.getTechnicalWorkspace("NVDA")).state, "AVAILABLE");
  const delivered = await api.getSignals({ lookback: 60 });
  assert.equal(delivered.scope, "CANONICAL_PRODUCT_UNIVERSE");
  assert.equal(delivered.coverage.available, 2);
});

test("Technical materialization remains independent when the Signals contract rejects provenance", () => {
  const dir = mkdtempSync(join(tmpdir(), "vu-product-intelligence-independent-"));
  const work = join(dir, "work", "tiingo", "daily"), out = join(dir, "out");
  mkdirSync(work, { recursive: true });
  const source = JSON.parse(readFileSync(join(root, "quant/data/market/golden-preview/daily/ref_MSFT.json"), "utf8"));
  source.currency = "EUR";
  writeFileSync(join(work, "ref_MSFT.json"), JSON.stringify(source));
  const summary = materialize({ workDir: join(dir, "work"), outDir: out, tickers: ["MSFT"] });
  assert.equal(summary.counts.signalsCapable, 0);
  assert.equal(summary.counts.technicalFullBundles, 1);
  assert.equal(summary.reasons.SIGNAL_INVALID_SIGNAL_PROVENANCE, 1);
  const shard = JSON.parse(gunzipSync(readFileSync(join(out, "MS.json.gz"))));
  assert.equal(TechnicalWorkspace.build(shard.instruments.MSFT, { ticker: "MSFT" }).state, "AVAILABLE");
});
