import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {validatePreviewQa,validatePreparedHistoryPlan} from '../../scripts/market/tiingo2-finalize-preview.mjs';import {budgets} from '../../scripts/vu2/resource-budget.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function fixture(){const readinessBytes=Buffer.from(JSON.stringify({runId:'qa-fixture',rows:[{ticker:'FIG',securityId:'ref_FIG',instrumentId:'vu_1234',canonicalStatus:'CANONICAL_READY'}]})),hash=sha(readinessBytes);return {
 summary:{runId:'qa-fixture',attachmentBlocker:null,removed:0,productionWrites:0,currentProduction:6419,proposedConsumer:6420,canonicalMaterialized:1},readinessBytes,
 shadowQa:{schemaVersion:'tiingo2-product-shadow-qa-1',sourceReadinessSha256:hash,productionWrites:0,scope:['FIG'],findings:[],checks:[{name:'PROTECTED_PRODUCTION_BASELINE_BYTES',status:'PASS'}]},
 browserQa:['chromium','webkit'].map(engine=>({schemaVersion:'tiingo2-product-browser-qa-1',engine,runId:'qa-fixture',sourceReadinessSha256:hash,scopedTitles:1,productionWrites:0,findings:[],checks:[{name:'CANONICAL_SYMBOL_SEARCH',ticker:'FIG',status:'PASS'}]})),
 legacyBrowser:{checks:Array.from({length:88},(_,i)=>({name:'contract-fixture-'+i,pass:true})),findings:[]},accessibility:{results:Array.from({length:76},(_,i)=>({route:'contract-fixture-'+i,violations:[]}))},
 resources:{results:[1440,390].flatMap(width=>Object.keys(budgets).map(view=>({view,width,budget:{...budgets[view]},decodedBytes:Math.min(1000,budgets[view].decodedBytes),requests:1,pass:true})))},smoke:{clean:true,failures:0,checks:148},release:{status:'PASS'}};}
// Fixtures are contract examples, not evidence of a live materialization.
test('finalization validates complete dual-engine QA with unchanged resource budgets',()=>{const f=fixture();assert.equal(f.resources.results.length,8);const result=validatePreviewQa(f);assert.equal(result.scopedTitles,1);assert.deepEqual(result.engines,['chromium','webkit']);});
test('finalization rejects changed source readiness and omitted WebKit',()=>{const changed=fixture();changed.readinessBytes=Buffer.from(JSON.stringify({rows:[{ticker:'OTHER'}]}));assert.throws(()=>validatePreviewQa(changed));const missing=fixture();missing.browserQa=missing.browserQa.filter(r=>r.engine==='chromium');assert.throws(()=>validatePreviewQa(missing),/SCOPED_BROWSER_QA_NOT_GREEN/);});
test('finalization rejects any product, accessibility, smoke or attachment failure',()=>{for(const mutate of [f=>{f.shadowQa.findings.push({name:'IDENTITY_CHANGED'});},f=>{f.browserQa[1].checks[0].status='FAIL';},f=>{f.legacyBrowser.checks[0].pass=false;},f=>{f.accessibility.results[0].violations.push({id:'contrast'});},f=>{f.smoke.clean=false;},f=>{f.summary.attachmentBlocker='IDENTITY_COLLISION';},f=>{f.release.status='FAIL';}]){const f=fixture();mutate(f);assert.throws(()=>validatePreviewQa(f));}});
test('finalization rejects raised budgets and genuine resource overruns',()=>{const raised=fixture();raised.resources.results.find(r=>r.view==='screener').budget.decodedBytes++;assert.throws(()=>validatePreviewQa(raised),/RESOURCE_BUDGET/);const over=fixture();over.resources.results.find(r=>r.view==='screener').decodedBytes=budgets.screener.decodedBytes+1;assert.throws(()=>validatePreviewQa(over),/RESOURCE_BUDGET/);});
test('finalization rejects duplicated measurements that omit Screener and mobile views',()=>{const f=fixture(),home=f.resources.results.find(r=>r.view==='home'&&r.width===1440);f.resources.results=Array.from({length:8},()=>({...home}));assert.throws(()=>validatePreviewQa(f),/RESOURCE_BUDGET/);});
test('finalization rejects absent, NaN, infinite and negative resource measurements',()=>{for(const field of ['decodedBytes','requests'])for(const value of [undefined,NaN,Infinity,-1]){const f=fixture();f.resources.results[0][field]=value;assert.throws(()=>validatePreviewQa(f),/RESOURCE_BUDGET/,field+':'+value);}});
test('finalization rejects empty or duplicate canonical readiness scopes',()=>{for(const rows of [[],[{ticker:'FIG',securityId:'ref_FIG',instrumentId:'vu_1234'},{ticker:'FIG',securityId:'ref_FIG',instrumentId:'vu_1234'}]]){const f=fixture();f.readinessBytes=Buffer.from(JSON.stringify({runId:'qa-fixture',rows}));const hash=sha(f.readinessBytes);f.shadowQa.sourceReadinessSha256=hash;for(const b of f.browserQa){b.sourceReadinessSha256=hash;b.scopedTitles=rows.length;}assert.throws(()=>validatePreviewQa(f));}});
function historyFixture(){const publicationManifestSha256='a'.repeat(64),additions=[{ticker:'FIG',securityId:'ref_FIG'},{ticker:'CART',securityId:'ref_CART'}];return {publicationManifestSha256,additions,history:{publicationManifestSha256,productionWrites:0,rows:additions.map(r=>({...r,path:'private-histories/tiingo/daily/'+r.securityId+'.json',existingObjectOverwriteAllowed:false,bars:250}))}};}
test('finalization binds private history intent to the exact canonical addition identity set',()=>{assert.equal(validatePreparedHistoryPlan(historyFixture()),true);for(const mutate of [f=>{f.history.rows[0].ticker='WRONG';},f=>{f.history.rows[0].securityId='ref_WRONG';},f=>{f.history.rows[1]={...f.history.rows[0]};},f=>{f.history.rows.pop();},f=>{f.history.publicationManifestSha256='b'.repeat(64);},f=>{f.history.productionWrites=1;}]){const f=historyFixture();mutate(f);assert.throws(()=>validatePreparedHistoryPlan(f),/HISTORY.*BINDING/);}});
test('finalization rejects history path escapes, overwrite permission and unsupported short evidence',()=>{for(const mutate of [r=>{r.path='../public-provider-body.json';},r=>{r.existingObjectOverwriteAllowed=true;},r=>{r.bars=0;},r=>{r.bars=NaN;}]){const f=historyFixture();mutate(f.history.rows[0]);assert.throws(()=>validatePreparedHistoryPlan(f),/HISTORY_IDENTITY_BINDING/);}});
