import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,copyFileSync,existsSync,unlinkSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {gzipSync} from 'node:zlib';
import {stageCanonicalPublication,attachCanonicalProjections,applyCanonicalPublication,verifyStagedCanonicalPublication,REQUIRED_PUBLICATION_QA,PRODUCTIZATION_QA_SCHEMA,CANONICAL_PUBLICATION_PATHS as paths} from '../../scripts/market/tiingo2-publication.mjs';
import {prepareHistoryPublication} from '../../scripts/market/tiingo2-history-preparation.mjs';
import {prepareRefreshedPublicationPackage,validateOriginalPublicationPackage,validateSourceOnlyHistoricalProvenance,validateSourceOnlyCurrencyDebtMetadata,validateNewCanonicalStorageMigrations,verifyCanonicalMigrationObservations,rebindFinalProductizationReadiness,rebindCurrentFundamentalsArtifacts,rebindCurrentQuantEvidenceArtifacts} from '../../scripts/market/tiingo2-refresh-publication-package.mjs';
const Company=createRequire(import.meta.url)('../../quant/engines/company-master.js'),sha=b=>createHash('sha256').update(b).digest('hex');
function fixture(fn,{currencyDebtMetadata=false}={}){const root=mkdtempSync(join(tmpdir(),'publication-refresh-')),originalPreparedRoot=join(root,'.market-cache/original/tiingo2'),workDir=join(root,'.market-cache/refreshed-work'),preparedRoot=join(root,'.market-cache/refreshed/tiingo2');
 const save=(path,doc)=>{const file=join(root,path);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,Buffer.isBuffer(doc)?doc:JSON.stringify(doc));};
 const git=(...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}),commit=()=>{git('add','quant/data','discover');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','canonical fixture');return git('rev-parse','HEAD').trim();};
 const keep={ticker:'KEEP',securityId:'ref_KEEP',exchange:'NASDAQ',active:true,assetType:'Stock',name:'Existing Software Inc'},inst=Company.toInstrument(keep,{today:'2026-10-02'});
 save(paths.raw,{securities:[keep],byExchange:{NASDAQ:1},bySector:{UNKNOWN:1}});save(paths.eligibility,{decisions:[{...keep,product_eligibility:'ELIGIBLE',instrument_type:'EQUITY_COMMON'}],counts:{universeMembers:1,productUniverse:1,ELIGIBLE:1,SEPARATE_CLASS:0,REVIEW:0,EXCLUDED:0}});save(paths.names,{rows:[{...keep,companyName:keep.name,status:'RESOLVED',inProductUniverse:true}]});save(paths.instruments+'/KE.json',{instruments:[inst]});save('discover/logos/index.json',{files:{},wide:[],dark:[]});
 const currencyPath='quant/data/market/fx/currency-debt-register.json',currencyFile='discover/engines/fundamentals.js',currencyCode='return value + " $";',currencyRegister={schema:'vu-currency-debt-register-1.0.0',generatedAtUtc:'2026-09-30T00:00:00.000Z',entries:[{file:currencyFile,line:1,rule:'trailingDollar',text:currencyCode,class:'UNCLASSIFIED'}]};
 if(currencyDebtMetadata){save(currencyFile,Buffer.from(currencyCode+'\n'));save(currencyPath,currencyRegister);}
 git('init','-q');const originalSourceCommit=commit();
 const candidate={ticker:'ZNEW',securityId:'ref_ZNEW',instrument_type:'EQUITY_COMMON',active:true,companyName:'New Software Corporation',listing:{ticker:'ZNEW',name:'New Software Corporation',assetType:'Stock',exchange:'NASDAQ',currency:'USD',startDate:'2026-09-01',endDate:'2026-10-01'},evidence:{identity:{resolved:true},price:{historyValid:true,latestValid:true,latestDate:'2026-10-01',corporateActionValid:true}}};
 let stage=stageCanonicalPublication({root,output:join(originalPreparedRoot,'canonical-stage'),candidates:[candidate],preview:{ADDED:[{ticker:'ZNEW',securityId:'ref_ZNEW'}],REMOVED:[]},runId:'original',today:'2026-10-02'}),addition=stage.additions[0];
 const chartPath='quant/data/market/discover-series/ref_ZNEW.json',docs={'quant/data/universe/master-manifest.json':{totals:{published:2},shards:{index:[{shard:'KE',count:1},{shard:'ZN',count:1}]}},'quant/data/universe/search/manifest.json':{sym:[{shard:'ZN',count:1}],name:[{shard:'00',count:1}]},'quant/data/universe/search/sym/ZN.json':{entries:[{s:'ZNEW',i:addition.instrumentId}]},'quant/data/universe/search/name/00.json':{entries:[{s:'ZNEW',i:addition.instrumentId}]},'quant/data/universe/market-capability.json':{members:[{s:'ZNEW',m:'ref_ZNEW',i:addition.instrumentId,ph:true}]},'discover/data/meta.json':{universeSource:{source:'SECURITY_MASTER',file:paths.eligibility,sha256:stage.files.find(f=>f.path===paths.eligibility).stagedSha256}},[chartPath]:{ticker:'ZNEW',securityId:'ref_ZNEW',status:'CALCULATED',priceSeriesType:'SPLIT_ADJUSTED',currency:'USD',points:Array.from({length:30},(_,i)=>['2026-09-'+String(i+1).padStart(2,'0'),10])},'discover/logos/index.json':{files:{},wide:['PASW'],wideFiles:{PASW:'files/wide/PASW.png'},dark:[]}};
 const preparedFiles=Object.entries(docs).map(([path,doc])=>({path,bytes:Buffer.from(JSON.stringify(doc))}));preparedFiles.push({path:'quant/data/product/universe-list-v1.json.gz',bytes:gzipSync(JSON.stringify({entries:[{s:'ZNEW',c:10,d:'2026-10-01'}]}))},{path:'discover/logos/files/wide/PASW.png',bytes:Buffer.from('fixture quarantined new image')});
 const products=Object.fromEntries(['QUANT','DISCOVER','SCREENER','SUPERTRADER','SEC'].map(k=>[k,{state:'UNAVAILABLE',reasonCodes:['NO_VERIFIED_DATA'],artifactPaths:[]} ]));Object.assign(products,{SEARCH:{state:'PASS',artifactPaths:['quant/data/universe/search/sym/ZN.json']},WATCHLIST:{state:'PASS',artifactPaths:[paths.instruments+'/ZN.json']},CHARTS:{state:'PASS',artifactPaths:[chartPath]}});
 stage=attachCanonicalProjections({root,staged:stage,preparedFiles,productizationReadiness:[{...addition,products}]});
 const payload={ticker:'ZNEW',securityId:'ref_ZNEW',provider:'tiingo',bars:Array.from({length:30},(_,i)=>({securityId:'ref_ZNEW',date:'2026-09-'+String(i+1).padStart(2,'0'),close:10}))},market=join(root,'.market-cache/market-store');save('.market-cache/market-store/tiingo/daily/ref_ZNEW.json',payload);
 prepareHistoryPublication({marketStoreDir:market,outputRoot:originalPreparedRoot,additions:[addition],publicationManifestSha256:stage.manifestSha256});
 const proof={schemaVersion:PRODUCTIZATION_QA_SCHEMA,manifestSha256:stage.manifestSha256,productReadinessSha256:stage.productizationReadinessSha256,checks:Object.fromEntries(REQUIRED_PUBLICATION_QA.map(k=>[k,'PASS'])),historyPlanSha256:sha(readFileSync(join(originalPreparedRoot,'history-publication-plan.json'))),productionWrites:0};save('.market-cache/original/tiingo2/canonical-stage/qa-proof.json',proof);applyCanonicalPublication({root,staged:stage,qaProof:proof});commit();
 // Final review corrects an alias, adds a native public artifact and removes
 // only a new orphan. No provider history or original baseline asset changes.
 save('discover/logos/index.json',{files:{},wide:[],dark:[]});unlinkSync(join(root,'discover/logos/files/wide/PASW.png'));save('quant/data/product/pattern-match-v1/ZN.json.gz',gzipSync(JSON.stringify({securities:{ZNEW:{native:true}}})));
 if(currencyDebtMetadata){save(currencyFile,Buffer.from('// chronology guard\nif (future) return;\n'+currencyCode+'\n'));save(currencyPath,{...currencyRegister,generatedAtUtc:'2026-10-03T00:00:00.000Z',entries:[{...currencyRegister.entries[0],line:3}]});}
 const expectedSourceCommit=commit();
 const options={root,originalPreparedRoot,workDir,preparedRoot,expectedManifestSha256:stage.manifestSha256,originalSourceCommit,expectedSourceCommit,runId:'final-package'};
 try{return fn({options,root,save,git,stage,originalPreparedRoot,proof});}finally{rmSync(root,{recursive:true,force:true});}
}
test('refresh stages committed final bytes with original rollback and exact private history, and grants no publication QA',()=>fixture(({options,originalPreparedRoot,root})=>{
 const before=readFileSync(join(root,paths.raw)),originalHistory=readFileSync(join(originalPreparedRoot,'private-histories/tiingo/daily/ref_ZNEW.json'));const result=prepareRefreshedPublicationPackage(options);
 assert.equal(result.state,'STAGED_REQUIRES_FINAL_QA');assert.equal(result.productionPublishAllowed,false);assert.equal(result.productionWrites,0);assert.equal(result.providerCalls,0);assert.equal(result.privateHistoriesRebuilt,0);assert.deepEqual(result.omittedNewAssets,['discover/logos/files/wide/PASW.png']);assert.ok(readFileSync(join(root,paths.raw)).equals(before));assert.ok(readFileSync(join(options.preparedRoot,'private-histories/tiingo/daily/ref_ZNEW.json')).equals(originalHistory));
 assert.equal(existsSync(join(dirname(result.stage),'qa-proof.json')),false);assert.equal(existsSync(join(dirname(result.stage),'applied.json')),false);
 const manifest=JSON.parse(readFileSync(result.stage));assert.ok(manifest.files.some(f=>f.path==='quant/data/product/pattern-match-v1/ZN.json.gz'));assert.ok(!manifest.files.some(f=>f.path.endsWith('/PASW.png')));assert.equal(manifest.removals.length,0);assert.equal(manifest.additions.length,1);assert.notEqual(result.manifestSha256,options.expectedManifestSha256);
 assert.equal(JSON.parse(readFileSync(join(options.preparedRoot,'history-publication-plan.json'))).publicationManifestSha256,result.manifestSha256);assert.equal(verifyStagedCanonicalPublication({root:result.baselineRoot,staged:{manifestPath:result.stage}}).manifestSha256,result.manifestSha256);
}));
test('changed original manifest, rollback or private-history bytes fail before creating refresh outputs',()=>{
 for(const path of ['canonical-stage/manifest.json','canonical-stage/rollback/'+paths.raw,'private-histories/tiingo/daily/ref_ZNEW.json'])fixture(({options,originalPreparedRoot})=>{writeFileSync(join(originalPreparedRoot,path),'{}');assert.throws(()=>prepareRefreshedPublicationPackage(options),/ORIGINAL/);assert.equal(existsSync(options.workDir),false);assert.equal(existsSync(options.preparedRoot),false);});
});
test('wrong source HEAD, uncommitted public changes and linked private inputs cannot enter a refresh',()=>{
 fixture(({options})=>assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit:'a'.repeat(40)}),/SOURCE_BINDING/));
 fixture(({options,save})=>{save(paths.raw,{securities:[]});assert.throws(()=>prepareRefreshedPublicationPackage(options),/NOT_COMMITTED/);});
 fixture(({options,originalPreparedRoot,root})=>{const path=join(originalPreparedRoot,'history-publication-plan.json');unlinkSync(path);symlinkSync(join(root,'missing'),path);assert.throws(()=>validateOriginalPublicationPackage(options),/LINK_REJECTED/);});
});
test('an existing PASW baseline asset or final wide alias cannot be removed through orphan omission',()=>fixture(({options,root,save,git})=>{
 save('discover/logos/index.json',{files:{},wide:['PASW'],wideFiles:{PASW:'files/wide/PASW.png'}});git('add','discover/logos/index.json');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','incorrect alias');const head=git('rev-parse','HEAD').trim();
 assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit:head}),/UNPROVED_REMOVAL/);
}));
test('object wide flags, shared aliases and nested credits cannot refer to the omitted asset',()=>{
 for(const [path,doc]of [['discover/logos/index.json',{files:{},wide:{PASW:true}}],['discover/logos/index.json',{files:{OTHER:'files/wide/PASW.png'},wide:{}}],['discover/logos/index.json',{files:{},wide:{},wideFiles:{ALIAS:'files/wide/PASW.png'}}],['discover/logos/credits.json',{credits:{OTHER:{wide:{path:'/discover/logos/files/wide/PASW.png'}}}}]])fixture(({options,save,git})=>{
  save(path,doc);git('add',path);git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','unsafe asset reference');const head=git('rev-parse','HEAD').trim();assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit:head}),/UNPROVED_REMOVAL/);
 });
});
test('historical source-only exception verifies exact audit rows and original Git/raw snapshot bytes',()=>{
 const root=mkdtempSync(join(tmpdir(),'source-provenance-refresh-')),shadow=join(root,'shadow'),source=paths.raw,path='quant/data/market/security-master/reconciliation.json';const save=(base,p,d)=>{mkdirSync(dirname(join(base,p)),{recursive:true});writeFileSync(join(base,p),Buffer.isBuffer(d)?d:JSON.stringify(d));},git=(...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:'pipe'});
 try{const bytes=Buffer.from(JSON.stringify({securities:[{ticker:'KEEP',securityId:'ref_KEEP'}]}));save(root,source,bytes);git('init','-q');git('add','quant');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','audit source');const auditCommit=git('rev-parse','HEAD').trim(),digest=sha(bytes),snapshot='quant/data/market/security-master/baselines/universe-FULL_UNIVERSE.'+digest+'.json.gz';
  const before={run:{commit:auditCommit},headline:{BASELINE_COUNT:1},nonDestructive:{baselineFile:source,baselineCount:1,baselinePreserved:1,baselineRemoved:0}};save(root,path,before);const after={...before,nonDestructive:{...before.nonDestructive,baselineFile:snapshot,baselineSourceFile:source,baselineSha256:digest,baselineSourceCommit:auditCommit}};save(shadow,path,after);save(shadow,snapshot,gzipSync(bytes));
  const options={baselineRoot:root,shadowRoot:shadow,changed:[path,snapshot]};assert.equal(validateSourceOnlyHistoricalProvenance(options).length,2);
  save(shadow,path,{...after,headline:{BASELINE_COUNT:2}});assert.throws(()=>validateSourceOnlyHistoricalProvenance(options),/AUDIT_ROWS_CHANGED/);save(shadow,path,after);
  save(shadow,snapshot,gzipSync(Buffer.from(JSON.stringify({securities:[{ticker:'CHANGED',securityId:'ref_CHANGED'}]}))));assert.throws(()=>validateSourceOnlyHistoricalProvenance(options),/SNAPSHOT_NOT_ORIGINAL/);
  assert.throws(()=>validateSourceOnlyHistoricalProvenance({...options,changed:[path,snapshot,'quant/data/market/security-master/baselines/other.json.gz']}),/PROVENANCE_INVALID/);
 }finally{rmSync(root,{recursive:true,force:true});}
});

function currencyDebtMetadataFixture(fn){
 const root=mkdtempSync(join(tmpdir(),'currency-debt-metadata-')),baselineRoot=join(root,'baseline'),shadowRoot=join(root,'final'),path='quant/data/market/fx/currency-debt-register.json',file='discover/engines/fundamentals.js',code='return value + " $";'+ ' '.repeat(170)+'/* preserved full source tail */';
 const save=(base,p,value)=>{mkdirSync(dirname(join(base,p)),{recursive:true});writeFileSync(join(base,p),typeof value==='string'?value:JSON.stringify(value));};
 const before={schema:'vu-currency-debt-register-1.0.0',generatedAtUtc:'2026-09-30T07:16:32.148Z',total:1,byClass:{UNCLASSIFIED:1},classes:{UNCLASSIFIED:{label:'UNCLASSIFIED'}},filesAffected:1,openClassA:0,entries:[{file,line:1,rule:'trailingDollar',class:'UNCLASSIFIED',text:code.slice(0,160),declaredReason:null}]},after=structuredClone(before);after.generatedAtUtc='2026-10-03T05:38:26.503Z';after.entries[0].line=3;
 const originalSource=code+'\n',finalSource='// chronology guard\nif (future) return;\n'+code+'\n';
 save(baselineRoot,path,before);save(shadowRoot,path,after);save(baselineRoot,file,originalSource);save(shadowRoot,file,finalSource);
 const options={baselineRoot,shadowRoot,changed:[path]};try{return fn({root,path,file,code,before,after,originalSource,finalSource,save,options});}finally{rmSync(root,{recursive:true,force:true});}
}
test('FX register source-only exemption binds identical entries and real moved code references, never FX projections',()=>currencyDebtMetadataFixture(c=>{
 const a=readFileSync(join(c.options.baselineRoot,c.path)),b=readFileSync(join(c.options.shadowRoot,c.path)),proof=validateSourceOnlyCurrencyDebtMetadata(c.options);assert.equal(proof.length,1);assert.equal(proof[0].category,'SOURCE_ONLY_CURRENCY_DEBT_METADATA');assert.equal(proof[0].beforeSha256,sha(a));assert.equal(proof[0].sha256,sha(b));assert.deepEqual(proof[0].movedReferences,[{file:c.file,rule:'trailingDollar',beforeLine:1,line:3}]);assert.equal(proof[0].sourceFiles[0].sha256,sha(Buffer.from(c.finalSource)));assert.equal(proof[0].entryCount,1);assert.deepEqual(validateSourceOnlyCurrencyDebtMetadata({...c.options,changed:['quant/data/market/fx/current.json']}),[]);assert.ok(readFileSync(join(c.options.baselineRoot,c.path)).equals(a));assert.ok(readFileSync(join(c.options.shadowRoot,c.path)).equals(b));
}));
test('FX metadata exemption rejects changed classifications/counts/entries, fake locations, changed full source or unsafe paths',()=>{
 const changes=[c=>c.after.total++,c=>c.after.entries[0].class='A',c=>c.after.byClass.A=1,c=>c.after.entries[0].text='changed',c=>c.after.entries[0].rule='germanScaleDollar',c=>c.after.entries[0].file='../outside.js',c=>c.after.entries.push({...c.after.entries[0]}),c=>c.after.entries[0].line=1,c=>c.after.entries[0].line=999,c=>c.after.entries[0].line=1.5,c=>c.after.generatedAtUtc='invalid',c=>c.after.generatedAtUtc='2026-09-01T00:00:00.000Z',c=>c.save(c.options.shadowRoot,c.file,c.finalSource.replace('preserved full source tail','modified hidden source tail')),c=>{const source=join(c.options.shadowRoot,c.file),outside=join(c.root,'outside.js');writeFileSync(outside,c.finalSource);unlinkSync(source);symlinkSync(outside,source);}];
 for(const change of changes)currencyDebtMetadataFixture(c=>{change(c);c.save(c.options.shadowRoot,c.path,c.after);assert.throws(()=>validateSourceOnlyCurrencyDebtMetadata(c.options),/REFRESH_CURRENCY_DEBT|REFRESH_LINK_REJECTED|REFRESH_PATH_REJECTED/);});
});
test('full package refresh records FX source-only proof without publishing the register, and rejects unrelated FX data',()=>{
 fixture(({options})=>{const result=prepareRefreshedPublicationPackage(options),manifest=JSON.parse(readFileSync(result.stage)),path='quant/data/market/fx/currency-debt-register.json';assert.ok(!manifest.files.some(f=>f.path===path));assert.equal(manifest.publicationRefresh.sourceOnlyCurrencyDebtMetadata.length,1);assert.equal(manifest.publicationRefresh.sourceOnlyCurrencyDebtMetadata[0].path,path);assert.deepEqual(manifest.publicationRefresh.sourceOnlyCurrencyDebtMetadata[0].movedReferences,[{file:'discover/engines/fundamentals.js',rule:'trailingDollar',beforeLine:1,line:3}]);assert.equal(result.productionWrites,0);},{currencyDebtMetadata:true});
 fixture(({options,save,git})=>{save('quant/data/market/fx/current.json',{rates:{USD:1}});git('add','quant/data/market/fx/current.json');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','unsupported FX projection');const expectedSourceCommit=git('rev-parse','HEAD').trim();assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit}),/REFRESH_UNSUPPORTED_PUBLIC_DIFF:quant\/data\/market\/fx\/current.json/);},{currencyDebtMetadata:true});
});

function canonicalMigrationFixture(fn){const root=mkdtempSync(join(tmpdir(),'sec-storage-migration-')),baselineRoot=join(root,'baseline'),shadowRoot=join(root,'final'),stage=join(root,'original-stage'),oldPath='quant/data/sec/canonical/Q.json',path=oldPath+'.gz',indexPath='quant/data/sec/canonical_index.json';
 const save=(base,p,doc)=>{mkdirSync(dirname(join(base,p)),{recursive:true});writeFileSync(join(base,p),Buffer.isBuffer(doc)?doc:JSON.stringify(doc));};
 const valid={securityId:'sec_Q',metricId:'revenue',fiscalYear:2018,fiscalPeriod:'Q2',periodEnd:'2018-06-30',value:1442.5,unit:'usd_m',currency:'USD',reportedAt:'2018-08-07',filedAt:'2018-08-07',availableAt:'2018-08-07',ingestedAt:'2026-10-02T00:00:00Z',revisionId:1,restatementStatus:'restated',sourceFilingId:'aug-q2',dataSourceId:'ds_sec_edgar_v1'},invalid={...valid,filedAt:'2018-05-07',reportedAt:'2018-05-07',availableAt:'2018-05-07',sourceFilingId:'bad-may-q1',value:1383.6,revisionId:0};
 const before={schema:'vu-canonical-v1',security:{ticker:'Q',securityId:'sec_Q',isMock:false},dataSource:{provider:'sec_edgar',isMock:false},filings:[{filingId:'aug-q2',periodEnd:'2018-06-30',filedAt:'2018-08-07'}],facts:[invalid,valid],coverage:{factCount:2},industrySpecificMetrics:null},after={...before,generatedAtUtc:'2026-10-03T00:00:00Z',facts:[{...valid,ingestedAt:'2026-10-03T00:00:00Z',revisionId:0,restatementStatus:'original'}],coverage:{factCount:1}};
 const oldBinding={ticker:'Q',securityId:'sec_Q',cik:'0000000007',file:'canonical/Q.json'},binding={...oldBinding,file:'canonical/Q.json.gz'},index={companies:[binding]};save(stage,'old.json',before);save(stage,'index.json',{companies:[oldBinding]});save(shadowRoot,indexPath,index);save(shadowRoot,paths.instruments+'/'+Company.shardKey('Q')+'.json',{instruments:[{symbol:'Q',cik:binding.cik}]});
 const original={stage,manifest:{files:[{path:oldPath,stagedPath:'old.json',stagedSha256:sha(readFileSync(join(stage,'old.json'))),baselineSha256:null},{path:indexPath,stagedPath:'index.json'}]}};
 const writeGzip=()=>save(shadowRoot,path,gzipSync(Buffer.from(JSON.stringify(after)+'\n'),{level:9,mtime:0}));writeGzip();
 try{return fn({baselineRoot,shadowRoot,original,before,after,index,oldPath,path,save,writeGzip});}finally{rmSync(root,{recursive:true,force:true});}
}
test('new SEC storage migration preserves every valid value/date, accounts impossible facts and rebinds exact readiness paths',()=>canonicalMigrationFixture(c=>{
 const result=validateNewCanonicalStorageMigrations(c);assert.equal(result.length,1);assert.equal(result[0].validFactsPreserved,1);assert.equal(result[0].withheldFacts,1);assert.equal(result[0].path,c.path);assert.equal(result[0].ticker,'Q');
 const readiness=[{ticker:'Q',products:{SEC:{state:'PASS',artifactPaths:[c.oldPath,'quant/data/sec/canonical_index.json','quant/data/sec/consumer/CIK0000000007.json']},QUANT:{state:'UNAVAILABLE',reasonCodes:['NO_FACTORS'],artifactPaths:[]}}}],rebound=rebindFinalProductizationReadiness({readiness,migrations:result});assert.deepEqual(rebound[0].products.SEC.artifactPaths,[c.path,'quant/data/sec/canonical_index.json','quant/data/sec/consumer/CIK0000000007.json','quant/data/sec/consumer/index.json']);assert.equal(readiness[0].products.SEC.artifactPaths[0],c.oldPath,'input proof stays immutable');assert.equal(rebound[0].products.QUANT.state,'UNAVAILABLE');
}));
test('SEC migration rejects invented/lost valid observations, dates, chronology and identity',()=>{
 for(const change of [c=>{c.after.facts[0].value++;},c=>{c.after.facts=[];c.after.coverage.factCount=0;},c=>{c.after.facts[0].periodEnd='2018-03-31';},c=>{c.after.facts[0].filedAt='2018-05-07';},c=>{c.after.security={...c.after.security,ticker:'OTHER'};},c=>{c.after.filings=[];}])canonicalMigrationFixture(c=>{change(c);c.writeGzip();assert.throws(()=>validateNewCanonicalStorageMigrations(c),/REFRESH_CANONICAL/);});
});
test('SEC migration rejects baseline JSON replacement, wrong CIK/index path, dual storage and non-deterministic gzip',()=>{
 for(const change of [c=>c.save(c.baselineRoot,c.oldPath,c.before),c=>{c.index.companies[0].cik='0000000008';c.save(c.shadowRoot,'quant/data/sec/canonical_index.json',c.index);},c=>{c.index.companies[0].file='canonical/Q.json';c.save(c.shadowRoot,'quant/data/sec/canonical_index.json',c.index);},c=>c.save(c.shadowRoot,c.oldPath,c.before),c=>{const bytes=readFileSync(join(c.shadowRoot,c.path));bytes.writeUInt32LE(1,4);c.save(c.shadowRoot,c.path,bytes);},c=>{c.save(c.shadowRoot,c.path,Buffer.concat([readFileSync(join(c.shadowRoot,c.path)),gzipSync(Buffer.alloc(0),{level:9,mtime:0})]));}])canonicalMigrationFixture(c=>{change(c);assert.throws(()=>validateNewCanonicalStorageMigrations(c),/REFRESH_CANONICAL/);});
});

function fundamentalMetadataFixture(fn){return canonicalMigrationFixture(c=>{
 const cik='0000000007',consumerPath='quant/data/sec/consumer/CIK'+cik+'.json';
 c.save(c.shadowRoot,paths.instruments+'/'+Company.shardKey('Q')+'.json',{instruments:[{symbol:'Q',cik,masterMemberId:'ref_Q',instrumentId:'vu_q'}]});c.save(c.shadowRoot,'quant/data/sec/consumer/index.json',{byTicker:{Q:{cik,file:'consumer/CIK'+cik+'.json'}}});
 const base={end:'2026-06-30',filed:'2026-08-07',accn:'filing-q2',through:'2026Q2',kind:'TTM'},bundle={cik,tickers:['Q'],securityIds:['ref_Q'],name:'Synthetic issuer',dataSource:{isMock:false},asOf:'2026-10-02',annual:{},quarterly:{cash_and_equivalents:[[2026,'Q2','2026-06-30',10,'2026-08-07','filing-q2',0]]},ttm:{operating_cash_flow:{...base,v:20},capital_expenditures:{...base,v:3},free_cash_flow:{end:base.end,through:base.through,kind:'TTM',v:17,derived:true,inputs:['operating_cash_flow','capital_expenditures']}},coverage:{annualYears:[2026],annualMetrics:{},quarterlyMetrics:{cash_and_equivalents:1},ttmMetrics:['capital_expenditures','free_cash_flow','operating_cash_flow'],horizons:{'3y':false,'5y':false,'10y':false,first:null,latest:null},latestAnnual:null,latestQuarter:null}};
 c.save(c.shadowRoot,consumerPath,bundle);const metrics=['capital_expenditures','cash_and_equivalents','free_cash_flow','operating_cash_flow'],fundamentals={ticker:'Q',securityId:'ref_Q',cik,identityVerified:true,pitValid:true,fundamentalsStatus:'PARTIAL',annualYears:1,quarterly:1,ttm:true,metrics,metricAvailability:{revenue:'NOT_REPORTED',net_income:'NOT_REPORTED',operating_cash_flow:'AVAILABLE',total_assets:'NOT_REPORTED',stockholders_equity:'NOT_REPORTED'},artifacts:[{path:consumerPath,sha256:'stale',bytes:1},{path:c.oldPath,sha256:'stale',bytes:1}]},rows=[{ticker:'Q',securityId:'ref_Q',instrumentId:'vu_q',fundamentals}];
 return fn({...c,root:c.shadowRoot,bundle,consumerPath,rows,saveConsumer:()=>c.save(c.shadowRoot,consumerPath,bundle)});
});}
test('derived fundamental metadata binds native fiscal scope, TTM input provenance and actual gzip bytes without changing input claims',()=>fundamentalMetadataFixture(c=>{
 const output=rebindCurrentFundamentalsArtifacts(c);assert.equal(output[0].fundamentals.annualYears,1,'examined fiscal scope may contain no annual observations');assert.equal(output[0].fundamentals.fundamentalsStatus,'PARTIAL');assert.equal(output[0].fundamentals.artifacts[1].path,c.path);assert.equal(output[0].fundamentals.artifacts[1].storage,'GZIP');assert.equal(output[0].fundamentals.artifacts[1].roundtripVerified,true);assert.equal(output[0].fundamentals.artifacts[1].sha256,sha(readFileSync(join(c.root,c.path))));assert.equal(c.rows[0].fundamentals.artifacts[1].sha256,'stale','caller metadata is untouched');
}));
test('fundamental metadata refuses stale summaries, false identity, invalid PIT and unsupported derived TTM claims',()=>{
 for(const change of [c=>c.rows[0].fundamentals.annualYears++,c=>c.rows[0].fundamentals.fundamentalsStatus='FULL',c=>c.rows[0].fundamentals.metrics.push('invented'),c=>c.rows[0].fundamentals.cik='0000000008',c=>{c.bundle.quarterly.cash_and_equivalents[0][4]='2026-05-07';c.saveConsumer();},c=>{c.bundle.ttm.free_cash_flow.v=100;c.saveConsumer();},c=>{c.bundle.ttm.operating_cash_flow.accn=null;c.saveConsumer();}])fundamentalMetadataFixture(c=>{change(c);assert.throws(()=>rebindCurrentFundamentalsArtifacts(c),/REFRESH_FUNDAMENTALS/);});
});

function quantMetadataFixture(fn){return fundamentalMetadataFixture(c=>{
 const Evidence=createRequire(import.meta.url)('../../quant/engines/factor-evidence.js'),shard=Company.shardKey('Q'),path='quant/data/product/factor-evidence-v1/'+shard+'.json.gz';
 const factors=Object.fromEntries(Evidence.FACTOR_ORDER.map(id=>[id,{state:'UNAVAILABLE',reason:'INPUT_NOT_MATERIALIZED',score:null,components:[]}]));for(const id of ['momentum','risk'])factors[id]={state:'AVAILABLE',reason:null,score:70,components:[{id:id==='momentum'?'priceReturn6m':'realizedVolatility252d',state:'AVAILABLE',reason:null,score:70}]};
 const record={ticker:'Q',securityId:'ref_Q',cik:'0000000007',asOf:'2026-10-01',bars:30,factors,composite:{state:'WITHHELD',reason:'QUANT_V2_NOT_ACTIVE'}},payload={schemaVersion:Evidence.SHARD_SCHEMA,methodologyVersion:Evidence.METHODOLOGY_VERSION,derivedFrom:Evidence.DERIVED_FROM,shard,publication:{compositeAllowed:false,rankingAllowed:false},securities:{Q:record}},factorStates=Object.fromEntries(Evidence.FACTOR_ORDER.map(id=>[id,{state:factors[id].state,reason:factors[id].reason,componentStates:factors[id].components.map(component=>({id:component.id,state:component.state,reason:component.reason}))}]));
 const quant={ticker:'Q',securityId:'ref_Q',quantStatus:'TECHNICAL_ONLY',factorDnaStatus:'PARTIAL',availableFactors:['momentum','risk'],fullQuantScoreReady:false,refreshedPrice:true,bars:30,productQuantReady:true,fullQuantScoreState:'BLOCKED_BY_EXISTING_METHODOLOGY',factorStates,canonicalEvidence:{state:'MATERIALIZED',verified:true,artifactPath:path,artifactSha256:'old-shard-hash',schemaVersion:payload.schemaVersion,methodologyVersion:payload.methodologyVersion,ticker:'Q',securityId:'ref_Q',asOf:record.asOf}},rows=[{ticker:'Q',securityId:'ref_Q',instrumentId:'vu_q',quant}];
 const writeShard=()=>c.save(c.root,path,gzipSync(Buffer.from(JSON.stringify(payload)),{level:9,mtime:0}));writeShard();c.save(c.root,'quant/methodology/quant-v2.json',{publication:{allowed:false}});return fn({...c,rows,quant,record,payload,path,writeShard});
});}
test('Quant evidence rebinds actual peer-score shard hashes while preserving native availability and globally withheld full scores',()=>quantMetadataFixture(c=>{
 c.record.factors.momentum.score=63.5;c.writeShard();const result=rebindCurrentQuantEvidenceArtifacts(c);assert.equal(result[0].quant.canonicalEvidence.artifactSha256,sha(readFileSync(join(c.root,c.path))));assert.equal(c.quant.canonicalEvidence.artifactSha256,'old-shard-hash');assert.equal(result[0].quant.quantStatus,'TECHNICAL_ONLY');assert.equal(result[0].quant.fullQuantScoreReady,false);assert.deepEqual(result[0].quant.availableFactors,['momentum','risk']);assert.deepEqual(result[0].quant.factorStates,c.quant.factorStates);
}));
test('Quant rebind rejects availability/classification upgrades, component drift, wrong canonical issuer and composite activation',()=>{
 for(const change of [c=>{c.record.factors.momentum.state='UNAVAILABLE';c.record.factors.momentum.reason='INPUT_NOT_MATERIALIZED';c.record.factors.momentum.score=null;},c=>{c.record.factors.risk.components[0].state='UNAVAILABLE';c.record.factors.risk.components[0].reason='INPUT_NOT_MATERIALIZED';},c=>{c.quant.quantStatus='PARTIAL';},c=>{c.record.securityId='ref_WRONG';},c=>{c.record.cik='0000000008';},c=>{c.quant.fullQuantScoreReady=true;},c=>{c.payload.publication.compositeAllowed=true;},c=>{c.record.composite={state:'AVAILABLE',score:99};}])quantMetadataFixture(c=>{change(c);c.writeShard();assert.throws(()=>rebindCurrentQuantEvidenceArtifacts(c),/REFRESH_QUANT/);});
});
