import {test} from 'node:test';import assert from 'node:assert/strict';
import {restoreConsumerIndexBindings,verifyConsumerBinding} from '../../scripts/market/tiingo2-consumer-index.mjs';
function fixture(){const ticker='IPO',cik='0001234567',dataSource={provider:'sec_edgar',isMock:false},security={ticker,securityId:'ref_IPO'},instrument={symbol:ticker,instrumentId:'vu_IPO',masterMemberId:'ref_IPO',issuerId:'iss_cik_'+cik,cik},canonical={ticker,cik,securityId:'sec_IPO',file:'canonical/IPO.json'},document={schema:'vu-canonical-v1',security:{ticker,securityId:'sec_IPO',isMock:false},dataSource},bundle={schema:'vu-consumer-fundamentals-1.0.0',asOf:'2026-10-02',cik,tickers:[ticker],securityIds:['ref_IPO'],dataSource,annual:{revenue:[[2025,'FY','2025-12-31',100,'2026-02-03','accn']]},quarterly:{},coverage:{annualYears:[2025],quarterlyMetrics:{},ttmMetrics:[],horizons:{'3y':false,'5y':false,'10y':false}}};return {index:{byTicker:{KEEP:{cik:'0000000001',file:'consumer/CIK0000000001.json',latestQuarter:{end:'2025-09-30'}}}},canonicalRows:[canonical],securities:[security],instruments:[instrument],bundles:new Map([[cik,bundle]]),canonicalDocuments:new Map([[ticker,document]]),tickers:[ticker],asOf:'2026-10-02'};}
test('native consumer routing is additive and retains full baseline mapping metadata and distinct SEC/listing IDs',()=>{const input=fixture(),before=structuredClone(input),result=restoreConsumerIndexBindings(input);assert.deepEqual(result.document.byTicker.KEEP,input.index.byTicker.KEEP);assert.deepEqual(result.document.byTicker.IPO,{cik:'0001234567',file:'consumer/CIK0001234567.json',annualYears:1,quarterly:0,ttm:false,h3:false,h5:false,h10:false});assert.equal(result.document.count,2);assert.equal(result.added[0].securityId,'ref_IPO');assert.deepEqual(input,before);assert.equal(restoreConsumerIndexBindings({...input,index:result.document}).added.length,0);});
test('unmaterialized SEC mapping remains unavailable without inventing fundamentals',()=>{const input=fixture();input.canonicalRows=[];const result=restoreConsumerIndexBindings(input);assert.equal(result.added.length,0);assert.equal(result.unavailable[0].reason,'CANONICAL_SEC_NOT_MATERIALIZED');assert.ok(!result.document.byTicker.IPO);});
test('wrong CIK, listing ID, ticker, issuer, source or canonical document fails closed',()=>{for(const change of [i=>i.bundles.get('0001234567').asOf='2026-10-03',i=>i.instruments[0].cik='0007654321',i=>i.instruments[0].issuerId='iss_cik_0007654321',i=>i.instruments[0].masterMemberId='ref_OTHER',i=>i.bundles.get('0001234567').securityIds=['ref_OTHER'],i=>i.bundles.get('0001234567').tickers=['OTHER'],i=>{i.canonicalRows[0].securityId='sec_OTHER';i.canonicalDocuments.get('IPO').security.securityId='sec_OTHER';},i=>i.canonicalDocuments.get('IPO').security.securityId='sec_OTHER',i=>i.canonicalDocuments.get('IPO').dataSource.isMock=true]){const i=fixture();change(i);assert.throws(()=>restoreConsumerIndexBindings(i),/IDENTITY_BINDING_FAILED/);}});
test('future periods or filings and missing accession cannot repair a consumer route',()=>{for(const change of [r=>r[2]='2026-12-31',r=>r[4]='2026-12-31',r=>r[5]='',r=>r[2]='2025-02-30']){const i=fixture();change(i.bundles.get('0001234567').annual.revenue[0]);assert.throws(()=>restoreConsumerIndexBindings(i),/PIT_BINDING_FAILED/);}});
test('duplicate canonical/listing/master identities are blocked before routing any company',()=>{for(const key of ['canonicalRows','securities','instruments']){const i=fixture();i[key].push(structuredClone(i[key][0]));assert.throws(()=>restoreConsumerIndexBindings(i),/AMBIGUOUS_IDENTITY/);}});
test('gzipped canonical reference preserves the same SEC identity convention',()=>{const i=fixture();i.canonicalRows[0].file='canonical/IPO.json.gz';assert.equal(restoreConsumerIndexBindings(i).added.length,1);i.canonicalRows[0].file='canonical/OTHER.json.gz';assert.throws(()=>restoreConsumerIndexBindings(i),/IDENTITY_BINDING_FAILED/);});

test('publication binds each new consumer route to scoped staged payloads and preserves baseline entries',async()=>{
 const {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync}=await import('node:fs'),{join,dirname}=await import('node:path'),{tmpdir}=await import('node:os'),{createHash,createRequire}=await import('node:module').then(async module=>({...module,...await import('node:crypto')}));
 const {stageCanonicalPublication,attachCanonicalProjections,CANONICAL_PUBLICATION_PATHS:p}=await import('../../scripts/market/tiingo2-publication.mjs');
 const Company=createRequire(import.meta.url)('../../quant/engines/company-master.js'),{gzipSync}=await import('node:zlib');
 for(const mutation of ['valid','baseline','extra','wrongCik','wrongCount']){
  const root=mkdtempSync(join(tmpdir(),'vu-consumer-route-'));try{
   const write=(path,doc)=>{mkdirSync(dirname(join(root,path)),{recursive:true});writeFileSync(join(root,path),JSON.stringify(doc));},keep={ticker:'KEEP',securityId:'ref_KEEP',exchange:'NASDAQ',active:true,assetType:'Stock',name:'Existing Software Inc'},instrument=Company.toInstrument(keep,{today:'2026-10-02'});instrument.instrumentId=Company.mintInstrumentId(keep,0);
   write(p.raw,{securities:[keep],actualSize:1,byExchange:{NASDAQ:1},bySector:{UNKNOWN:1}});write(p.eligibility,{version:'us-security-master-1.2.0',decisions:[{...keep,product_eligibility:'ELIGIBLE',instrument_type:'EQUITY_COMMON'}],counts:{universeMembers:1,ELIGIBLE:1,SEPARATE_CLASS:0,EXCLUDED:0,REVIEW:0,productUniverse:1},nonDestructive:{}});write(p.names,{version:'company-names-1.0.0',rows:[{...keep,companyName:keep.name,inProductUniverse:true,status:'RESOLVED',nameSource:'TIINGO_METADATA'}],master:{},counts:{}});
   const shardPath=p.instruments+'/'+Company.shardKey('KEEP')+'.json';write(shardPath,{shard:Company.shardKey('KEEP'),count:1,instruments:[instrument]});
   const input=fixture(),restored=restoreConsumerIndexBindings(input).document;write('quant/data/sec/consumer/index.json',input.index);
   const listing={ticker:'IPO',name:'IPO Software Inc',assetType:'Stock',exchange:'NASDAQ',currency:'USD',startDate:'2026-09-01',endDate:'2026-10-01'},candidate={ticker:'IPO',securityId:'ref_IPO',instrument_type:'EQUITY_COMMON',active:true,companyName:listing.name,listing,evidence:{identity:{resolved:true},price:{historyValid:true,latestValid:true,latestDate:'2026-10-01',corporateActionValid:true}}},baselineHashes=Object.fromEntries([p.raw,p.eligibility,p.names,shardPath].map(path=>[path,createHash('sha256').update(readFileSync(join(root,path))).digest('hex')]));
   const staged=stageCanonicalPublication({root,output:join(root,'stage'),candidates:[candidate],preview:{ADDED:[{ticker:'IPO',securityId:'ref_IPO'}],REMOVED:[]},baselineHashes,runId:'consumer-binding',today:'2026-10-02'});
   const memberFile=staged.files.find(f=>f.path===p.instruments+'/'+Company.shardKey('IPO')+'.json'),members=JSON.parse(readFileSync(join(dirname(staged.manifestPath),memberFile.stagedPath)));Object.assign(members.instruments[0],{cik:'0001234567',issuerId:'iss_cik_0001234567'});
   if(mutation==='baseline')restored.byTicker.KEEP.cik='0001234567';if(mutation==='extra')restored.byTicker.EXTRA=restored.byTicker.IPO;if(mutation==='wrongCik')restored.byTicker.IPO.cik='0007654321';if(mutation==='wrongCount')restored.count=999;
   const addition=staged.additions[0],entry={s:'IPO',i:addition.instrumentId},newShard=Company.shardKey('IPO');
   const docs={'quant/data/universe/master-manifest.json':{totals:{published:2},shards:{index:[{shard:Company.shardKey('KEEP'),count:1},{shard:newShard,count:1}]}},'quant/data/universe/search/manifest.json':{sym:[{shard:newShard,count:1}],name:[{shard:'00',count:1}]},['quant/data/universe/search/sym/'+newShard+'.json']:{entries:[entry]},'quant/data/universe/search/name/00.json':{entries:[entry]},'quant/data/universe/market-capability.json':{members:[{...entry,m:'ref_IPO',ph:true}]},'discover/data/meta.json':{universeSource:{source:'SECURITY_MASTER',file:p.eligibility,sha256:staged.files.find(row=>row.path===p.eligibility).stagedSha256}},[memberFile.path]:members,'quant/data/sec/canonical_index.json':{companies:input.canonicalRows},'quant/data/sec/canonical/IPO.json':input.canonicalDocuments.get('IPO'),'quant/data/sec/consumer/CIK0001234567.json':input.bundles.get('0001234567'),'quant/data/sec/consumer/index.json':restored},attach=()=>attachCanonicalProjections({root,staged,preparedFiles:[...Object.entries(docs).map(([path,doc])=>({path,bytes:Buffer.from(JSON.stringify(doc))})),{path:'quant/data/product/universe-list-v1.json.gz',bytes:gzipSync(JSON.stringify({entries:[{s:'IPO',c:12,d:'2026-10-01'}]}))}]});
   if(mutation==='valid')assert.doesNotThrow(attach);else assert.throws(attach,/CONSUMER_INDEX_MAPPING|CONSUMER_INDEX_COUNT/);
  }finally{rmSync(root,{recursive:true,force:true});}
 }
});
