import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,copyFileSync,existsSync,unlinkSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {gzipSync} from 'node:zlib';
import {stageCanonicalPublication,attachCanonicalProjections,applyCanonicalPublication,verifyStagedCanonicalPublication,REQUIRED_PUBLICATION_QA,PRODUCTIZATION_QA_SCHEMA,CANONICAL_PUBLICATION_PATHS as paths} from '../../scripts/market/tiingo2-publication.mjs';
import {prepareHistoryPublication} from '../../scripts/market/tiingo2-history-preparation.mjs';
import {prepareRefreshedPublicationPackage,validateOriginalPublicationPackage,validateSourceOnlyHistoricalProvenance} from '../../scripts/market/tiingo2-refresh-publication-package.mjs';
const Company=createRequire(import.meta.url)('../../quant/engines/company-master.js'),sha=b=>createHash('sha256').update(b).digest('hex');
function fixture(fn){const root=mkdtempSync(join(tmpdir(),'publication-refresh-')),originalPreparedRoot=join(root,'.market-cache/original/tiingo2'),workDir=join(root,'.market-cache/refreshed-work'),preparedRoot=join(root,'.market-cache/refreshed/tiingo2');
 const save=(path,doc)=>{const file=join(root,path);mkdirSync(dirname(file),{recursive:true});writeFileSync(file,Buffer.isBuffer(doc)?doc:JSON.stringify(doc));};
 const git=(...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}),commit=()=>{git('add','quant/data','discover');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','canonical fixture');return git('rev-parse','HEAD').trim();};
 const keep={ticker:'KEEP',securityId:'ref_KEEP',exchange:'NASDAQ',active:true,assetType:'Stock',name:'Existing Software Inc'},inst=Company.toInstrument(keep,{today:'2026-10-02'});
 save(paths.raw,{securities:[keep],byExchange:{NASDAQ:1},bySector:{UNKNOWN:1}});save(paths.eligibility,{decisions:[{...keep,product_eligibility:'ELIGIBLE',instrument_type:'EQUITY_COMMON'}],counts:{universeMembers:1,productUniverse:1,ELIGIBLE:1,SEPARATE_CLASS:0,REVIEW:0,EXCLUDED:0}});save(paths.names,{rows:[{...keep,companyName:keep.name,status:'RESOLVED',inProductUniverse:true}]});save(paths.instruments+'/KE.json',{instruments:[inst]});save('discover/logos/index.json',{files:{},wide:[],dark:[]});
 git('init','-q');const originalSourceCommit=commit();
 const candidate={ticker:'ZNEW',securityId:'ref_ZNEW',instrument_type:'EQUITY_COMMON',active:true,companyName:'New Software Corporation',listing:{ticker:'ZNEW',name:'New Software Corporation',assetType:'Stock',exchange:'NASDAQ',currency:'USD',startDate:'2026-09-01',endDate:'2026-10-01'},evidence:{identity:{resolved:true},price:{historyValid:true,latestValid:true,latestDate:'2026-10-01',corporateActionValid:true}}};
 let stage=stageCanonicalPublication({root,output:join(originalPreparedRoot,'canonical-stage'),candidates:[candidate],preview:{ADDED:[{ticker:'ZNEW',securityId:'ref_ZNEW'}],REMOVED:[]},runId:'original',today:'2026-10-02'}),addition=stage.additions[0];
 const chartPath='quant/data/market/discover-series/ref_ZNEW.json',docs={'quant/data/universe/master-manifest.json':{totals:{published:2},shards:{index:[{shard:'KE',count:1},{shard:'ZN',count:1}]}},'quant/data/universe/search/manifest.json':{sym:[{shard:'ZN',count:1}],name:[{shard:'00',count:1}]},'quant/data/universe/search/sym/ZN.json':{entries:[{s:'ZNEW',i:addition.instrumentId}]},'quant/data/universe/search/name/00.json':{entries:[{s:'ZNEW',i:addition.instrumentId}]},'quant/data/universe/market-capability.json':{members:[{s:'ZNEW',m:'ref_ZNEW',i:addition.instrumentId,ph:true}]},'discover/data/meta.json':{universeSource:{source:'SECURITY_MASTER',file:paths.eligibility,sha256:stage.files.find(f=>f.path===paths.eligibility).stagedSha256}},[chartPath]:{ticker:'ZNEW',securityId:'ref_ZNEW',status:'CALCULATED',priceSeriesType:'SPLIT_ADJUSTED',currency:'USD',points:Array.from({length:30},(_,i)=>['2026-09-'+String(i+1).padStart(2,'0'),10])},'discover/logos/index.json':{files:{},wide:['PASW'],wideFiles:{PASW:'files/wide/PASW.png'},dark:[]}};
 const preparedFiles=Object.entries(docs).map(([path,doc])=>({path,bytes:Buffer.from(JSON.stringify(doc))}));preparedFiles.push({path:'quant/data/product/universe-list-v1.json.gz',bytes:gzipSync(JSON.stringify({entries:[{s:'ZNEW',c:10,d:'2026-10-01'}]}))},{path:'discover/logos/files/wide/PASW.png',bytes:Buffer.from('fixture quarantined new image')});
 const products=Object.fromEntries(['QUANT','DISCOVER','SCREENER','SUPERTRADER','SEC'].map(k=>[k,{state:'UNAVAILABLE',reasonCodes:['NO_VERIFIED_DATA'],artifactPaths:[]} ]));Object.assign(products,{SEARCH:{state:'PASS',artifactPaths:['quant/data/universe/search/sym/ZN.json']},WATCHLIST:{state:'PASS',artifactPaths:[paths.instruments+'/ZN.json']},CHARTS:{state:'PASS',artifactPaths:[chartPath]}});
 stage=attachCanonicalProjections({root,staged:stage,preparedFiles,productizationReadiness:[{...addition,products}]});
 const payload={ticker:'ZNEW',securityId:'ref_ZNEW',provider:'tiingo',bars:Array.from({length:30},(_,i)=>({securityId:'ref_ZNEW',date:'2026-09-'+String(i+1).padStart(2,'0'),close:10}))},market=join(root,'.market-cache/market-store');save('.market-cache/market-store/tiingo/daily/ref_ZNEW.json',payload);
 prepareHistoryPublication({marketStoreDir:market,outputRoot:originalPreparedRoot,additions:[addition],publicationManifestSha256:stage.manifestSha256});
 const proof={schemaVersion:PRODUCTIZATION_QA_SCHEMA,manifestSha256:stage.manifestSha256,productReadinessSha256:stage.productizationReadinessSha256,checks:Object.fromEntries(REQUIRED_PUBLICATION_QA.map(k=>[k,'PASS'])),historyPlanSha256:sha(readFileSync(join(originalPreparedRoot,'history-publication-plan.json'))),productionWrites:0};save('.market-cache/original/tiingo2/canonical-stage/qa-proof.json',proof);applyCanonicalPublication({root,staged:stage,qaProof:proof});commit();
 // Final review corrects an alias, adds a native public artifact and removes
 // only a new orphan. No provider history or original baseline asset changes.
 save('discover/logos/index.json',{files:{},wide:[],dark:[]});unlinkSync(join(root,'discover/logos/files/wide/PASW.png'));save('quant/data/product/pattern-match-v1/ZN.json.gz',gzipSync(JSON.stringify({securities:{ZNEW:{native:true}}})));const expectedSourceCommit=commit();
 const options={root,originalPreparedRoot,workDir,preparedRoot,expectedManifestSha256:stage.manifestSha256,originalSourceCommit,expectedSourceCommit,runId:'final-package'};
 try{return fn({options,root,save,git,stage,originalPreparedRoot,proof});}finally{rmSync(root,{recursive:true,force:true});}
}
test('refresh stages committed final bytes with original rollback and exact private history, and grants no publication QA',()=>fixture(({options,originalPreparedRoot,root})=>{
 const before=readFileSync(join(root,paths.raw)),originalHistory=readFileSync(join(originalPreparedRoot,'private-histories/tiingo/daily/ref_ZNEW.json'));const result=prepareRefreshedPublicationPackage(options);
 assert.equal(result.state,'STAGED_REQUIRES_FINAL_QA');assert.equal(result.productionPublishAllowed,false);assert.equal(result.productionWrites,0);assert.equal(result.providerCalls,0);assert.equal(result.privateHistoriesRebuilt,0);assert.deepEqual(result.omittedNewAssets,['discover/logos/files/wide/PASW.png']);assert.ok(readFileSync(join(root,paths.raw)).equals(before));assert.ok(readFileSync(join(options.preparedRoot,'private-histories/tiingo/daily/ref_ZNEW.json')).equals(originalHistory));
 assert.equal(existsSync(join(dirname(result.stage),'qa-proof.json')),false);assert.equal(existsSync(join(dirname(result.stage),'applied.json')),false);
 const manifest=JSON.parse(readFileSync(result.stage));assert.ok(manifest.files.some(f=>f.path==='quant/data/product/pattern-match-v1/ZN.json.gz'));assert.ok(!manifest.files.some(f=>f.path.endsWith('/PASW.png')));assert.equal(manifest.removals.length,0);assert.equal(manifest.additions.length,1);assert.notEqual(result.manifestSha256,options.expectedManifestSha256);
 assert.equal(JSON.parse(readFileSync(join(options.preparedRoot,'history-publication-plan.json'))).publicationManifestSha256,result.manifestSha256);assert.equal(verifyStagedCanonicalPublication({root:result.baselineRoot,staged:{manifestPath:result.stage}}).manifestSha256,result.manifestSha256);
}));
test('changed original manifest, rollback or private-history bytes fail before creating refresh outputs',()=>{
 for(const path of ['canonical-stage/manifest.json','canonical-stage/rollback/'+paths.raw,'private-histories/tiingo/daily/ref_ZNEW.json'])fixture(({options,originalPreparedRoot})=>{writeFileSync(join(originalPreparedRoot,path),'{}');assert.throws(()=>prepareRefreshedPublicationPackage(options),/ORIGINAL/);assert.equal(existsSync(options.workDir),false);assert.equal(existsSync(options.preparedRoot),false);});
});
test('wrong source HEAD, uncommitted public changes and linked private inputs cannot enter a refresh',()=>{
 fixture(({options})=>assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit:'a'.repeat(40)}),/SOURCE_BINDING/));
 fixture(({options,save})=>{save(paths.raw,{securities:[]});assert.throws(()=>prepareRefreshedPublicationPackage(options),/NOT_COMMITTED/);});
 fixture(({options,originalPreparedRoot,root})=>{const path=join(originalPreparedRoot,'history-publication-plan.json');unlinkSync(path);symlinkSync(join(root,'missing'),path);assert.throws(()=>validateOriginalPublicationPackage(options),/LINK_REJECTED/);});
});
test('an existing PASW baseline asset or final wide alias cannot be removed through orphan omission',()=>fixture(({options,root,save,git})=>{
 save('discover/logos/index.json',{files:{},wide:['PASW'],wideFiles:{PASW:'files/wide/PASW.png'}});git('add','discover/logos/index.json');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','incorrect alias');const head=git('rev-parse','HEAD').trim();
 assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit:head}),/UNPROVED_REMOVAL/);
}));
test('object wide flags, shared aliases and nested credits cannot refer to the omitted asset',()=>{
 for(const [path,doc]of [['discover/logos/index.json',{files:{},wide:{PASW:true}}],['discover/logos/index.json',{files:{OTHER:'files/wide/PASW.png'},wide:{}}],['discover/logos/index.json',{files:{},wide:{},wideFiles:{ALIAS:'files/wide/PASW.png'}}],['discover/logos/credits.json',{credits:{OTHER:{wide:{path:'/discover/logos/files/wide/PASW.png'}}}}]])fixture(({options,save,git})=>{
  save(path,doc);git('add',path);git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','unsafe asset reference');const head=git('rev-parse','HEAD').trim();assert.throws(()=>prepareRefreshedPublicationPackage({...options,expectedSourceCommit:head}),/UNPROVED_REMOVAL/);
 });
});
test('historical source-only exception verifies exact audit rows and original Git/raw snapshot bytes',()=>{
 const root=mkdtempSync(join(tmpdir(),'source-provenance-refresh-')),shadow=join(root,'shadow'),source=paths.raw,path='quant/data/market/security-master/reconciliation.json';const save=(base,p,d)=>{mkdirSync(dirname(join(base,p)),{recursive:true});writeFileSync(join(base,p),Buffer.isBuffer(d)?d:JSON.stringify(d));},git=(...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:'pipe'});
 try{const bytes=Buffer.from(JSON.stringify({securities:[{ticker:'KEEP',securityId:'ref_KEEP'}]}));save(root,source,bytes);git('init','-q');git('add','quant');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','audit source');const auditCommit=git('rev-parse','HEAD').trim(),digest=sha(bytes),snapshot='quant/data/market/security-master/baselines/universe-FULL_UNIVERSE.'+digest+'.json.gz';
  const before={run:{commit:auditCommit},headline:{BASELINE_COUNT:1},nonDestructive:{baselineFile:source,baselineCount:1,baselinePreserved:1,baselineRemoved:0}};save(root,path,before);const after={...before,nonDestructive:{...before.nonDestructive,baselineFile:snapshot,baselineSourceFile:source,baselineSha256:digest,baselineSourceCommit:auditCommit}};save(shadow,path,after);save(shadow,snapshot,gzipSync(bytes));
  const options={baselineRoot:root,shadowRoot:shadow,changed:[path,snapshot]};assert.equal(validateSourceOnlyHistoricalProvenance(options).length,2);
  save(shadow,path,{...after,headline:{BASELINE_COUNT:2}});assert.throws(()=>validateSourceOnlyHistoricalProvenance(options),/AUDIT_ROWS_CHANGED/);save(shadow,path,after);
  save(shadow,snapshot,gzipSync(Buffer.from(JSON.stringify({securities:[{ticker:'CHANGED',securityId:'ref_CHANGED'}]}))));assert.throws(()=>validateSourceOnlyHistoricalProvenance(options),/SNAPSHOT_NOT_ORIGINAL/);
  assert.throws(()=>validateSourceOnlyHistoricalProvenance({...options,changed:[path,snapshot,'quant/data/market/security-master/baselines/other.json.gz']}),/PROVENANCE_INVALID/);
 }finally{rmSync(root,{recursive:true,force:true});}
});
