import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';
import {fromBars,dailyOf} from '../../scripts/quant/lib/daily-prices.mjs';
import {fromDelistedTiingoBars,delistedBundleStamp,BUNDLE_VERSION} from '../../scripts/quant/build-survivorship-control.mjs';
const Q=createRequire(import.meta.url)('../engines/market-quality.js');
function bars({split=.025,dividend=3,move=-.176,cashAdjusted=true}={}){const previous=100,close=previous/split*(1+move),step=split*(cashAdjusted?1+dividend/close:1),bar=(date,close,adjustedClose,sf,d)=>({date,open:close,high:close,low:close,close,adjustedClose,splitFactor:sf,dividend:d,volume:100});return[bar('2024-08-19',previous,previous/step,1,0),bar('2024-08-20',close,close,split,dividend),bar('2024-08-21',close,close,1,0)];}
test('combined exports retain Main total-return and accepted349 corporate-action APIs',()=>{for(const api of ['totalReturnVerdict','classifyCorporateActions','assessSeries','validateAdjustmentConsistency'])assert.equal(typeof Q[api],'function');assert.equal(Q.TR_CONTRACT_VERSION,'total-return-contract-1.0.0');assert.deepEqual(Q.TR_DIVIDEND_BAND,[.6,1.4]);});
test('Tiingo split+dividend step does not contaminate shared total-return dividend evidence',()=>{const b=bars({split:2,dividend:2,move:-.176}),o={dividendConvention:'TIINGO_REINVESTMENT_CLOSE'},sem=Q.validateAdjustmentConsistency(b,{...o,claimedStatus:'TOTAL_RETURN'});assert.equal(Q.classifyCorporateActions(b,o).ok,true);assert.equal(Q.totalReturnVerdict(b,o).confirmed,true);const d=sem.observed.dividendEvidence[0];assert.ok(Math.abs(d.observedFactorStep/d.expectedFactorStep-1)<.001);assert.equal(sem.observed.splitEvidence.length,1);});
test('missing cash adjustment on simultaneous split remains a rejected total-return history',()=>{const b=bars({split:2,dividend:2,cashAdjusted:false}),o={dividendConvention:'TIINGO_REINVESTMENT_CLOSE'};assert.equal(Q.totalReturnVerdict(b,o).confirmed,false);assert.equal(Q.classifyCorporateActions(b,o).ok,false);});
test('accepted DNA reverse split preserves economic loss and passes Main shared verdict',()=>{const b=bars({dividend:0});assert.equal(Q.totalReturnVerdict(b,{dividendConvention:'TIINGO_REINVESTMENT_CLOSE'}).confirmed,true);assert.equal(Q.classifyCorporateActions(b).ok,true);assert.ok(Math.abs(b[1].adjustedClose/b[0].adjustedClose-1+.176)<1e-12);});
test('large Tiingo ex-close dividend accepted explicitly, prior-close remains generic default',()=>{const b=bars({split:1,dividend:50,move:-.5});assert.equal(Q.totalReturnVerdict(b,{dividendConvention:'TIINGO_REINVESTMENT_CLOSE'}).confirmed,true);assert.equal(Q.totalReturnVerdict(b).confirmed,false,'explicit Tiingo convention must not change generic callers');});
test('daily loader uses verified Tiingo provenance, preserves explicit caller override and generic defaults',()=>{
 const b=bars({split:1,dividend:50,move:-.5}),payload={ticker:'TEST',bars:b};
 for(const provenance of [{provider:'tiingo'},{provenance:{provider:'TIINGO'}},{provenance:{source:'tiingo'}}]){const p={...payload,...provenance};assert.equal(fromBars(p).totalReturn,true);assert.equal(fromBars(p,{dividendConvention:'PREVIOUS_CLOSE'}).totalReturn,false);assert.equal(fromBars(p,{asOf:'2025-01-01',maxStaleDays:2}).trVerdict.reason,'STALE');}
 assert.equal(fromBars(payload).totalReturn,false);assert.equal(fromBars({...payload,provider:'other'}).totalReturn,false);assert.equal(fromBars(payload,{dividendConvention:'TIINGO_REINVESTMENT_CLOSE'}).totalReturn,true);
});
test('known Tiingo history path supplies convention for legacy metadata and keeps caller options',t=>{
 const dir=mkdtempSync(join(tmpdir(),'tiingo-daily-convention-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const daily=join(dir,'tiingo','daily');mkdirSync(daily,{recursive:true});writeFileSync(join(daily,'ref_TEST.json'),JSON.stringify({ticker:'TEST',bars:bars({split:1,dividend:50,move:-.5})}));assert.equal(dailyOf('ref_TEST',dir).totalReturn,true);assert.equal(dailyOf('ref_TEST',dir,{dividendConvention:'PREVIOUS_CLOSE'}).totalReturn,false);
});
test('delisted Tiingo segment preserves issuer prices and economic cash return while generic/override semantics stay separate',()=>{
 const b=bars({split:1,dividend:50,move:-.5}),before=structuredClone(b),d=fromDelistedTiingoBars('OLD',b);assert.equal(d.totalReturn,true);assert.deepEqual([...d.tr],[50,50,50]);assert.equal(fromBars({ticker:'OLD',bars:b}).totalReturn,false);assert.equal(fromDelistedTiingoBars('OLD',b,{dividendConvention:'PREVIOUS_CLOSE'}).totalReturn,false);assert.deepEqual(b,before);assert.equal(fromDelistedTiingoBars('OLD',bars({split:2,dividend:2,cashAdjusted:false})).totalReturn,false,'a share action cannot replace missing cash adjustment');
});
test('same listing manifest invalidates prior derived weekly cache while retaining deterministic source binding',()=>{
 const manifest={updatedAt:'2026-10-01T00:00:00.000Z',tableHash:'a'.repeat(64)},before=structuredClone(manifest),old={bundle:'delisted-weekly-bundle-1.0.0',contract:Q.TR_CONTRACT_VERSION,manifestUpdatedAt:manifest.updatedAt,tableHash:manifest.tableHash},stamp=delistedBundleStamp(manifest);assert.equal(BUNDLE_VERSION,'delisted-weekly-bundle-1.1.0');assert.notEqual(JSON.stringify(stamp),JSON.stringify(old),'same source cannot reuse old dividend semantics');assert.deepEqual(stamp,{...old,bundle:BUNDLE_VERSION});assert.deepEqual(delistedBundleStamp(manifest),stamp);assert.deepEqual(manifest,before);
});
test('native Tiingo repair preserves large ex-close dividend raw bars through every contract boundary',async t=>{
 const {createServer}=await import('node:http'),{execFile}=await import('node:child_process'),root=fileURLToPath(new URL('../../',import.meta.url)),days=[];
 for(let d=new Date('2024-01-02T00:00:00Z');days.length<600;d.setUTCDate(d.getUTCDate()+1))if(d.getUTCDay()%6)days.push(d.toISOString().slice(0,10));
 const raw=days.map((date,i)=>({securityId:'ref_AAPL',date,open:i<300?100:50,high:i<300?100:50,low:i<300?100:50,close:i<300?100:50,volume:1000+i,adjustedClose:i<300?100:50,dividend:i===300?50:0,splitFactor:1}));
 const rows=raw.map(b=>({date:b.date+'T00:00:00.000Z',open:b.open,high:b.high,low:b.low,close:b.close,volume:b.volume,adjOpen:50,adjHigh:50,adjLow:50,adjClose:50,adjVolume:b.volume,divCash:b.dividend,splitFactor:1}));let hits=0;
 const server=createServer((req,res)=>{if(!/^\/tiingo\/daily\/AAPL\/prices\?/.test(req.url)){res.writeHead(404).end('{}');return;}hits++;res.writeHead(200,{'Content-Type':'application/json',Connection:'close'}).end(JSON.stringify(rows));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});
 const dir=mkdtempSync(join(tmpdir(),'tiingo-large-dividend-repair-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const work=join(dir,'work'),daily=join(work,'tiingo','daily'),report=join(dir,'report.json');mkdirSync(daily,{recursive:true});writeFileSync(join(daily,'ref_AAPL.json'),JSON.stringify({ticker:'AAPL',securityId:'ref_AAPL',provider:'tiingo',adjustmentStatus:'TOTAL_RETURN',bars:raw}));
 await new Promise((resolve,reject)=>execFile(process.execPath,[join(root,'scripts/market/repair-total-return-history.mjs'),'--work-dir',work,'--report',report,'--max','5'],{timeout:120000,env:{PATH:process.env.PATH,TIINGO_API_KEY:'test',TIINGO_BASE_URL:`http://127.0.0.1:${server.address().port}`}},e=>e?reject(e):resolve()));
 const result=JSON.parse(readFileSync(report)),after=JSON.parse(readFileSync(join(daily,'ref_AAPL.json')));assert.equal(hits,1);assert.equal(result.repairedCount,1,JSON.stringify(result));assert.equal(result.after.TOTAL_RETURN_CONFIRMED,1);assert.deepEqual(after.bars.map(({adjustedClose,...b})=>b),raw.map(({adjustedClose,...b})=>b));assert.equal(fromBars(after).totalReturn,true);assert.equal(Q.totalReturnVerdict(after.bars).confirmed,false,'generic prior-close verdict stays unchanged');assert.equal(after.totalReturnRepair.mode,'ADJUSTED_ONLY');
});
