(function(){
'use strict';
const S=QuantShell,el=S.el,api=VUProductServices.create({loadJSON:S.loadJSON,displayPolicy:VUDisplayPolicy,queryEngine:VUQuery});
const params=new URLSearchParams(location.search),view=params.get('view')||'home';
const href=(v,t)=>'/vu2/?view='+v+(t?'&ticker='+encodeURIComponent(t):'');
const link=(label,url,cls)=>el('a',{text:label,href:url,class:cls});
const n=(m,d=1)=>m&&Number.isFinite(m.value)?m.value.toLocaleString('de-DE',{maximumFractionDigits:d,minimumFractionDigits:d})+(m.unit==='percent'?' %':m.unit==='USD'?' $':''):'Nicht verfügbar';
const nav=[['home','Home'],['markets','Markets'],['discover','Discover'],['research','Research'],['strategies','Strategies'],['portfolio','Portfolio']];
const groups=[
 ['Aktien & Analyse','Vom Unternehmen bis zur Kursstruktur.',[
 ['Aktien',href('stocks')],['Charts','/quant/stock/?ticker=NVDA'],['Fundamentals & Historie','/quant/data-inspector/'],['Technical Intelligence','/quant/technical/?symbol=NVDA'],['Elliott Wave','/quant/technical/?symbol=NVDA&layer=ELLIOTT'],['Quant','/quant/'],['Vergleichen',href('compare')]]],
 ['Märkte & Ideen','Zusammenhänge verstehen und Titel finden.',[
 ['Screener',href('screener')],['Professioneller Screener','/quant/screener/'],['Rankings','/quant/ranking/'],['ETF Research & Vergleich','/etf/'],['Macro Intelligence','/macro/'],['Hedge Funds & Ownership','/hedgefonds/'],['Analyst Ratings','/analysten/']]],
 ['Research & Wissen','Aktuelles einordnen. Tiefer verstehen.',[
 ['News','/news/'],['Morning Briefing','/morning/'],['Weekly Magazine','/magazin/'],['Stock Reports','/reports/xpeng/'],['Academy','/academy/'],['Investment Guide','/guide/'],['Strategies',href('strategies')],['Signals',href('signals')],['Watchlist','/quant/watchlist/'],['Ask Atlas','/quant/ai/']]]
];
const app=document.getElementById('app');
const header=el('header',{class:'top'},[link('',href('home'),'brand'),el('nav',{class:'nav','aria-label':'Hauptnavigation'},nav.map(([id,label])=>link(label,href(id),id===view?'active':''))),el('div',{class:'utility'},[link('Watchlist','/quant/watchlist/'),link('Signals',href('signals')),el('button',{text:'Suche',onclick:()=>openSearch()})])]);
header.querySelector('.brand').append(el('img',{src:'/assets/vision-universe-logo.png',alt:'Vision Universe®'}));
const main=el('main',{id:'content'});app.append(header,main,el('nav',{class:'mobile-nav','aria-label':'Mobile Navigation'},nav.filter(([id])=>id!=='strategies').map(([id,label])=>link(label,href(id),id===view?'active':''))));
const dialog=el('dialog',{'aria-label':'Unternehmen und Workspaces suchen'});app.append(dialog);
let universe;
function heading(title,description){return el('div',{class:'intro'},[el('div',{},[el('span',{class:'eyebrow',text:'Vision Universe® · Preview'}),el('h1',{text:title}),description?el('p',{class:'muted',text:description}):null])]);}
function notice(title,text){return el('div',{class:'notice'},[el('h3',{text:title}),el('p',{class:'muted',text})]);}
function stockRows(stocks,metricKey='momentum6m',metricLabel='6 Monate'){return el('div',{},[el('div',{class:'row eyebrow'},[el('span',{text:'Unternehmen'}),el('span',{class:'number',text:'Schlusskurs'}),el('span',{class:'number',text:metricLabel})]),...stocks.map(s=>el('a',{class:'row',href:href('stock',s.ticker)},[el('div',{},[el('strong',{text:s.ticker}),el('span',{class:'muted',text:s.name})]),el('div',{class:'number',text:n(s.price,2)}),el('div',{class:'number '+(s[metricKey]?.value>=0?'positive':'negative'),text:n(s[metricKey])})]))]);}
function evidence(s){return el('div',{class:'evidence'},[['Umsatzwachstum',s.revenueGrowth],['Operative Marge',s.operatingMargin],['Kursentwicklung · 6M',s.momentum6m]].map(([label,m])=>el('div',{},[el('span',{class:'muted',text:label}),el('strong',{text:n(m)})])));}
function actions(items){return el('div',{class:'actions'},items.map((a,i)=>link(a.label,a.href,'button'+(i?' secondary':''))));}
function openSearch(){S.clear(dialog);const input=el('input',{class:'search',placeholder:'Unternehmen, Ticker oder Workspace','aria-label':'Suche'});const results=el('div',{class:'search-results links'});
 function update(){const q=input.value.trim().toLowerCase();S.clear(results);const matches=[...(universe?.stocks||[]).map(s=>({label:s.ticker+' · '+s.name,href:href('stock',s.ticker)})),...groups.flatMap(g=>g[2].map(([label,href])=>({label,href})))].filter(x=>x.label.toLowerCase().includes(q)).slice(0,9);results.append(...matches.map(x=>link(x.label,x.href)));if(!matches.length)results.append(el('p',{text:'Keine Treffer im verfügbaren Analysebereich.'}));}
 input.addEventListener('input',update);dialog.append(el('h2',{text:'Was möchtest du untersuchen?'}),input,results,el('button',{class:'button secondary',text:'Schließen',onclick:()=>dialog.close()}));update();dialog.showModal();input.focus();}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();openSearch();}});
async function stockPage(ticker){const s=await api.getStockIntelligence(ticker);main.append(heading(s.name||'Aktienanalyse',s.ticker||''));if(s.state!=='AVAILABLE'){main.append(notice('Daten derzeit nicht verfügbar','Für diesen Titel liegen in dieser Ansicht keine freigegebenen Daten vor.'));return;}
 const left=el('section',{class:'focus'},[el('span',{class:'pill',text:s.above200.value>0&&s.above50.value>0?'Über wichtigen Trendbereichen':'Kursstruktur prüfen'}),el('div',{class:'quote',text:n(s.price,2)}),el('p',{class:'muted',text:'Letzter verfügbarer Schlusskurs · '+(s.asOf||'Datum nicht verfügbar')})]);
 const chart=el('div'),ranges=el('div',{class:'ranges','aria-label':'Chart-Zeitraum'});
 function draw(id){S.clear(chart);const data=VUChartRanges.selectRange(id,{eod:s.chart.bars,adjustmentStatus:s.chart.adjustmentStatus});ranges.querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',b.dataset.range===id);b.setAttribute('aria-pressed',b.dataset.range===id?'true':'false');});if(!data.ok){chart.append(notice('Dieser Zeitraum ist nicht verfügbar','Tagesverläufe benötigen freigegebene Intraday-Daten. Wähle einen längeren Zeitraum.'));return;}
 chart.append(QuantCharts.lineChart({title:s.ticker+' · historische Schlusskurse',width:Math.min(900,window.innerWidth-40),height:290,dates:data.bars.map(b=>b.date),series:[{values:data.bars.map(b=>b.close)}],yFormat:v=>v.toFixed(0)+' $'}));}
 VUChartRanges.RANGES.forEach(r=>ranges.append(el('button',{text:r.label,dataset:{range:r.id},onclick:()=>draw(r.id)})));left.append(chart,ranges,el('p',{class:'muted',text:'Unbereinigte Schlusskurse · USD. Splits können historische Kurssprünge verursachen.'}));draw('1Y');
 const side=el('aside',{},[el('h2',{text:'Was dahintersteht'}),el('p',{text:s.above200.value>0?'Der Kurs liegt über seinem 200-Tage-Durchschnitt. Das beschreibt die bisherige Entwicklung, keine Prognose.':'Die langfristige Kursstruktur verdient einen genaueren Blick.'}),evidence(s),el('details',{},[el('summary',{text:'Evidenz & Methodik'}),el('p',{class:'muted',text:'Abstand zum 200-Tage-Durchschnitt: '+n(s.above200)+'. Fundamentaldaten bis '+s.fundamentalsAsOf+', verfügbar seit '+s.availableAt+'. Quelle: SEC EDGAR; Kurskennzahlen: Tiingo EOD / bestehende Quant-Methodik.'}),link('Daten und Berechnung untersuchen','/quant/data-inspector/','button secondary')])]);
 main.append(el('div',{class:'layout'},[left,side]),actions(s.workspaces));
 const technical=await api.getTechnicalIntelligence(ticker);
 const section=el('section',{class:'section'},[el('span',{class:'eyebrow',text:'Kursstruktur verstehen'}),el('h2',{text:'Technical Intelligence'})]);
 if(technical.state==='AVAILABLE'){
  section.append(el('div',{class:'technical-summary'},[['Trend',technical.trend],['Momentum',technical.momentum],['Volatilität',technical.volatility]].map(([label,state])=>el('div',{},[el('span',{class:'muted',text:label}),el('h3',{text:state.label})]))),el('p',{class:'muted',text:'Analyse bis '+technical.asOf+' · '+technical.methodology}),el('p',{text:'Elliott Wave: '+technical.elliott.label+'. Die Szenarien sind keine Wahrscheinlichkeitsprognose.'}),actions([{label:'Vollständige Technical-Analyse',href:technical.workspace},{label:'Elliott: Szenarien & Invalidation',href:technical.elliottWorkspace}]));
 }else section.append(notice('Technische Analyse derzeit nicht verfügbar','Der vollständige Workspace bleibt über die Analysezugänge erreichbar.'));
 main.append(section);
}
async function marketsPage(){
 const market=await api.getMarketIntelligence();
 main.append(heading('Den Markt einordnen','Kursstrukturen untersuchen. Den Kontext verstehen. Die Evidenz prüfen.'),notice('Gesamtmarkt-Einordnung noch nicht verfügbar','Die freigegebene Vorschau umfasst fünf Unternehmen. Ihre Entwicklung beschreibt nicht die Marktbreite oder das Marktregime.'));
 const rows=el('section',{class:'section'},[el('h2',{text:'Trendradar · verfügbarer Analysebereich'}),el('p',{class:'muted',text:'Ein Kurs über seinen Durchschnittslinien beschreibt seine bisherige Position. Er ist kein Kaufsignal.'})]);
 for(const {stock,trend} of market.observations){rows.append(el('article',{class:'market-observation'},[el('div',{},[link(stock.ticker,href('stock',stock.ticker),'stock-link'),el('p',{class:'muted',text:stock.name})]),el('div',{},[el('h3',{text:trend.label}),el('p',{class:'muted',text:'Kursstand: '+stock.asOf}),el('details',{},[el('summary',{text:'Warum?'}),el('p',{text:trend.explanation||'Für die Einordnung fehlen belastbare Kennzahlen.'}),...(trend.evidence||[]).map(e=>el('p',{text:e.label+': '+n(e.metric)})),link('Vollständige Analyse öffnen','/quant/technical/?symbol='+stock.ticker)])]),el('div',{class:'number'},[el('span',{class:'muted',text:'6 Monate'}),el('strong',{text:n(stock.momentum6m)})])]));}
 if(!market.observations.length)rows.append(notice('Titel derzeit nicht verfügbar','Die zugrunde liegenden Daten konnten nicht geladen werden.'));
 main.append(rows,el('section',{class:'section'},[el('h2',{text:'Das größere Bild'}),actions([{label:'Macro Intelligence',href:'/macro/'},{label:'ETF Research & Vergleich',href:'/etf/'},{label:'Aktuelle Nachrichten',href:'/news/'}])]));
}
async function discoverPage(){
 main.append(heading('Eine Idee ist der Anfang','Entdecke Unternehmen anhand sichtbarer Kriterien. Öffne jede Auswahl im Screener und entwickle sie weiter.'));
 const data=await api.getDiscover();
 main.append(el('p',{class:'scope-note',text:'Aktuell verfügbarer Analysebereich: fünf Unternehmen. Diese Auswahlen sind keine Rangliste des Gesamtmarkts.'}));
 for(const collection of data.collections){
  const result=collection.result;
  const title=el('div',{},[el('span',{class:'eyebrow',text:'Entdecken · '+(result.state==='AVAILABLE'?result.stocks.length+' Treffer':'Daten fehlen')}),el('h2',{text:collection.title}),el('p',{class:'muted',text:collection.explanation}),el('p',{class:'recipe-rule',text:collection.rule}),link('Regeln im Screener bearbeiten',href('screener')+'&recipe='+encodeURIComponent(collection.id),'button secondary')]);
  const evidence=result.state==='AVAILABLE'?(result.stocks.length?stockRows(result.stocks,collection.field==='priceTo200dma'?'above200':collection.field,collection.field==='revenueGrowth'?'Umsatzwachstum':collection.field==='priceTo200dma'?'Abstand 200T':'6 Monate'):notice('Aktuell keine Treffer','Das Kriterium trifft auf kein Unternehmen im verfügbaren Analysebereich zu. Du kannst es im Screener verändern.')):notice('Auswahl derzeit nicht verfügbar','Die zugrunde liegenden Daten konnten nicht geladen werden.');
  main.append(el('section',{class:'collection'},[title,el('div',{},[evidence])]));
 }
}
async function screenPage(){main.append(heading('Dein Screener','Kriterien verändern. Ergebnisse verstehen. Selbst weiterforschen.'));
 const field=el('select',{'aria-label':'Kennzahl'},[['momentum6m','Kursentwicklung · 6 Monate'],['revenueGrowth','Umsatzwachstum'],['priceTo200dma','Abstand zum 200-Tage-Durchschnitt']].map(([value,text])=>el('option',{value,text}))),threshold=el('input',{type:'number',value:params.get('threshold')||'0','aria-label':'Mindestwert in Prozent',step:'1'}),out=el('div'),method=el('pre',{style:'white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px'});
 const recipe=api.getRecipes().find(r=>r.id===params.get('recipe'));
 if(recipe){field.value=recipe.field;threshold.value=recipe.threshold;main.append(el('p',{class:'scope-note',text:'Aus Discover: '+recipe.title+'. Alle Kriterien bleiben veränderbar.'}));}
 if(params.get('field')&&Array.from(field.options).some(o=>o.value===params.get('field')))field.value=params.get('field');
 const update=async()=>{try{if(threshold.value.trim()===''||!Number.isFinite(Number(threshold.value)))throw Error('invalid');const query=VUQuery.createQuery({filters:[{field:field.value,operator:'gte',value:Number(threshold.value),scale:'raw'}],sort:[{field:field.value,direction:'desc'}],limit:50});const result=await api.screen(query);S.clear(out);if(result.state!=='AVAILABLE'){out.append(notice('Ergebnisse derzeit nicht verfügbar','Die Daten konnten nicht geladen werden. Deine Kriterien bleiben erhalten.'));method.textContent=JSON.stringify(query,null,2);return;}out.append(el('p',{class:'muted',text:result.stocks.length+' Treffer in '+result.eligible+' verfügbaren Unternehmen · kein Gesamtmarkt-Ranking'}),stockRows(result.stocks,field.value==='priceTo200dma'?'above200':field.value,field.value==='revenueGrowth'?'Umsatzwachstum':field.value==='priceTo200dma'?'Abstand 200T':'6 Monate'));method.textContent=JSON.stringify(result.query,null,2);}catch{S.mount(out,notice('Kriterium prüfen','Bitte gib einen gültigen Zahlenwert ein.'));}};
 main.append(el('div',{class:'filter'},[el('label',{text:'Zeige Unternehmen mit'}),field,el('label',{text:'mindestens'}),threshold,el('span',{text:'%'}),el('button',{class:'button',text:'Anwenden',onclick:update})]),out,el('details',{},[el('summary',{text:'Reproduzierbare Regel ansehen'}),el('p',{text:'Diese Abfrage verwendet dieselbe Regel-Engine wie der professionelle Screener. Der Datenumfang dieser Vorschau bleibt separat begrenzt.'}),method]),actions([{label:'Professionellen Screener öffnen',href:'/quant/screener/'}]));await update();
}
async function render(){universe=await api.getUniverse();
 if(view==='stock')await stockPage(params.get('ticker')||'NVDA');
 else if(view==='markets')await marketsPage();
 else if(view==='discover')await discoverPage();
 else if(view==='screener')await screenPage();
 else if(view==='research'){main.append(heading('Research ohne Umwege','Deine Workspaces. Von der ersten Frage bis zur vollständigen Analyse.'),el('div',{class:'catalog'},groups.map(([title,desc,links])=>el('section',{},[el('h2',{text:title}),el('p',{text:desc}),el('div',{class:'links'},links.map(([label,url])=>link(label,url)))]))));}
 else if(view==='compare'){main.append(heading('Unternehmen vergleichen','Dieselben Kennzahlen. Derselbe verfügbare Datenumfang.'));const one=el('select',{'aria-label':'Erstes Unternehmen'}),two=el('select',{'aria-label':'Zweites Unternehmen'});for(const s of universe.stocks){one.append(el('option',{value:s.ticker,text:s.ticker}));two.append(el('option',{value:s.ticker,text:s.ticker}));}one.value=params.get('ticker')||'NVDA';two.value='MSFT';const target=el('div',{class:'table-wrap'});function compare(){const a=universe.stocks.find(s=>s.ticker===one.value),b=universe.stocks.find(s=>s.ticker===two.value);if(!a||!b)return;S.mount(target,el('table',{},[el('thead',{},[el('tr',{},['Kennzahl',a.ticker,b.ticker].map(text=>el('th',{text})))]),el('tbody',{},[['Kursentwicklung 6M','momentum6m'],['Umsatzwachstum','revenueGrowth'],['Operative Marge','operatingMargin'],['FCF-Marge','fcfMargin'],['ROIC','roic'],['Größter Rückgang · 1J','drawdown']].map(([label,key])=>el('tr',{},[el('td',{text:label}),el('td',{text:n(a[key])}),el('td',{text:n(b[key])})])))]));}one.onchange=two.onchange=compare;main.append(el('div',{class:'filter'},[one,el('span',{text:'mit'}),two]),target);compare();}
 else if(view==='strategies'){main.append(heading('Eine Idee. Klare Regeln.','Formuliere eine Strategie und untersuche ihre historische Entwicklung.'),notice('Historische Ergebnisse brauchen Kontext','Prüfe Datenverfügbarkeit, Kosten, Ausführungszeitpunkt und das historische Universum. Ein Fundamental-PIT-Test allein macht noch keinen professionellen Backtest.'),actions([{label:'Strategy Lab öffnen',href:'/quant/strategies/'},{label:'Eigene Strategie bauen',href:'/quant/strategies/builder/'},{label:'Backtests untersuchen',href:'/quant/backtests/'}]));}
 else if(view==='portfolio'){main.append(heading('Deine Perspektive auf das Portfolio','Beobachten, vergleichen und Risiken untersuchen.'),actions([{label:'Watchlist öffnen',href:'/quant/watchlist/'},{label:'Modellportfolios & Strategien',href:'/quant/strategies/'}]),notice('Keine erfundenen Portfoliozahlen','Eine echte Portfolio-Auswertung benötigt deine Positionen und deren Datenstand. Die bestehenden Werkzeuge bleiben direkt erreichbar.'));}
 else if(view==='signals'){main.append(heading('Was hat sich verändert?','Ein Signal beschreibt eine belegte Zustandsänderung.'),notice('Noch keine bestätigten Ereignisse in dieser Ansicht','Ohne vergleichbare vorherige und aktuelle Zustände erzeugen wir kein Signal. Ein hoher Kennzahlenwert allein ist keine neue Entwicklung.'),actions([{label:'Bestehenden Radar öffnen',href:'/quant/radar/'},{label:'Watchlist',href:'/quant/watchlist/'}]));}
 else if(view==='stocks'){main.append(heading('Unternehmen untersuchen','Fünf Unternehmen im aktuell verfügbaren Analysebereich.'),stockRows(universe.stocks));}
 else {main.append(heading(view==='markets'?'Märkte verstehen':'Das Wichtigste im Blick','Daten einordnen. Zusammenhänge erkennen. Weiterforschen.'));const focus=universe.stocks.find(s=>s.ticker==='NVDA');const left=el('section',{},[notice('Gesamtmarkt noch nicht eingeordnet','Die aktuelle Ansicht deckt '+universe.stocks.length+' Unternehmen ab. Daraus lässt sich keine belastbare Marktbreite ableiten.'),el('div',{class:'section'},[el('h2',{text:'Unternehmen im Blick'}),stockRows(universe.stocks)])]);const right=el('aside',{},[el('span',{class:'eyebrow',text:'Analyse vertiefen'}),el('h2',{text:focus?'NVIDIA':'Research'}),el('p',{class:'muted',text:'Wie entwickeln sich Geschäft und Kurs? Die Aktienanalyse verbindet Kennzahlen mit ihren Quellen.'}),focus?evidence(focus):null,link('Aktie untersuchen',href('stock','NVDA'),'button'),el('div',{class:'section links'},[link('Ideen entdecken',href('discover')),link('Makro-Zusammenhänge','/macro/'),link('Morning Briefing','/morning/'),link('News im Kontext','/news/'),link('Ask Atlas','/quant/ai/')])]);main.append(el('div',{class:'layout'},[left,right]));}
 main.append(el('footer',{class:'footer',text:'Vision Universe® · Entwicklungsvorschau · Bestehender freigegebener Analysebereich. Kurse: letzter verfügbarer EOD-Stand, nicht realtime. '+(universe.stocks[0]?.asOf?'Kursstand: '+universe.stocks[0].asOf+'. ':'')+'Keine Anlageempfehlung.'}));
}
render().catch(()=>main.append(notice('Ansicht derzeit nicht verfügbar','Die Daten konnten nicht geladen werden. Bitte versuche es erneut.')));
})();
