(function(){
'use strict';
const S=QuantShell,el=S.el,api=VUProductServices.create({loadJSON:S.loadJSON,displayPolicy:VUDisplayPolicy,queryEngine:VUQuery});
const params=new URLSearchParams(location.search),view=params.get('view')||'home';
const href=(v,t)=>'/vu2/?view='+v+(t?'&ticker='+encodeURIComponent(t):'');
const link=(label,url,cls)=>el('a',{text:label,href:url,class:cls});
const n=(m,d=1)=>m&&Number.isFinite(m.value)?m.value.toLocaleString('de-DE',{maximumFractionDigits:d,minimumFractionDigits:d})+(m.unit==='percent'?' %':m.unit==='USD'?' $':''):'Nicht verfügbar';
const formatFactor=m=>!Number.isFinite(m.value)?'Nicht verfügbar':m.value.toLocaleString('de-DE',{maximumFractionDigits:2})+(m.metricId==='marginExpansion'?' Prozentpunkte':m.unit==='pct'?' %':m.unit==='x'?' ×':'');
const nav=[['home','Home'],['markets','Markets'],['discover','Discover'],['research','Research'],['strategies','Strategies'],['portfolio','Portfolio']];
const groups=[
 ['Aktien & Analyse','Vom Unternehmen bis zur Kursstruktur.',[
 ['Aktien',href('stocks')],['Charts','/quant/stock/?ticker=NVDA'],['Fundamentals & Historie',href('fundamentals','NVDA')],['SEC Dateninspektor','/quant/data-inspector/'],['Technical Intelligence',href('technical','NVDA')],['Elliott Wave',href('elliott','NVDA')],['Quant',href('quant','NVDA')],['Vergleichen',href('compare')]]],
 ['Märkte & Ideen','Zusammenhänge verstehen und Titel finden.',[
 ['Screener',href('screener')],['Professioneller Screener','/quant/screener/'],['Rankings','/quant/ranking/'],['ETF Research & Vergleich','/etf/'],['Macro Intelligence','/macro/'],['Hedge Funds & Ownership','/hedgefonds/'],['Analyst Ratings','/analysten/']]],
 ['Research & Wissen','Aktuelles einordnen. Tiefer verstehen.',[
 ['News','/news/'],['Morning Briefing','/morning/'],['Weekly Magazine','/magazin/'],['Stock Reports','/reports/xpeng/'],['Academy','/academy/'],['Investment Guide','/guide/'],['Strategies',href('strategies')],['Signals',href('signals')],['Watchlist',href('watchlist')],['Ask Atlas',href('atlas')]]]
];
const app=document.getElementById('app');
const header=el('header',{class:'top'},[link('',href('home'),'brand'),el('nav',{class:'nav','aria-label':'Hauptnavigation'},nav.map(([id,label])=>link(label,href(id),id===view?'active':''))),el('div',{class:'utility'},[link('Watchlist',href('watchlist')),link('Signals',href('signals')),el('button',{text:'Suche',onclick:()=>openSearch()})])]);
header.querySelector('.brand').append(el('img',{src:'/assets/vision-universe-logo.png',alt:'Vision Universe®'}));
const main=el('main',{id:'content'});app.append(header,main,el('nav',{class:'mobile-nav','aria-label':'Mobile Navigation'},nav.filter(([id])=>id!=='strategies').map(([id,label])=>link(label,href(id),id===view?'active':''))));
const dialog=el('dialog',{'aria-label':'Unternehmen und Workspaces suchen'});app.append(dialog);
let universe;
function heading(title,description){return el('div',{class:'intro'},[el('div',{},[el('span',{class:'eyebrow',text:'Vision Universe® · Preview'}),el('h1',{text:title}),description?el('p',{class:'muted',text:description}):null])]);}
function notice(title,text){return el('div',{class:'notice'},[el('h3',{text:title}),el('p',{class:'muted',text})]);}
function stockRows(stocks,metricKey='momentum6m',metricLabel='6 Monate',showAsOf=false){return el('div',{},[el('div',{class:'row eyebrow'},[el('span',{text:'Unternehmen'}),el('span',{class:'number',text:'Schlusskurs'}),el('span',{class:'number',text:metricLabel})]),...stocks.map(s=>el('a',{class:'row',href:href('stock',s.ticker)},[el('div',{},[el('strong',{text:s.ticker}),el('span',{class:'muted',text:s.name}),showAsOf?el('span',{class:'muted row-asof'},[el('span',{text:'Kursstand '}),el('time',{datetime:s.asOf,text:s.asOf||'nicht verfügbar'})]):null]),el('div',{class:'number',text:n(s.price,2)}),el('div',{class:'number '+(Number.isFinite(s[metricKey]?.value)&&s[metricKey].unit==='percent'?(s[metricKey].value>=0?'positive':'negative'):''),text:n(s[metricKey])})]))]);}
function evidence(s){return el('div',{class:'evidence'},[['Umsatzwachstum',s.revenueGrowth],['Operative Marge',s.operatingMargin],['Kursentwicklung · 6M',s.momentum6m]].map(([label,m])=>el('div',{},[el('span',{class:'muted',text:label}),el('strong',{text:n(m)})])));}
function actions(items){return el('div',{class:'actions'},items.map((a,i)=>link(a.label,a.href,'button'+(i?' secondary':''))));}
function openSearch(){S.clear(dialog);const input=el('input',{class:'search',placeholder:'Unternehmen, Ticker oder Workspace','aria-label':'Suche'});const results=el('div',{class:'search-results links'});
 function update(){const q=input.value.trim().toLowerCase();S.clear(results);const matches=[...(universe?.stocks||[]).map(s=>({label:s.ticker+' · '+s.name,href:href('stock',s.ticker)})),...groups.flatMap(g=>g[2].map(([label,href])=>({label,href})))].filter(x=>x.label.toLowerCase().includes(q)).slice(0,9);results.append(...matches.map(x=>link(x.label,x.href)));if(!matches.length)results.append(el('p',{text:'Keine Treffer im verfügbaren Analysebereich.'}));}
 input.addEventListener('input',update);dialog.append(el('h2',{text:'Was möchtest du untersuchen?'}),input,results,el('button',{class:'button secondary',text:'Schließen',onclick:()=>dialog.close()}));update();dialog.showModal();input.focus();}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();openSearch();}});
async function stockPage(ticker){const s=await api.getStockIntelligence(ticker);main.append(heading(s.name||'Aktienanalyse',s.ticker||''));if(s.state!=='AVAILABLE'){main.append(notice('Daten derzeit nicht verfügbar','Für diesen Titel liegen in dieser Ansicht keine freigegebenen Daten vor.'));return;}
 const left=el('section',{class:'focus'},[el('span',{class:'pill',text:s.above200.value>0&&s.above50.value>0?'Über wichtigen Trendbereichen':'Kursstruktur prüfen'}),el('div',{class:'quote',text:n(s.price,2)}),el('p',{class:'muted',text:'Letzter verfügbarer Schlusskurs · '+(s.asOf||'Datum nicht verfügbar')})]);
 const chart=el('div'),ranges=el('div',{class:'ranges','aria-label':'Chart-Zeitraum'});
 function draw(id){S.clear(chart);const data=VUChartRanges.selectRange(id,{eod:s.chart.bars,adjustmentStatus:s.chart.adjustmentStatus});ranges.querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',b.dataset.range===id);b.setAttribute('aria-pressed',b.dataset.range===id?'true':'false');});if(!data.ok){chart.append(notice('Dieser Zeitraum ist nicht verfügbar','Tagesverläufe benötigen freigegebene Intraday-Daten. Wähle einen längeren Zeitraum.'));return;}
 chart.append(QuantCharts.lineChart({title:s.ticker+' · historische Schlusskurse',width:Math.min(900,window.innerWidth-40),height:290,dates:data.bars.map(b=>b.date),series:[{values:data.bars.map(b=>b.close)}],yFormat:v=>v.toFixed(0)+' $'}));}
 VUChartRanges.RANGES.forEach(r=>ranges.append(el('button',{text:r.label,dataset:{range:r.id},onclick:()=>draw(r.id)})));left.append(chart,ranges,el('p',{class:'muted',text:'Unbereinigte Schlusskurse · USD. Splits können historische Kurssprünge verursachen.'}));draw('1Y');
 const side=el('aside',{},[el('h2',{text:'Was dahintersteht'}),el('p',{text:s.above200.value>0?'Der Kurs liegt über seinem 200-Tage-Durchschnitt. Das beschreibt die bisherige Entwicklung, keine Prognose.':'Die langfristige Kursstruktur verdient einen genaueren Blick.'}),evidence(s),el('details',{},[el('summary',{text:'Evidenz & Methodik'}),el('p',{class:'muted',text:'Abstand zum 200-Tage-Durchschnitt: '+n(s.above200)+'. Fundamentaldaten bis '+s.fundamentalsAsOf+', verfügbar seit '+s.availableAt+'. Quelle: SEC EDGAR; Kurskennzahlen: Tiingo EOD / bestehende Quant-Methodik.'}),link('Daten und Berechnung untersuchen','/quant/data-inspector/','button secondary')])]);
 main.append(el('div',{class:'layout'},[left,side]),actions(s.workspaces));
 const technical=await api.getTechnicalIntelligence(ticker);
 const section=el('section',{class:'section'},[el('span',{class:'eyebrow',text:'Kursstruktur verstehen'}),el('h2',{text:'Technical Intelligence'})]);
 if(technical.state==='AVAILABLE'){
  section.append(el('div',{class:'technical-summary'},[['Trend',technical.trend],['Momentum',technical.momentum],['Volatilität',technical.volatility]].map(([label,state])=>el('div',{},[el('span',{class:'muted',text:label}),el('h3',{text:state.label})]))),el('p',{class:'muted',text:'Analyse bis '+technical.asOf+' · '+technical.methodology}),el('p',{text:'Elliott Wave: '+technical.elliott.label+'. Die Szenarien sind keine Wahrscheinlichkeitsprognose.'}),actions([{label:'Vollständige Technical-Analyse',href:technical.workspace},{label:'Elliott: Szenarien & Invalidation',href:technical.elliottWorkspace}]));
 }else section.append(notice('Technische Analyse derzeit nicht verfügbar','Der vollständige Workspace bleibt über die Analysezugänge erreichbar.'));
 main.append(section);
}
async function technicalWorkspacePage(ticker,elliottMode){
 const data=await api.getTechnicalWorkspace(ticker);
 main.append(heading(elliottMode?'Elliott Wave · Szenarien verstehen':'Kursstruktur untersuchen',ticker+' · Chart, Evidenz und alternative Entwicklungen.'));
 if(data.state!=='AVAILABLE'){main.append(notice('Analyse derzeit nicht verfügbar','Die Daten erfüllen die Anforderungen dieser Ansicht derzeit nicht.'),actions([{label:'Bestehenden Workspace öffnen',href:'/quant/technical/?symbol='+encodeURIComponent(ticker)}]));return;}
 const root=el('section',{class:'technical-workspace'}),chart=el('div',{class:'technical-chart-host'}),select=el('select',{'aria-label':'Unternehmen'},universe.stocks.map(s=>el('option',{value:s.ticker,text:s.ticker+' · '+s.name}))),layer=el('select',{'aria-label':'Chart-Ebene'},[['AUTO','Übersicht'],['STRUCTURE','Marktstruktur'],['TREND','Trend'],['MOMENTUM','Momentum'],['SUPPORT_RESISTANCE','Support / Resistance'],['FIBONACCI','Fibonacci'],['ELLIOTT','Elliott Wave']].map(([value,text])=>el('option',{value,text}))),range=el('select',{'aria-label':'Chart-Zeitraum'},[['1M','1 Monat'],['3M','3 Monate'],['6M','6 Monate'],['YTD','Seit Jahresbeginn'],['1Y','1 Jahr'],['5Y','5 Jahre'],['MAX','Max · vorhandenes Analysefenster']].map(([value,text])=>el('option',{value,text}))),mode=el('select',{'aria-label':'Chart-Darstellung'},[['candles','Kerzen'],['line','Linie']].map(([value,text])=>el('option',{value,text}))),alt=el('input',{type:'checkbox','aria-label':'Alternativen im Chart'}),labels=el('input',{type:'checkbox','aria-label':'Chart-Beschriftungen'});labels.checked=innerWidth>=650;
 select.value=ticker;select.onchange=()=>location.assign(href(elliottMode?'elliott':'technical',select.value));layer.value=elliottMode?'ELLIOTT':'AUTO';range.value='1Y';
 const draw=()=>{const annotations=data.chart.annotations.filter(a=>(a.layers||[]).includes(layer.value)||(alt.checked&&((a.layers||[]).includes('ALTERNATIVE')||(layer.value==='ELLIOTT'&&(a.layers||[]).includes('ELLIOTT_ALT')))));S.mount(chart,QuantCharts.technicalChart({bars:data.chart.bars,series:data.chart.series,annotations,annotationLabels:labels.checked,range:range.value,mode:mode.value,width:Math.max(300,Math.min(1168,main.clientWidth-40)),height:innerWidth<650?340:460,title:ticker+' · '+(elliottMode?'Elliott Wave':'Technical Intelligence'),description:'Historische Kurse und ausdrücklich gekennzeichnete Projektionen. Keine Zukunftsdaten im Kursverlauf.'}));};
 layer.onchange=range.onchange=mode.onchange=alt.onchange=labels.onchange=draw;
 const primary=data.scenarios.find(s=>s.kind==='PRIMARY');
 root.append(el('div',{class:'workspace-toolbar'},[select,layer,range,mode,el('label',{class:'toggle'},[alt,el('span',{text:'Alternativen'})]),el('label',{class:'toggle'},[labels,el('span',{text:'Chart-Texte'})])]),el('div',{class:'workspace-meaning'},[el('h2',{text:elliottMode?data.elliott.label:(primary?primary.label+' · '+primary.status:'Kursstruktur im Detail')}),el('p',{class:'muted',text:'Analysestand: '+data.asOf+' · Szenarien beschreiben Bedingungen, keine gesicherten Vorhersagen.'})]),chart,el('p',{class:'chart-key',text:'Durchgezogen: Historie · farbig: laufende Struktur · gestrichelt: Projektion. Der Jetzt-Marker trennt Daten und Szenarien. Chart-Texte lassen sich einblenden; vollständige Zählungen und Bedingungen stehen darunter.'}),el('p',{class:'muted',text:'Analysefenster: '+data.chart.bars.timestamps[0]+' bis '+data.asOf+'. Kursbasis: '+(data.priceBasis==='SPLIT_ADJUSTED'?'splitbereinigt':data.priceBasis)+'. Max zeigt das vorhandene Analysefenster; weitere Kursgeschichte findest du in der Aktienanalyse.'}));main.append(root);draw();
 const price=v=>Number.isFinite(v)?v.toLocaleString('de-DE',{maximumFractionDigits:2}):'Nicht verfügbar';
 function countSection(count,label){if(!count)return notice(label,'Keine validierte Zählung verfügbar.');return el('section',{class:'wave-count'},[el('h3',{text:label}),el('p',{text:'Aktuelle Welle: '+(count.currentWave?.label||'Nicht verfügbar')+' · '+(count.currentWave?.status==='DEVELOPING'?'noch in Entwicklung':'Status im Detail prüfen')}),el('p',{text:'Invalidation: '+price(count.invalidation?.price)+' · '+(count.invalidation?.statement||'Bedingung nicht verfügbar')}),el('p',{text:'Projektionszonen: '+((count.projection?.zones||[]).map(z=>z.label+': '+price(z.zoneLow)+'–'+price(z.zoneHigh)).join(' · ')||'Keine bestätigten Zonen')}),el('details',{},[el('summary',{text:'Vollständige Zählung & Regeln'}),el('div',{class:'table-wrap',tabindex:'0'},[el('table',{},[el('thead',{},[el('tr',{},['Welle','Von','Bis','Status'].map(text=>el('th',{text})))]),el('tbody',{},(count.waves||[]).map(w=>el('tr',{},[el('td',{text:w.label}),el('td',{text:w.fromTime+' · '+price(w.fromPrice)}),el('td',{text:w.toTime+' · '+price(w.toPrice)}),el('td',{text:{CONFIRMED:'Bestätigt',DEVELOPING:'In Entwicklung',PROJECTED:'Projektion'}[w.status]||w.status})])))])]),...(count.hardRuleResults||[]).map(r=>el('p',{class:'muted',text:(r.passed===true?'Erfüllt: ':r.passed===false?'Verletzt: ':'Noch offen: ')+r.detail}))])]);}
 const wave=el('section',{class:'section'},[el('h2',{text:'Elliott · Zählungen und Grenzen'}),el('p',{class:'muted',text:'Method Fit bewertet, wie gut die Zählung zu den Regeln passt. Es ist keine Eintrittswahrscheinlichkeit.'}),countSection(data.elliott.primary,'Basiszählung'),countSection(data.elliott.alternative,'Alternative Zählung'),el('details',{},[el('summary',{text:'Confidence & Methodik'}),el('p',{text:'Method Fit: '+price(data.elliott.methodFit)+'/100. '+(data.elliott.disclaimer||'Keine Wahrscheinlichkeit.')}),el('p',{class:'muted',text:data.elliott.methodology})])]);
 const scenarios=el('section',{class:'section'},[el('h2',{text:'Szenarien & Invalidation'}),...data.scenarios.map(s=>el('article',{class:'scenario-row'},[el('div',{},[el('h3',{text:s.label}),el('span',{class:'muted',text:s.status})]),el('div',{},[el('p',{text:s.confirmation||'Bestätigungsbedingung nicht verfügbar'}),el('p',{text:'Invalidation: '+price(s.invalidation?.price)+' · '+(s.invalidation?.rule||'Bedingung nicht verfügbar')}),el('p',{text:'Zielzonen: '+(s.targets.map(t=>price(t.zoneLow)+'–'+price(t.zoneHigh)).join(' · ')||'Keine verfügbar')}),el('details',{},[el('summary',{text:'Evidenz und Gegenargumente'}),el('p',{text:s.expiration||'Ablaufbedingung nicht verfügbar'}),...s.support.map(e=>el('p',{text:'Dafür: '+e.statement})),...s.conflicts.map(e=>el('p',{text:'Dagegen: '+e.statement}))])])]))]);
 main.append(...(elliottMode?[wave,scenarios]:[scenarios,wave]),actions([{label:'Alle technischen Details im bestehenden Workspace',href:data.legacyHref},{label:'Vollständige Kursgeschichte',href:data.priceHistoryHref},{label:'Fundamentals',href:href('fundamentals',ticker)}]));
}
async function signalsPage(){
 main.append(heading('Was hat sich verändert?','Belegte Zustandswechsel aus vorhandenen Tagesschlusskursen.'));
 const lookback=[5,20,60].includes(Number(params.get('window')))?Number(params.get('window')):20,data=await api.getSignals({lookback});if(data.state!=='AVAILABLE'){main.append(notice('Änderungen derzeit nicht auswertbar','Ohne vergleichbare Kursbeobachtungen und freigegebene Daten erzeugen wir keine Signale.'));return;}
 const windowSelect=el('select',{'aria-label':'Signal-Zeitraum'},[5,20,60].map(n=>el('option',{value:String(n),text:n+' EOD-Beobachtungen'})));windowSelect.value=String(lookback);windowSelect.onchange=()=>location.assign(href('signals')+'&window='+windowSelect.value);
 main.append(el('p',{class:'scope-note',text:'Verfügbare Kursstände: '+[...new Set(data.results.filter(r=>r.state==='AVAILABLE').map(r=>r.asOf))].join(', ')+' · '+data.results.filter(r=>r.state==='AVAILABLE').length+' Unternehmen geprüft'}));
 const company=el('select',{'aria-label':'Signals Unternehmen'},[el('option',{value:'all',text:'Alle verfügbaren Unternehmen'}),...data.results.filter(r=>r.state==='AVAILABLE').map(r=>el('option',{value:r.ticker,text:r.ticker}))]),target=el('div');
 main.append(el('div',{class:'workspace-controls'},[company,windowSelect]),el('p',{class:'muted',text:'Betrachtet werden die letzten '+lookback+' vorhandenen EOD-Beobachtungen je Unternehmen. Ein Wechsel liegt zwischen zwei angegebenen Daten; er ist kein Echtzeit- oder Handelssignal.'}));
 main.append(el('details',{},[el('summary',{text:'Datenabdeckung & Beobachtungszeitraum'}),...data.results.map(r=>el('p',{text:r.ticker+' · '+(r.state==='AVAILABLE'?'Vergleich '+r.from+' bis '+r.asOf:'Nicht auswertbar · Daten oder Freigabe fehlen')})),el('p',{class:'muted',text:'Auswertung des heute vorhandenen Datenbestands. Keine Rekonstruktion des damaligen Wissensstands und kein Point-in-Time-Backtest. Der Kalender prüft Sitzungsschluss, keine endgültige Bestätigung durch den Anbieter.'})]));
 if(data.partial)main.append(notice('Nicht alle Unternehmen auswertbar','Die Übersicht ist unvollständig. Fehlende Quellen erzeugen keine Ersatzereignisse.'));
 function draw(){const events=data.events.filter(e=>company.value==='all'||e.ticker===company.value);S.clear(target);if(!events.length){target.append(notice('Keine belegten Wechsel in diesem Ausschnitt','Ein unveränderter Zustand ist kein neues Signal. Die Regeln bleiben im Screener untersuchbar.'));return;}
 for(const e of events){const title=e.definitionId==='positive-momentum'?(e.transition==='ENTERED'?'Sechs-Monats-Entwicklung wieder nicht negativ':'Sechs-Monats-Entwicklung wird negativ'):(e.transition==='ENTERED'?'Zurück am langfristigen Trendbereich':'Unter den langfristigen Trendbereich gefallen');
 target.append(el('article',{class:'signal-event'},[el('div',{class:'signal-date'},[el('span',{class:'eyebrow',text:e.asOf}),link(e.ticker,href('stock',e.ticker))]),el('div',{},[el('h2',{text:title}),el('p',{class:'muted',text:'Regel: '+e.rule+'. Vergleich '+e.previousAsOf+' → '+e.asOf+'.'}),el('details',{},[el('summary',{text:'Warum wurde der Wechsel erkannt?'}),...e.evidence.map(m=>el('p',{text:(VUCatalog.field(m.metricId)?.label||m.metricId)+': '+m.previous.toLocaleString('de-DE',{maximumFractionDigits:3})+' % → '+m.current.toLocaleString('de-DE',{maximumFractionDigits:3})+' %'})),el('p',{class:'muted',text:'Historische Beobachtung, keine Kauf- oder Verkaufsempfehlung. '+(e.expiration.at?'Abgelöst durch die nächste vorhandene Beobachtung vom '+e.expiration.at+'.':'Letzte Beobachtung dieses Datensatzes. Keine laufende Überwachung behauptet.')}),el('p',{class:'muted',text:'Definition '+e.definitionId+' · v'+e.definitionVersion+' · Daten bis '+e.snapshotAsOf})]),link('Regel im Screener untersuchen',href('screener')+'&query='+encodeURIComponent(VUScreenerWorkspace.encode(e.query)),'button secondary')])]));
 }}if(data.results.some(r=>r.state==='AVAILABLE'&&r.ticker===params.get('ticker')))company.value=params.get('ticker');company.onchange=draw;main.append(target,actions([{label:'Discover',href:href('discover')},{label:'Bestehender Radar',href:'/quant/radar/'},{label:'Watchlist',href:href('watchlist')}]));draw();
}
async function atlasPage(){
 main.append(el('div',{class:'atlas-intro'},[el('img',{src:'/assets/atlas.png',alt:'Atlas',width:'88',height:'88'}),heading('Ask Atlas · verstehen, was dahintersteht','Geführte Fragen mit belegten Antworten aus Vision Universe®.')]),el('p',{class:'scope-note',text:'Diese Vorschau nutzt feste Fragen und vorhandene Produktdaten, kein angeschlossenes Sprachmodell. Freie KI-Unterhaltung ist noch nicht aktiviert.'}));
 const tools=VUAtlasTools.create(api),company=el('select',{'aria-label':'Atlas Unternehmen'},universe.stocks.map(s=>el('option',{value:s.ticker,text:s.ticker+' · '+s.name}))),question=el('select',{'aria-label':'Atlas Frage'},[['quality','Wie profitabel arbeitet das Unternehmen?'],['growth','Wie verändert sich das Geschäft?'],['value','Wie wird das Unternehmen bewertet?'],['momentum','Wie hat sich der Kurs entwickelt?'],['risk','Wie stark schwankte der Kurs?'],['technical','Was sagt die technische Analyse?']].map(([value,text])=>el('option',{value,text}))),answer=el('section',{class:'atlas-answer','aria-live':'polite'});company.value=params.get('ticker')||'NVDA';let request=0;
 async function draw(){const current=++request,ticker=company.value,topic=question.value;S.mount(answer,el('p',{class:'muted',text:'Vorhandene Evidenz wird geladen …'}));const result=await tools.call(topic==='technical'?'getTechnicalEvidence':'getQuantEvidence',{ticker});if(current!==request)return;S.clear(answer);
  if(!result.ok||result.data?.state!=='AVAILABLE'){answer.append(notice('Dazu fehlt derzeit belastbare Evidenz','Ohne verfügbare Produktdaten erzeugt Atlas keine Ersatzantwort oder erfundene Kennzahlen.'));return;}
  const data=result.data;
  if(topic==='technical')answer.append(el('h2',{text:'Die Kursstruktur von '+ticker}),el('p',{class:'muted',text:'Analyse bis '+data.asOf+' · '+data.methodology}),el('div',{class:'technical-summary'},[['Trend',data.trend],['Momentum',data.momentum],['Volatilität',data.volatility]].map(([label,state])=>el('div',{},[el('span',{class:'muted',text:label}),el('h3',{text:state.label})]))),el('p',{text:'Elliott Wave: '+data.elliott.label+'. Szenarien und Confidence sind keine garantierten Wahrscheinlichkeiten.'}),actions([{label:'Technische Evidenz untersuchen',href:data.workspace},{label:'Elliott-Szenarien',href:data.elliottWorkspace}]));
  else{const family=data.families.find(f=>f.id===topic);answer.append(el('span',{class:'eyebrow',text:data.name}),el('h2',{text:family.question}),el('p',{class:'muted',text:'Geschäftsdaten bis '+data.fundamentalsAsOf+' · verfügbar seit '+data.availableAt+' · Kurse bis '+data.asOf}),...family.metrics.map(m=>el('article',{class:'atlas-evidence'},[el('div',{},[el('h3',{text:m.label}),el('p',{class:'muted',text:m.description})]),el('strong',{text:formatFactor(m)}),el('details',{},[el('summary',{text:'Beleg & Definition'}),el('p',{text:'Kennzahl '+m.registryId+' · Definition '+m.definitionVersion+' · Stand '+m.asOf}),el('p',{class:'muted',text:m.state==='AVAILABLE'?'Unveränderter Wert aus dem bestehenden Produktvertrag.':'Diese Kennzahl ist in der aktuellen Quelle oder Freigabe nicht verfügbar.'})])])),actions([{label:'Vollständige Quant-Analyse',href:href('quant',ticker)},{label:'Fundamental-Historie',href:href('fundamentals',ticker)},{label:'Aktie untersuchen',href:href('stock',ticker)}]));}
  answer.append(el('p',{class:'muted atlas-limit',text:'Die Einordnung beschreibt vorhandene Daten, keine Kaufempfehlung. Es werden keine zusätzlichen Scores, Kursziele oder historischen Ergebnisse generiert.'}));
 }
 company.onchange=question.onchange=draw;main.append(el('div',{class:'atlas-controls'},[el('label',{},[el('span',{text:'Unternehmen'}),company]),el('label',{},[el('span',{text:'Deine Frage'}),question])]),answer,el('details',{},[el('summary',{text:'Wie Atlas an seine Antworten kommt'}),el('p',{text:'Diese Antworten werden aus denselben Produktdiensten wie Quant, Technical und Fundamentals zusammengestellt. Die zugehörigen Werkzeuge sind ausschließlich lesend; sie können weder freien Code ausführen noch beliebige Quellen abrufen oder eine Strategie speichern.'}),el('p',{text:'Ein später angebundenes Sprachmodell kann diese strukturierten Werkzeuge nutzen. In dieser Ansicht werden noch keine Fragen an einen KI-Anbieter übertragen.'}),link('Bisheriger AI-Workspace','/quant/ai/','button secondary')]));await draw();
}
async function homePage(){
 let tickers=[],storageUnavailable=false;try{tickers=VUWatchlistWorkspace.load(localStorage);}catch{storageUnavailable=true;}
 const data=await api.getHomeIntelligence(tickers),observations=data.market.observations;
 main.append(heading('Was ist für dich wichtig?','Unternehmen beobachten. Veränderungen verstehen. Deine nächste Analyse finden.'));
 const session=el('div',{class:'home-session'});
 function showSession(s){S.clear(session);session.append(el('div',{},[el('strong',{text:s.label}),el('span',{class:'muted',text:s.state==='AVAILABLE'?' · Kalenderstand '+s.localDate+' '+s.localTime.slice(0,5)+' New York':' · Kalender derzeit nicht verfügbar'})]),el('span',{class:'pill',text:'Kurse: letzter verfügbarer Tagesstand'}));}
 showSession(data.session);main.append(session,el('p',{class:'muted home-session-note',text:'Die Handelsphase folgt dem Börsenkalender. Diese Vorschau zeigt keine Echtzeitkurse; eine geöffnete Börse bedeutet keinen aktiven Datenstream.'}));
 let refreshing=false;const timer=setInterval(async()=>{if(document.hidden||refreshing)return;refreshing=true;try{showSession(await api.getMarketSession());}finally{refreshing=false;}},60000);addEventListener('pagehide',()=>clearInterval(timer),{once:true});
 const personal=el('section',{class:'home-personal'},[el('span',{class:'eyebrow',text:'Deine Perspektive'}),el('h2',{text:'Unternehmen, die dich interessieren'})]);
 if(storageUnavailable)personal.append(notice('Deine Auswahl bleibt geschützt','Die gespeicherte Watchlist ist derzeit nicht lesbar. Sie wird nicht zurückgesetzt.'));
 else if(data.watchlist.state==='EMPTY')personal.append(el('p',{class:'muted',text:'Stelle deine eigene Watchlist zusammen. Hier findest du anschließend ihre aktuelle Kursstruktur und die passenden Analysen.'}));
 else{for(const s of data.watchlist.members.slice(0,3))personal.append(el('div',{class:'home-watch-row'},[link(s.ticker,href('stock',s.ticker)),el('span',{class:'muted',text:(s.state!=='AVAILABLE'?'Analyse derzeit nicht verfügbar':!Number.isFinite(s.above200?.value)?'Trend derzeit nicht verfügbar':s.above200.value>=0?'Am langfristigen Trendbereich oder darüber':'Unter dem langfristigen Trendbereich')+(s.state==='AVAILABLE'?' · Kursstand '+s.asOf:'')})]));if(data.watchlist.members.length>3)personal.append(el('p',{class:'muted',text:'Weitere '+(data.watchlist.members.length-3)+' Titel in deiner Watchlist.'}));}
 personal.append(link(tickers.length?'Deine Watchlist öffnen':'Watchlist zusammenstellen',href('watchlist'),'button'));
 const changes=el('section',{},[el('span',{class:'eyebrow',text:'Was sich verändert hat'}),el('h2',{text:'Nicht jede Bewegung ist ein neues Signal'}),el('p',{class:'muted',text:'Untersuche belegte Wechsel über Trendgrenzen und in der Kursentwicklung. Mit Datum, Vergleichswert und derselben Regel im Screener.'}),link('Historische Änderungen untersuchen',href('signals')+'&window=60','button secondary')]);
 main.append(el('div',{class:'home-priorities'},[personal,changes]));
 const markets=el('section',{class:'section'},[el('div',{class:'home-section-heading'},[el('div',{},[el('span',{class:'eyebrow',text:'Märkte einordnen'}),el('h2',{text:'Einblicke in den verfügbaren Analysebereich'})]),link('Markets öffnen',href('markets'),'button secondary')]),el('p',{class:'scope-note',text:observations.length+' Unternehmen mit verfügbaren Daten. Das ist kein Gesamtmarktbild; Marktbreite, Branchenführung und ein Marktregime lassen sich daraus nicht belastbar ableiten.'})]);
 if(observations.length)markets.append(stockRows(observations.map(o=>o.stock),'momentum6m','6 Monate',true));else markets.append(notice('Marktdaten derzeit nicht verfügbar','Wir zeigen keine Ersatzkurse und leiten daraus keinen Marktstatus ab.'));
 main.append(markets,el('section',{class:'home-research section'},[el('div',{},[el('span',{class:'eyebrow',text:'Dein nächster Schritt'}),el('h2',{text:'Von der Frage zur vollständigen Analyse'}),el('p',{class:'muted',text:'Geführt starten oder direkt in den professionellen Workspace springen.'})]),el('div',{class:'links'},[link('Ideen mit sichtbaren Regeln entdecken',href('discover')),link('Eigene Kriterien im Screener kombinieren',href('screener')),link('Alle Research-Workspaces',href('research')),link('Morning Briefing','/morning/'),link('News','/news/'),link('Weekly Magazine','/magazin/'),link('Ask Atlas',href('atlas'))])]));
}
async function watchlistPage(){
 main.append(heading('Deine Unternehmen im Blick','Beobachte selbst gewählte Titel und vertiefe ihre aktuelle Entwicklung.'));
 let selected;try{selected=VUWatchlistWorkspace.load(localStorage);}catch{main.append(notice('Gespeicherte Watchlist nicht lesbar','Die vorhandenen Einträge bleiben erhalten und werden nicht automatisch überschrieben.'),link('Bisherige Watchlist öffnen','/quant/watchlist/','button secondary'));return;}
 const ticker=el('input',{type:'text',maxlength:'12',placeholder:'z. B. NVDA','aria-label':'Watchlist Ticker'}),message=el('div',{'aria-live':'polite'}),target=el('section',{'aria-live':'polite'});let request=0;
 const changed=()=>S.mount(message,notice('Auswahl noch nicht gespeichert','Speichere deine Watchlist, um sie beim nächsten Öffnen wiederzufinden.'));
 async function draw(){const id=++request,data=await api.getWatchlistIntelligence(selected);if(id!==request)return;S.clear(target);
  if(data.state==='EMPTY'){target.append(notice('Wen möchtest du beobachten?','Füge deinen ersten Ticker hinzu. Die Watchlist startet ohne Beispielbestände.'));return;}
  if(!Array.isArray(data.members)){target.append(notice('Auswahl derzeit nicht auswertbar','Deine Eingaben bleiben erhalten.'));return;}
  target.append(el('p',{class:'scope-note',text:data.members.length+' Titel ausgewählt · '+data.members.filter(s=>s.state==='AVAILABLE').length+' im verfügbaren Analysebereich'}));
  for(const s of data.members){const available=s.state==='AVAILABLE',trend=s.above200?.value;
   target.append(el('article',{class:'watchlist-member'},[el('div',{},[link(s.ticker,href('stock',s.ticker)),el('p',{class:'muted',text:s.name}),el('button',{class:'button secondary',text:'Entfernen','aria-label':s.ticker+' aus Watchlist entfernen',onclick:()=>{selected=selected.filter(t=>t!==s.ticker);changed();draw();}})]),el('div',{},[
    el('h2',{text:!available?'Analyse noch nicht verfügbar':!Number.isFinite(trend)?'Trend noch nicht einordenbar':trend>=0?'Am langfristigen Trendbereich oder darüber':'Unter dem langfristigen Trendbereich'}),
    available?el('p',{class:'muted',text:'Schlusskurs '+n(s.price,2)+' · Kursstand '+s.asOf}):el('p',{class:'muted',text:'Für diesen Ticker fehlen in dieser Ansicht Daten oder die Anzeigefreigabe. Er bleibt auf deiner Liste.'}),
    available?evidence(s):null,
    available?el('details',{},[el('summary',{text:'Warum diese Einordnung?'}),el('p',{text:'Abstand zum 200-Tage-Durchschnitt: '+n(s.above200)+'. Die Aussage beschreibt den vorhandenen Kursstand, keine Prognose und keinen neuen Zustandswechsel.'}),el('p',{class:'muted',text:'Geschäftsdaten bis '+s.fundamentalsAsOf+' · verfügbar seit '+s.availableAt})]):null,
    actions(available?[{label:'Aktie untersuchen',href:href('stock',s.ticker)},{label:'Historische Änderungen',href:href('signals',s.ticker)+'&window=60'},{label:'Fundamental-Historie',href:href('fundamentals',s.ticker)}]:[{label:'Analysebereich öffnen',href:href('research')}])
   ])]));
  }
 }
 const add=el('button',{class:'button secondary',text:'Titel hinzufügen',onclick:()=>{try{const symbol=ticker.value.trim().toUpperCase();selected=VUWatchlistWorkspace.validate([...selected,symbol]);ticker.value='';changed();draw();}catch{S.mount(message,notice('Ticker prüfen','Verwende einen gültigen Ticker, der noch nicht auf deiner Liste steht.'))}}}),save=el('button',{class:'button',text:'Watchlist speichern',onclick:()=>{try{VUWatchlistWorkspace.save(localStorage,selected);S.mount(message,notice('Watchlist gespeichert','Nur in diesem Browser gespeichert. Keine automatische Überwachung oder Benachrichtigung.'));}catch{S.mount(message,notice('Speichern nicht möglich','Deine Eingaben bleiben sichtbar. Der Browserspeicher ist möglicherweise nicht verfügbar.'));}}});
 main.append(el('div',{class:'watchlist-editor'},[el('label',{},[el('span',{text:'Unternehmen auswählen'}),ticker]),add,save]),message,target,el('details',{},[el('summary',{text:'Bestehende Watchlist & Speicherung'}),el('p',{text:'Diese Vorschau speichert deine Auswahl getrennt von der bisherigen Watchlist. Vorhandene Einträge und deren Funktionen bleiben unverändert. Beispielauswahlen werden nicht automatisch importiert.'}),link('Bisherige Watchlist öffnen','/quant/watchlist/','button secondary')]),actions([{label:'Unternehmen entdecken',href:href('discover')},{label:'Portfolio',href:href('portfolio')}]));await draw();
}
async function portfolioPage(){
 main.append(heading('Deine Positionen im Zusammenhang','Trage Bestände ein und untersuche ihren Wert und ihre Gewichtung.'));
 let positions;try{positions=VUPortfolioWorkspace.load(localStorage);}catch{main.append(notice('Gespeicherte Bestände nicht lesbar','Die vorhandenen Daten bleiben erhalten. Diese Ansicht überschreibt sie nicht automatisch.'));return;}
 const ticker=el('input',{type:'text',placeholder:'NVDA',maxlength:'12','aria-label':'Position Ticker'}),quantity=el('input',{type:'number',min:'0',step:'any',placeholder:'Anzahl','aria-label':'Stückzahl'}),message=el('div',{'aria-live':'polite'}),holdings=el('section',{'aria-live':'polite'});let request=0;
 const usd=value=>value===null?'Nicht verfügbar':value.toLocaleString('de-DE',{style:'currency',currency:'USD',maximumFractionDigits:2});
 async function draw(){const current=++request,data=await api.getPortfolioIntelligence(positions);if(current!==request)return;S.clear(holdings);
  if(data.state==='EMPTY'){holdings.append(notice('Noch keine Positionen','Beginne mit einem Ticker und der Stückzahl. Es werden keine Beispielpositionen angelegt.'));return;}
  if(!Array.isArray(data.positions)){holdings.append(notice('Bestände nicht auswertbar','Prüfe die Eingaben und die verfügbare Datenquelle.'));return;}
  holdings.append(el('div',{class:'portfolio-total'},[el('span',{class:'eyebrow',text:'Erfasste Positionen · USD'}),el('div',{class:'quote',text:usd(data.total)}),el('p',{class:'muted',text:data.total!==null?'Bewertung mit den zuletzt verfügbaren Schlusskursen vom '+data.asOf+'. Kein Depotstand in Echtzeit.':'Ein Gesamtwert und Gewichte werden erst angezeigt, wenn für jede Position ein vergleichbarer Kursstand vorliegt.'})]));
  holdings.append(el('div',{class:'holdings'},data.positions.map(p=>el('article',{class:'holding'},[
   el('div',{},[link(p.ticker,href('stock',p.ticker)),el('p',{class:'muted',text:p.quantity.toLocaleString('de-DE',{maximumSignificantDigits:15})+' Stück · '+p.name})]),
   el('div',{class:'holding-value'},[el('strong',{text:usd(p.value)}),el('p',{class:'muted',text:p.state==='AVAILABLE'?'Kurs '+usd(p.price)+' · '+p.asOf:'Für diesen Bestand ist kein freigegebener Kurs verfügbar.'})]),
   el('div',{class:'holding-weight'},[el('span',{text:p.weight===null?'Gewicht offen':(p.weight*100).toLocaleString('de-DE',{maximumFractionDigits:1})+' %'}),p.weight===null?null:el('div',{class:'weight-track','aria-hidden':'true'},[el('span',{style:'width:'+(p.weight*100)+'%'})])]),
   el('div',{class:'actions'},[el('button',{class:'button secondary',text:'Bearbeiten',onclick:()=>{ticker.value=p.ticker;quantity.value=String(p.quantity);quantity.focus();}}),el('button',{class:'button secondary',text:'Entfernen','aria-label':p.ticker+' entfernen',onclick:()=>{positions=positions.filter(x=>x.ticker!==p.ticker);S.mount(message,notice('Änderung noch nicht gespeichert','Speichere die Bestände, um die Änderung in diesem Browser zu behalten.'));draw();}})])]))));
 }
 const add=el('button',{class:'button secondary',text:'Position übernehmen',onclick:()=>{try{const next={ticker:ticker.value.trim().toUpperCase(),quantity:Number(quantity.value)};VUPortfolioWorkspace.validate([next]);positions=VUPortfolioWorkspace.validate([...positions.filter(p=>p.ticker!==next.ticker),next]);S.mount(message,notice('Änderung noch nicht gespeichert','Speichere die Bestände, um sie beim nächsten Öffnen wiederzufinden.'));ticker.value='';quantity.value='';draw();}catch{S.mount(message,notice('Position prüfen','Gib einen gültigen Ticker und eine positive Stückzahl ein.'))}}});
 const save=el('button',{class:'button',text:'Bestände speichern',onclick:()=>{try{VUPortfolioWorkspace.save(localStorage,positions);S.mount(message,notice('Bestände gespeichert','Nur in diesem Browser gespeichert. Keine Übertragung an einen Broker.'));}catch{S.mount(message,notice('Speichern nicht möglich','Die Eingaben bleiben hier sichtbar. Prüfe, ob der Browserspeicher verfügbar ist.'));}}});
 main.append(el('div',{class:'portfolio-editor'},[el('label',{},[el('span',{text:'Ticker'}),ticker]),el('label',{},[el('span',{text:'Stückzahl'}),quantity]),add,save]),message,holdings,el('details',{},[el('summary',{text:'Was diese Auswertung umfasst'}),el('p',{text:'Bewertet werden ausschließlich deine erfassten Stückzahlen mit vorhandenen USD-Schlusskursen. Nicht erfasst sind Cash, Gebühren, Steuern, Kaufkurse und Währungsumrechnung. Deshalb werden weder Gewinn noch Rendite ausgewiesen.'}),el('p',{text:'Die Gewichtung zeigt Konzentration innerhalb der erfassten Bestände. Sektor-, Korrelations- und Drawdown-Analysen benötigen weitere validierte Daten und werden hier nicht geschätzt.'})]),actions([{label:'Watchlist öffnen',href:href('watchlist')},{label:'Unternehmen vergleichen',href:href('compare')},{label:'Strategien',href:href('strategies')}]));await draw();
}
async function strategyPage(){
 main.append(heading('Aus Überzeugung werden Regeln','Definiere Auswahl, Gewichtung und Kosten. Bewahre jede Änderung nachvollziehbar auf.'));
 const context=await api.getStrategyContext();if(context.state!=='AVAILABLE'){main.append(notice('Methodik derzeit nicht verfügbar','Der bestehende Strategy Builder bleibt erreichbar.'),actions([{label:'Strategy Builder öffnen',href:'/quant/strategies/builder/'}]));return;}
 let saved,definition=context.definition;try{saved=VUStrategyWorkspace.load(localStorage);if(saved)definition=VUStrategy.getVersion(saved).definition;if(params.has('query'))definition=VUStrategy.createDefinition({...definition,filters:VUScreenerWorkspace.decode(params.get('query')).filters});}catch{main.append(notice('Gespeicherte Strategie prüfen','Der Entwurf oder die übergebenen Regeln sind nicht gültig. Vorhandene Daten werden nicht überschrieben.'));return;}
 const fields={};function input(id,label,value,attrs={}){const control=el('input',{id:'strategy-'+id,value:String(value),...attrs});fields[id]=control;return el('label',{class:'strategy-field'},[el('span',{text:label}),control]);}
 function select(id,label,value,options){const control=el('select',{'aria-label':label},options.map(([value,text])=>el('option',{value,text})));control.value=value;fields[id]=control;return el('label',{class:'strategy-field'},[el('span',{text:label}),control]);}
 const filters=el('div',{class:'strategy-rules'},definition.filters.length?definition.filters.map(f=>el('p',{text:(VUCatalog.field(f.field)?.label||f.field)+' '+(VUCatalog.operator(f.operator)?.label||f.operator)+' '+f.value+(f.scale==='percentile'?' · Perzentil':VUCatalog.field(f.field)?.unit==='pct'?' %':VUCatalog.field(f.field)?.unit==='usd'?' USD':'')})):[el('p',{text:'Noch keine Auswahlkriterien. Beginne im Screener und übernimm deine Regeln.'})]);
 let editHref=href('screener');try{editHref+='&query='+encodeURIComponent(VUScreenerWorkspace.encode(VUScreenerWorkspace.build(definition.filters)));}catch{}
 const names={quality:'Qualität',momentum:'Momentum',value:'Bewertung',growth:'Wachstum',risk:'Risiko'},status=el('div',{'aria-live':'polite'}),preview=el('section',{'aria-live':'polite'}),history=el('pre',{class:'query-code',text:saved?JSON.stringify(saved,null,2):'Noch keine gespeicherte Version.'});
 main.append(input('name','Name des Entwurfs',saved?.strategy.name||'Meine Investmentidee',{maxlength:'120'}),el('section',{class:'section'},[el('h2',{text:'1 · Welche Unternehmen kommen infrage?'}),filters,link('Kriterien im Screener bearbeiten',editHref,'button secondary')]),el('section',{class:'section'},[el('h2',{text:'2 · Was soll bei der Auswahl zählen?'}),el('p',{class:'muted',text:'Die Faktoranteile müssen zusammen 100 % ergeben. Sie definieren das spätere Ranking; aus fünf Titeln wird hier kein Ranking berechnet.'}),el('div',{class:'strategy-grid'},context.factors.map(f=>input(f,names[f]+' · Anteil in %',(definition.ranking.factors.find(r=>r.factor===f)?.weight||0)*100,{type:'number',min:'0',max:'100',step:'1'})))]),
 el('section',{class:'section'},[el('h2',{text:'3 · Portfolio und Ausführung'}),el('div',{class:'strategy-grid'},[
 input('positions','Anzahl Positionen',definition.portfolio.positions,{type:'number',min:context.constraints.minPositions,max:context.constraints.maxPositions,step:'1'}),
 select('weighting','Positionsgewichtung',definition.portfolio.weighting,context.weightings.map(v=>[v,{equal:'Gleichgewichtet',score:'Nach Faktorwert',volatility:'Nach Volatilität'}[v]])),
 select('rebalance','Umschichten',definition.rebalance,context.rebalance.map(v=>[v,{monthly:'Monatlich',quarterly:'Quartalsweise'}[v]])),
 select('timing','Ausführungszeitpunkt',definition.execution.timing,context.timings.map(v=>[v,{next_open:'Nächste Eröffnung',next_close:'Nächster Schlusskurs'}[v]])),
 input('cost','Transaktionskosten · Basispunkte',definition.execution.transactionCostsBps,{type:'number',min:'0',max:context.costs.maxTransactionCostsBps,step:'any'}),input('slippage','Slippage · Basispunkte',definition.execution.slippageBps,{type:'number',min:'0',max:context.costs.maxSlippageBps,step:'any'})]),
 el('p',{class:'muted',text:'1 Basispunkt = 0,01 %. Kosten gelten beim Kauf und Verkauf. Entscheidungen werden frühestens am nächsten Handelszeitpunkt ausgeführt.'}),
 el('details',{},[el('summary',{text:'Konzentration & Handelbarkeit'}),el('div',{class:'strategy-grid'},[input('maxPosition','Maximales Positionsgewicht · %',definition.portfolio.maxPositionWeight*100,{type:'number',step:'any'}),input('maxSector','Maximales Sektorgewicht · %',definition.portfolio.maxSectorWeight*100,{type:'number',step:'any'}),input('minVolume','Mindest-Handelsvolumen · Mio. USD',definition.portfolio.minDollarVolumeM,{type:'number',step:'any'}),input('minCap','Mindest-Marktkapitalisierung · Mio. USD',definition.portfolio.minMarketCapM,{type:'number',step:'any'})])])]),
 input('reason','Grund der Änderung',saved?'':'Erster Entwurf',{maxlength:'500'}),status);
 function build(){for(const [key,control] of Object.entries(fields))if(control.type==='number'&&(!control.value.trim()||!Number.isFinite(Number(control.value))||!control.checkValidity()))throw Error('Bitte alle Zahlenfelder gültig ausfüllen.');const number=id=>Number(fields[id].value);return VUStrategy.assertValid(VUStrategy.createDefinition({...definition,ranking:{factors:context.factors.filter(f=>number(f)>0).map(f=>({factor:f,weight:number(f)/100}))},portfolio:{...definition.portfolio,positions:number('positions'),weighting:fields.weighting.value,maxPositionWeight:number('maxPosition')/100,maxSectorWeight:number('maxSector')/100,minDollarVolumeM:number('minVolume'),minMarketCapM:number('minCap')},rebalance:fields.rebalance.value,execution:{timing:fields.timing.value,transactionCostsBps:number('cost'),slippageBps:number('slippage')}}));}
 const save=el('button',{class:'button',text:'Version speichern',onclick:()=>{try{const next=VUStrategyWorkspace.save(localStorage,{name:fields.name.value,definition:build(),reason:fields.reason.value});saved=next;history.textContent=JSON.stringify(next,null,2);fields.name.readOnly=true;S.mount(status,notice('Version '+next.strategy.latestVersion+' gespeichert','Dieser Entwurf liegt nur in diesem Browser. Vorherige Versionen bleiben erhalten.'));fields.reason.value='';}catch(e){S.mount(status,notice('Entwurf nicht gespeichert',/identical/.test(e.message)?'Die Definition ist unverändert. Es wurde keine zusätzliche Version angelegt.':/changeReason/.test(e.message)?'Bitte begründe die Änderung, damit die Version nachvollziehbar bleibt.':'Prüfe Zahlen, Gewichtungen und den Änderungsgrund. Faktoranteile müssen 100 % ergeben; Positionszahl und Konzentrationsgrenzen müssen zusammenpassen. Auch gesperrter Browserspeicher verhindert das Speichern.'));}}});
 const inspect=el('button',{class:'button secondary',text:'Aktuelle Kriterien prüfen',onclick:async()=>{try{const def=build(),query=VUScreenerWorkspace.build(def.filters),result=await api.screen(query);if(result.state!=='AVAILABLE')throw Error('SOURCE_UNAVAILABLE');S.mount(preview,el('div',{},[el('h2',{text:'Aktuelle Kriterien-Auswahl'}),el('p',{text:'Nur die Filter im freigegebenen Analysebereich. Kein historisches Ergebnis, kein Ranking und keine Portfolio-Zuteilung.'}),stockRows(result.stocks||[])]));}catch(e){S.mount(preview,notice('Auswahl noch nicht auswertbar','Prüfe die Definition und die unterstützten Screener-Kriterien.'));}}});
 fields.name.readOnly=!!saved;
 main.append(el('div',{class:'actions'},[save,inspect]),preview,el('section',{class:'section'},[el('h2',{text:'Vor einem historischen Test'}),el('p',{text:'Ein echter Backtest ist für diese Vorschau noch nicht freigegeben. Diese Prüfungen müssen gemeinsam bestanden sein:'}),...context.backtest.checks.map(([title,text])=>el('div',{class:'trust-row'},[el('strong',{text:title}),el('p',{class:'muted',text})]))]),el('details',{},[el('summary',{text:'Gespeicherte Versionen & Definition'}),history]),actions([{label:'Vollständiger Strategy Builder',href:'/quant/strategies/builder/'},{label:'Bestehende Backtest-Umgebung',href:'/quant/backtests/'}]));
}
async function quantPage(ticker){
 const data=await api.getQuantWorkspace(ticker);main.append(heading('Das Unternehmen in Zahlen',data.name||ticker));
 if(data.state!=='AVAILABLE'){main.append(notice('Kennzahlen derzeit nicht verfügbar','Die vorhandenen Quellen reichen für diese Ansicht nicht aus.'));return;}
 const company=el('select',{'aria-label':'Quant Unternehmen'},universe.stocks.map(s=>el('option',{value:s.ticker,text:s.ticker+' · '+s.name})));company.value=ticker;company.onchange=()=>location.assign(href('quant',company.value));
 const format=formatFactor;
 main.append(el('div',{class:'workspace-controls'},[company]),el('p',{class:'muted',text:'Geschäftsdaten bis '+data.fundamentalsAsOf+' · verfügbar seit '+data.availableAt+' · Kurse bis '+data.asOf}),
 el('nav',{class:'factor-nav','aria-label':'Faktorbereiche'},data.families.map(f=>link(f.label,'#factor-'+f.id))));
 for(const family of data.families){main.append(el('section',{class:'factor-section',id:'factor-'+family.id},[
  el('div',{},[el('span',{class:'eyebrow',text:family.label}),el('h2',{text:family.question})]),
  el('div',{class:'factor-evidence'},family.metrics.map(m=>el('div',{class:'factor-metric'},[el('div',{},[el('span',{text:m.label}),el('strong',{text:format(m)})]),el('details',{},[el('summary',{text:'Definition & Datenstand'}),el('p',{text:m.description||'Bestehender Faktor-Rohwert; vollständige Definition und Herkunft im Dateninspektor.'}),el('p',{class:'muted',text:'Stand '+m.asOf+' · Kennzahl '+m.metricId+' · '+m.owner+' · '+m.panelVersion})])])))]));}
 main.append(notice('Einordnen ohne scheinpräzisen Rang','Diese fünf Unternehmen bilden keine ausreichend große Vergleichsgruppe. Deshalb gibt es hier keinen Quant Score und keine Marktperzentile. Die Kennzahlen beschreiben vorhandene Daten; sie sind keine Empfehlung.'),el('details',{},[el('summary',{text:'Historischer Kontext & Methodik'}),el('p',{text:'Aktuelle Faktor-Rohwerte sind kein historischer Backtest. Bewertung verbindet Geschäftsdaten mit dem angegebenen Kursstand. Unterschiedliche Berichtsperioden und branchenspezifische Definitionen müssen bei Vergleichen berücksichtigt werden.'})]),actions([{label:'Fundamental-Historie',href:href('fundamentals',ticker)},{label:'Vergleichen',href:href('compare',ticker)},{label:'Dateninspektor',href:data.methodologyHref},{label:'Bestehender Quant Workspace',href:data.legacyHref}]));
}
async function fundamentalsPage(){
 main.append(heading('Wie entwickelt sich das Geschäft?','Geschäftszahlen über die Zeit verstehen – mit Berichtszeiträumen und nachvollziehbarer Herkunft.'));
 const company=el('select',{'aria-label':'Unternehmen'},universe.stocks.map(s=>el('option',{value:s.ticker,text:s.ticker+' · '+s.name}))),metric=el('select',{'aria-label':'Fundamentale Kennzahl'},VUFundamentalsContract.metrics.map(m=>el('option',{value:m.id,text:m.label}))),period=el('select',{'aria-label':'Berichtsart'},[['annual','Geschäftsjahre'],['quarterly','Quartalsmeldungen'],['ttm','Letzte zwölf Monate (TTM)']].map(([value,text])=>el('option',{value,text}))),target=el('section',{'aria-live':'polite'});
 company.value=universe.stocks.some(s=>s.ticker===params.get('ticker'))?params.get('ticker'):'NVDA';
 main.append(el('div',{class:'filter history-controls'},[company,metric,period]),target);let request=0;
 async function update(){const current=++request;const result=await api.getHistoricalFundamentals(company.value,{metric:metric.value,period:period.value});if(current!==request)return;S.clear(target);
  if(result.state!=='AVAILABLE'){target.append(notice(result.reason==='TTM_NOT_VALIDATED'?'TTM noch nicht verfügbar':result.reason==='PERIOD_SEMANTICS_NOT_VALIDATED'?'Quartalsabgrenzung noch nicht bestätigt':'Historie derzeit nicht verfügbar',result.reason==='TTM_NOT_VALIDATED'?'Für diese Ansicht liegt noch keine validierte Zwölfmonats-Reihe vor. Geschäftsjahre und Quartalsmeldungen bleiben zugänglich.':result.reason==='PERIOD_SEMANTICS_NOT_VALIDATED'?'Die vorhandenen abgeleiteten Werte lassen sich noch nicht sicher einem einzelnen Quartal zuordnen. Die Geschäftsjahres-Historie und der SEC-Dateninspektor bleiben verfügbar.':'Es fehlen belastbare Daten für diese Auswahl. Werte werden nicht ersetzt oder geschätzt.'));return;}
  const known=result.rows.filter(r=>r.state==='AVAILABLE'),latest=known.at(-1),scale=result.metric.unit==='USD/shares'?1:1e9,unit=result.metric.unit==='USD/shares'?'USD je Aktie':result.metric.unit==='shares'?'Mrd. Aktien':'Mrd. USD';
  const value=r=>(r.value/scale).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
  target.append(el('div',{class:'history-header'},[el('div',{},[el('span',{class:'eyebrow',text:result.name}),el('h2',{text:result.metric.label}),el('div',{class:'quote',text:value(latest)+' '+unit}),el('p',{class:'muted',text:latest.label+' · '+(latest.start?latest.start+' bis ':'Stichtag ')+latest.end})]),el('p',{class:'muted',text:'Aktuell bekannter Berichtsstand. Frühere Angaben können nachträglich angepasst sein.'})]));
  target.append(QuantCharts.barChart({title:result.metric.label+' nach Berichtsperiode',description:'Verfügbare gemeldete Werte. Exakte Zahlen und fehlende Perioden stehen in der Tabelle.',width:Math.min(1100,innerWidth-40),maxLabels:innerWidth<650?3:8,height:300,items:known.map(r=>({label:period.value==='annual'?String(r.fiscalYear):r.fiscalPeriod+' '+String(r.fiscalYear).slice(-2),value:r.value/scale})),yFormat:v=>v.toLocaleString('de-DE',{maximumFractionDigits:1})}),el('p',{class:'muted',text:'Skala: '+unit+' · '+known.length+' verfügbare Berichtsperioden. '+result.missing+' Perioden ohne darstellbaren Wert.'}));
  if(period.value==='quarterly')target.append(notice('Berichtszeitraum beachten','Gezeigt werden direkt gemeldete Werte mit ihrem Quellenzeitraum. Dieser kann seit Geschäftsjahresbeginn kumuliert sein. Abgeleitete Quartalswerte bleiben ausgeblendet, solange ihre zeitliche Abgrenzung nicht bestätigt ist.'));
  const body=result.rows.slice().reverse().map(r=>el('tr',{},[el('th',{scope:'row',text:r.label}),el('td',{text:r.state==='AVAILABLE'?value(r)+' '+unit:r.state==='PIPELINE_ERROR'?'Datenprüfung erforderlich':r.reason==='PERIOD_SEMANTICS_NOT_VALIDATED'?'Quartalsabgrenzung offen':'Nicht verfügbar'}),el('td',{text:r.state==='AVAILABLE'?(r.start?r.start+' → ':'')+r.end:'—'}),el('td',{text:r.state==='AVAILABLE'?r.availableFrom.replace('T',' ').replace('.000Z',' UTC'):'—'})]));
  target.append(el('h2',{class:'section',text:'Die Zahlen im Detail'}),el('div',{class:'table-wrap',tabindex:'0','aria-label':'Historische Geschäftszahlen, horizontal scrollbar'},[el('table',{},[el('thead',{},[el('tr',{},['Berichtsperiode',result.metric.label,'Zeitraum / Stichtag','Bekannt seit · Originalzeitpunkt'].map(text=>el('th',{scope:'col',text})))]),el('tbody',{},body)])]),el('details',{},[el('summary',{text:'Quellen und Methodik'}),el('p',{text:'Diese rückblickende Ansicht ist kein damaliger Informationsstand für Backtests. Quelle: SEC EDGAR. Stand der Aufbereitung: '+result.generatedAt.slice(0,10)+'. Gemeldete und bereits im bestehenden SEC-Workstream abgeleitete Werte werden unverändert übernommen.'}),el('p',{text:'Letzter Wert, ungerundet: '+latest.value.toLocaleString('de-DE',{maximumFractionDigits:12})+' '+latest.unit+'. Meldung: '+latest.accession+'. '+(latest.source==='VISION_UNIVERSE_DERIVED'?'Abgeleitete Kennzahl nach vorhandener SEC-Methodik.':'Gemeldete SEC-Kennzahl.')})]),actions([{label:'Alle Quellen im Dateninspektor',href:'/quant/data-inspector/'},{label:'Zur Aktienanalyse',href:href('stock',company.value)}]));
 }
 company.onchange=metric.onchange=period.onchange=update;await update();
}
async function marketsPage(){
 const market=await api.getMarketIntelligence();
 main.append(heading('Den Markt einordnen','Kursstrukturen untersuchen. Den Kontext verstehen. Die Evidenz prüfen.'),notice('Gesamtmarkt-Einordnung noch nicht verfügbar','Die freigegebene Vorschau umfasst fünf Unternehmen. Ihre Entwicklung beschreibt nicht die Marktbreite oder das Marktregime.'));
 const rows=el('section',{class:'section'},[el('h2',{text:'Trendradar · verfügbarer Analysebereich'}),el('p',{class:'muted',text:'Ein Kurs über seinen Durchschnittslinien beschreibt seine bisherige Position. Er ist kein Kaufsignal.'})]);
 for(const {stock,trend} of market.observations){rows.append(el('article',{class:'market-observation'},[el('div',{},[link(stock.ticker,href('stock',stock.ticker),'stock-link'),el('p',{class:'muted',text:stock.name})]),el('div',{},[el('h3',{text:trend.label}),el('p',{class:'muted',text:'Kursstand: '+stock.asOf}),el('details',{},[el('summary',{text:'Warum?'}),el('p',{text:trend.explanation||'Für die Einordnung fehlen belastbare Kennzahlen.'}),...(trend.evidence||[]).map(e=>el('p',{text:e.label+': '+n(e.metric)})),link('Vollständige Analyse öffnen','/quant/technical/?symbol='+stock.ticker)])]),el('div',{class:'number'},[el('span',{class:'muted',text:'6 Monate'}),el('strong',{text:n(stock.momentum6m)})])]));}
 if(!market.observations.length)rows.append(notice('Titel derzeit nicht verfügbar','Die zugrunde liegenden Daten konnten nicht geladen werden.'));
 main.append(rows,el('section',{class:'section'},[el('h2',{text:'Das größere Bild'}),actions([{label:'Macro Intelligence',href:'/macro/'},{label:'ETF Research & Vergleich',href:'/etf/'},{label:'Aktuelle Nachrichten',href:'/news/'}])]));
}
async function discoverPage(){
 main.append(heading('Eine Idee ist der Anfang','Entdecke Unternehmen anhand sichtbarer Kriterien. Öffne jede Auswahl im Screener und entwickle sie weiter.'));
 const data=await api.getDiscover();
 main.append(el('p',{class:'scope-note',text:'Aktuell verfügbarer Analysebereich: fünf Unternehmen. Diese Auswahlen sind keine Rangliste des Gesamtmarkts.'}));
 for(const collection of data.collections){
  const result=collection.result;
  const title=el('div',{},[el('span',{class:'eyebrow',text:'Entdecken · '+(result.state==='AVAILABLE'?result.stocks.length+' Treffer':'Daten fehlen')}),el('h2',{text:collection.title}),el('p',{class:'muted',text:collection.explanation}),el('p',{class:'recipe-rule',text:collection.rule}),link('Regeln im Screener bearbeiten',href('screener')+'&recipe='+encodeURIComponent(collection.id),'button secondary')]);
  const evidence=result.state==='AVAILABLE'?(result.stocks.length?stockRows(result.stocks,collection.field==='priceTo200dma'?'above200':collection.field,collection.field==='revenueGrowth'?'Umsatzwachstum':collection.field==='priceTo200dma'?'Abstand 200T':'6 Monate'):notice('Aktuell keine Treffer','Das Kriterium trifft auf kein Unternehmen im verfügbaren Analysebereich zu. Du kannst es im Screener verändern.')):notice('Auswahl derzeit nicht verfügbar','Die zugrunde liegenden Daten konnten nicht geladen werden.');
  main.append(el('section',{class:'collection'},[title,el('div',{},[evidence])]));
 }
}
async function screenPage(){
 main.append(heading('Aus einer Idee wird deine Auswahl','Kombiniere Geschäftsentwicklung und Kursstruktur. Alle Kriterien müssen gleichzeitig erfüllt sein.'));
 const editor=VUScreenerWorkspace,recipe=api.getRecipes().find(r=>r.id===params.get('recipe'));
 let initial=recipe?.query||editor.build([{field:'momentum6m',operator:'gte',value:0,scale:'raw'}]),invalidLink=false;
 try{if(params.has('recipe')&&!recipe)throw Error('unknown recipe');if(params.has('query'))initial=editor.decode(params.get('query'));else if(params.has('field')||params.has('threshold'))initial=editor.build([{field:params.get('field')||'momentum6m',operator:'gte',value:Number(params.get('threshold')||0),scale:'raw'}]);}catch{invalidLink=true;main.append(notice('Gespeicherte Regeln konnten nicht geöffnet werden','Die Abfrage enthält ungültige oder in diesem Editor nicht unterstützte Kriterien. Es wurden keine Ersatzregeln ausgeführt. Erstelle hier eine neue Auswahl oder öffne den vollständigen Screener.'));}
 if(recipe)main.append(el('p',{class:'scope-note',text:'Aus Discover: '+recipe.title+'. Alle Kriterien bleiben veränderbar.'}));
 const ruleList=el('div',{class:'rule-list'}),out=el('section',{'aria-live':'polite'}),method=el('pre',{class:'query-code'}),share=link('Diese Auswahl erneut öffnen','#','button secondary'),strategyLink=link('Als Strategie weiterentwickeln','#','button secondary'),sort=el('select',{'aria-label':'Sortieren nach'},editor.fields.map(f=>el('option',{value:f.id,text:f.label}))),direction=el('select',{'aria-label':'Sortierreihenfolge'},[['desc','Absteigend'],['asc','Aufsteigend']].map(([value,text])=>el('option',{value,text})));let rows=[],request=0;strategyLink.hidden=true;
 sort.value=initial.sort[0].field;direction.value=initial.sort[0].direction;
 function addRule(filter={field:'revenueGrowth',operator:'gte',value:0,scale:'raw'}){
  if(rows.length>=editor.maxFilters)return;
  const field=el('select',{'aria-label':'Kennzahl'},editor.fields.map(f=>el('option',{value:f.id,text:f.label}))),op=el('select',{'aria-label':'Vergleich'},editor.operators.map(o=>el('option',{value:o.id,text:o.label}))),value=el('input',{type:'number',step:'any',value:String(filter.value),'aria-label':'Vergleichswert'}),unit=el('span',{class:'muted'}),row=el('div',{class:'rule'});
  field.value=filter.field;op.value=filter.operator;const item={row,field,op,value};rows.push(item);
  function unitLabel(){unit.textContent=editor.fields.find(f=>f.id===field.value).unit==='usd'?'USD':'%';}field.onchange=unitLabel;unitLabel();
  row.append(field,op,value,unit,el('button',{text:'Entfernen',class:'remove-rule','aria-label':'Kriterium entfernen',onclick:()=>{rows=rows.filter(r=>r!==item);row.remove();}}));ruleList.append(row);
 }
 initial.filters.forEach(addRule);
 const apply=async()=>{const current=++request;try{
  const filters=rows.map(r=>{if(!r.value.value.trim()||!Number.isFinite(Number(r.value.value)))throw Error('invalid');return {field:r.field.value,operator:r.op.value,value:Number(r.value.value),scale:'raw'};});
  const query=editor.build(filters,[{field:sort.value,direction:direction.value}]);const result=await api.screen(query);if(current!==request)return;S.clear(out);
  share.hidden=false;strategyLink.hidden=false;strategyLink.href=href('strategies')+'&query='+encodeURIComponent(editor.encode(query));method.textContent=JSON.stringify(query,null,2);share.href=href('screener')+'&query='+encodeURIComponent(editor.encode(query));
  if(result.state!=='AVAILABLE'){out.append(notice('Ergebnisse derzeit nicht verfügbar','Die Daten konnten nicht geladen werden. Deine Kriterien bleiben erhalten.'));return;}
  const selected=editor.fields.find(f=>f.id===sort.value);
  out.append(el('p',{class:'muted',text:result.stocks.length+' Treffer in '+result.eligible+' verfügbaren Unternehmen · kein Gesamtmarkt-Ranking'}),stockRows(result.stocks,selected.productKey,selected.label));
 }catch{if(current===request){share.hidden=true;strategyLink.hidden=true;method.textContent='';S.mount(out,notice('Kriterium prüfen','Gib für jedes Kriterium einen gültigen Zahlenwert ein. Die Regeln wurden nicht angewendet.'));}}};
 main.append(ruleList,el('div',{class:'actions'},[el('button',{class:'button secondary',text:'Kriterium hinzufügen',onclick:()=>addRule()}),el('button',{class:'button',text:'Anwenden',onclick:apply})]),el('div',{class:'filter'},[el('span',{text:'Ergebnisse sortieren'}),sort,direction]),out,el('details',{},[el('summary',{text:'Regeln speichern & Methodik'}),el('p',{text:'Der Link enthält ausschließlich die Regeln. Ergebnisse werden beim Öffnen mit dem dann verfügbaren Datenstand neu berechnet. Keine historische Simulation.'}),share,strategyLink,el('p',{class:'muted',text:'Die bestehende Query Engine prüft dieselben Kriterien wie im professionellen Screener. Die Vorschau bleibt auf den bestehenden Analysebereich begrenzt.'}),method]),actions([{label:'Vollständigen Screener öffnen',href:'/quant/screener/'}]));
 sort.onchange=direction.onchange=apply;ruleList.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();apply();}});if(!invalidLink)await apply();else share.hidden=true;
}
async function render(){universe=await api.getUniverse();
 if(view==='home')await homePage();
 else if(view==='stock')await stockPage(params.get('ticker')||'NVDA');
 else if(view==='technical'||view==='elliott')await technicalWorkspacePage(params.get('ticker')||'NVDA',view==='elliott');
 else if(view==='quant')await quantPage(params.get('ticker')||'NVDA');
 else if(view==='fundamentals')await fundamentalsPage();
 else if(view==='markets')await marketsPage();
 else if(view==='discover')await discoverPage();
 else if(view==='screener')await screenPage();
 else if(view==='research'){main.append(heading('Research ohne Umwege','Deine Workspaces. Von der ersten Frage bis zur vollständigen Analyse.'),el('div',{class:'catalog'},groups.map(([title,desc,links])=>el('section',{},[el('h2',{text:title}),el('p',{text:desc}),el('div',{class:'links'},links.map(([label,url])=>link(label,url)))]))));}
 else if(view==='compare'){main.append(heading('Unternehmen vergleichen','Dieselben Kennzahlen. Derselbe verfügbare Datenumfang.'));const one=el('select',{'aria-label':'Erstes Unternehmen'}),two=el('select',{'aria-label':'Zweites Unternehmen'});for(const s of universe.stocks){one.append(el('option',{value:s.ticker,text:s.ticker}));two.append(el('option',{value:s.ticker,text:s.ticker}));}one.value=params.get('ticker')||'NVDA';two.value='MSFT';const target=el('div',{class:'table-wrap'});function compare(){const a=universe.stocks.find(s=>s.ticker===one.value),b=universe.stocks.find(s=>s.ticker===two.value);if(!a||!b)return;S.mount(target,el('table',{},[el('thead',{},[el('tr',{},['Kennzahl',a.ticker,b.ticker].map(text=>el('th',{text})))]),el('tbody',{},[['Kursentwicklung 6M','momentum6m'],['Umsatzwachstum','revenueGrowth'],['Operative Marge','operatingMargin'],['FCF-Marge','fcfMargin'],['ROIC','roic'],['Größter Rückgang · 1J','drawdown']].map(([label,key])=>el('tr',{},[el('td',{text:label}),el('td',{text:n(a[key])}),el('td',{text:n(b[key])})])))]));}one.onchange=two.onchange=compare;main.append(el('div',{class:'filter'},[one,el('span',{text:'mit'}),two]),target);compare();}
 else if(view==='strategies')await strategyPage();
 else if(view==='portfolio')await portfolioPage();
 else if(view==='watchlist')await watchlistPage();
 else if(view==='atlas')await atlasPage();
 else if(view==='signals')await signalsPage();
 else if(view==='stocks'){main.append(heading('Unternehmen untersuchen','Fünf Unternehmen im aktuell verfügbaren Analysebereich.'),stockRows(universe.stocks));}
 else {main.append(heading(view==='markets'?'Märkte verstehen':'Das Wichtigste im Blick','Daten einordnen. Zusammenhänge erkennen. Weiterforschen.'));const focus=universe.stocks.find(s=>s.ticker==='NVDA');const left=el('section',{},[notice('Gesamtmarkt noch nicht eingeordnet','Die aktuelle Ansicht deckt '+universe.stocks.length+' Unternehmen ab. Daraus lässt sich keine belastbare Marktbreite ableiten.'),el('div',{class:'section'},[el('h2',{text:'Unternehmen im Blick'}),stockRows(universe.stocks)])]);const right=el('aside',{},[el('span',{class:'eyebrow',text:'Analyse vertiefen'}),el('h2',{text:focus?'NVIDIA':'Research'}),el('p',{class:'muted',text:'Wie entwickeln sich Geschäft und Kurs? Die Aktienanalyse verbindet Kennzahlen mit ihren Quellen.'}),focus?evidence(focus):null,link('Aktie untersuchen',href('stock','NVDA'),'button'),el('div',{class:'section links'},[link('Ideen entdecken',href('discover')),link('Makro-Zusammenhänge','/macro/'),link('Morning Briefing','/morning/'),link('News im Kontext','/news/'),link('Ask Atlas',href('atlas'))])]);main.append(el('div',{class:'layout'},[left,right]));}
 main.append(el('footer',{class:'footer',text:'Vision Universe® · Entwicklungsvorschau · Bestehender freigegebener Analysebereich. Kurse: letzter verfügbarer EOD-Stand, nicht realtime. '+(universe.stocks[0]?.asOf?'Kursstand: '+universe.stocks[0].asOf+'. ':'')+'Keine Anlageempfehlung.'}));
}
render().catch(()=>main.append(notice('Ansicht derzeit nicht verfügbar','Die Daten konnten nicht geladen werden. Bitte versuche es erneut.')));
})();
