// Explicitly requested static-repository QA. No deployment or provider calls.
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const root=resolve(process.cwd()),out=resolve(process.env.VU_QA_OUTPUT||'../vu2-evidence/experience');
await mkdir(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname.split('/').some(s=>s.startsWith('.')))throw Error('private');if(pathname.endsWith('/'))pathname+='index.html';const file=resolve(root,'.'+pathname);if(!file.startsWith(root+sep))throw Error('path');res.setHeader('Content-Type',mime[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.statusCode=404;res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const origin='http://127.0.0.1:'+server.address().port;const checks=[],performanceSamples=[];
try{for(const width of [1440,390]){const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const view of ['home','stock','technical','elliott','quant','fundamentals','discover','research','markets','screener','compare','strategies','signals','portfolio','watchlist','atlas']){
 const started=performance.now();await page.goto(origin+'/vu2/?view='+view+'&ticker=NVDA');await page.locator('main footer').waitFor();
 const resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(r=>({path:new URL(r.name).pathname,bytes:r.decodedBodySize,durationMs:Math.round(r.duration)})));performanceSamples.push({view,width,renderMs:Math.round(performance.now()-started),decodedBytes:resources.reduce((sum,r)=>sum+r.bytes,0),requests:resources.length});
 if(view==='home'&&resources.some(r=>r.path.includes('/daily/ref_')||r.path.includes('/fixtures/')))throw Error('Home loads raw history or fixtures');
 if(await page.locator('h1').count()!==1)throw Error('missing heading '+view);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow)throw Error('page overflow '+view+' '+width);
 if(view==='home'){await page.locator('.market-freshness').getByText(/Neuere Tagesdaten fehlen/).waitFor();if(await page.locator(width===390?'.mobile-nav':'.nav').getByRole('link',{name:'Discover',exact:true}).getAttribute('href')!=='/discover/')throw Error('current main Discover not integrated');if(await page.locator('a.row').count()!==5)throw Error('real scope missing');await page.getByText('Kurse: letzter verfügbarer Tagesstand',{exact:true}).waitFor();await page.getByRole('link',{name:'Watchlist zusammenstellen',exact:true}).waitFor();await page.getByRole('button',{name:'Suche',exact:true}).click();await page.getByRole('textbox',{name:'Suche',exact:true}).fill('NVDA');await page.getByRole('dialog').getByRole('link',{name:/NVDA/}).waitFor();await page.getByRole('button',{name:'Schließen'}).click();
  await page.route('**/quant/config/market-calendar.json',route=>route.abort());await page.reload();await page.locator('main footer').waitFor();await page.getByText('Handelsphase nicht bestätigt',{exact:true}).waitFor();if(await page.locator('a.row').count()!==5)throw Error('calendar outage hid research');await page.unroute('**/quant/config/market-calendar.json');await page.reload();await page.locator('main footer').waitFor();
 }
 if(view==='stock'){await page.locator('.market-freshness').getByText(/Neuere Tagesdaten fehlen/).waitFor();if(await page.locator('[data-stock-family]').count()!==4||await page.locator('.stock-evidence-metric').count()!==8)throw Error('stock business evidence missing');await page.locator('[data-stock-family=quality]').getByText('65,21 %',{exact:true}).waitFor();await page.locator('[data-stock-family=growth]').getByText('83,38 %',{exact:true}).waitFor();await page.locator('[data-stock-family=risk]').getByText('38,07 %',{exact:true}).waitFor();await page.getByText('Warum ist das relevant?',{exact:true}).first().click();await page.getByRole('heading',{name:'Technical Intelligence',exact:true}).waitFor();await page.getByRole('heading',{name:'Aufwärtstrend',exact:true}).waitFor();await page.getByRole('button',{name:'Max',exact:true}).click();if(await page.locator('.q-chart').count()!==1)throw Error('MAX chart missing');await page.getByRole('button',{name:'1J',exact:true}).click();}
 if(view==='technical'||view==='elliott'){await page.locator('.technical-chart-host svg').waitFor();await page.getByRole('combobox',{name:'Chart-Zeitraum',exact:true}).selectOption('MAX');await page.getByRole('checkbox',{name:'Alternativen im Chart'}).check();const labels=page.getByRole('checkbox',{name:'Chart-Beschriftungen'});await labels.check();if(!await page.locator('.technical-chart-host .ann-label:not(.ann-now-label)').count())throw Error('chart labels missing');if(width===390)await labels.uncheck();await page.getByRole('heading',{name:'Szenarien & Invalidation',exact:true}).waitFor();await page.getByRole('heading',{name:'Alternative Zählung',exact:true}).waitFor();await page.getByText('Vollständige Zählung & Regeln',{exact:true}).first().click();if(await page.locator('.wave-count').first().locator('tbody tr').count()<40)throw Error('wave count truncated');await page.getByText('Vollständige Zählung & Regeln',{exact:true}).first().click();await page.getByRole('combobox',{name:'Chart-Zeitraum',exact:true}).selectOption('1Y');}
 if(view==='quant'){if(await page.locator('.factor-section').count()!==5||await page.locator('.factor-metric').count()!==18)throw Error('quant evidence missing');await page.getByText('Definition & Datenstand',{exact:true}).first().click();await page.getByRole('combobox',{name:'Quant Unternehmen'}).selectOption('JPM');await page.locator('main footer').waitFor();await page.getByRole('combobox',{name:'Quant Unternehmen'}).selectOption('NVDA');await page.locator('main footer').waitFor();await page.getByText('Definition & Datenstand',{exact:true}).first().click();await page.getByText('Anteil des operativen Gewinns am Umsatz der letzten vier vollständigen Berichtsperioden.',{exact:true}).waitFor();}
 if(view==='strategies'){const query=await page.evaluate(()=>VUScreenerWorkspace.build([{field:'momentum6m',operator:'gte',value:10,scale:'raw'},{field:'revenueGrowth',operator:'gte',value:20,scale:'raw'}]));await page.goto(origin+'/vu2/?view=strategies&query='+encodeURIComponent(JSON.stringify(query)));await page.locator('main footer').waitFor();if(await page.locator('.strategy-rules p').count()!==2)throw Error('strategy rules lost');await page.getByRole('button',{name:'Version speichern',exact:true}).click();await page.getByRole('heading',{name:'Version 1 gespeichert',exact:true}).waitFor();await page.locator('#strategy-slippage').fill('10');await page.locator('#strategy-reason').fill('Konservativere Ausführung');await page.getByRole('button',{name:'Version speichern',exact:true}).click();await page.getByRole('heading',{name:'Version 2 gespeichert',exact:true}).waitFor();await page.reload();await page.locator('main footer').waitFor();if(await page.locator('#strategy-slippage').inputValue()!=='10')throw Error('strategy version not restored');await page.getByRole('button',{name:'Aktuelle Kriterien prüfen',exact:true}).click();await page.getByRole('heading',{name:'Aktuelle Kriterien-Auswahl',exact:true}).waitFor();if(await page.locator('a.row').count()!==1)throw Error('strategy filter mismatch');await page.route('**/quant/data/sec/quant-factor-inputs.json',route=>route.abort());await page.reload();await page.locator('main footer').waitFor();await page.getByRole('button',{name:'Aktuelle Kriterien prüfen',exact:true}).click();await page.getByRole('heading',{name:'Auswahl noch nicht auswertbar',exact:true}).waitFor();if(await page.locator('a.row').count())throw Error('unavailable strategy source rendered as selection');await page.unroute('**/quant/data/sec/quant-factor-inputs.json');await page.reload();await page.locator('main footer').waitFor();}
 if(view==='portfolio'){await page.getByRole('heading',{name:'Noch keine Positionen',exact:true}).waitFor();await page.getByRole('textbox',{name:'Position Ticker'}).fill('NVDA');await page.getByRole('spinbutton',{name:'Stückzahl'}).fill('10');await page.getByRole('button',{name:'Position übernehmen',exact:true}).click();await page.getByRole('button',{name:'Bestände speichern',exact:true}).click();await page.getByRole('heading',{name:'Bestände gespeichert',exact:true}).waitFor();await page.reload();await page.locator('main footer').waitFor();if(await page.locator('.holding').count()!==1)throw Error('holdings not restored');await page.getByRole('textbox',{name:'Position Ticker'}).fill('TSLA');await page.getByRole('spinbutton',{name:'Stückzahl'}).fill('1');await page.getByRole('button',{name:'Position übernehmen',exact:true}).click();await page.locator('.portfolio-total .quote').getByText('Nicht verfügbar',{exact:true}).waitFor();await page.getByRole('button',{name:'TSLA entfernen',exact:true}).click();await page.getByRole('button',{name:'Bearbeiten',exact:true}).click();await page.getByRole('spinbutton',{name:'Stückzahl'}).fill('12');await page.getByRole('button',{name:'Position übernehmen',exact:true}).click();await page.getByRole('button',{name:'Bestände speichern',exact:true}).click();await page.reload();await page.locator('main footer').waitFor();await page.locator('.portfolio-total .quote').getByText(/2\.708,76/).waitFor();}
 if(view==='signals'){await page.getByRole('heading',{name:'Keine belegten Wechsel in diesem Ausschnitt',exact:true}).waitFor();await page.getByRole('combobox',{name:'Signal-Zeitraum'}).selectOption('60');await page.locator('main footer').waitFor();if(await page.locator('.signal-event').count()!==4)throw Error('historical transitions missing');await page.getByRole('combobox',{name:'Signals Unternehmen'}).selectOption('MSFT');if(await page.locator('.signal-event').count()!==2)throw Error('signal company filter failed');await page.getByText('Warum wurde der Wechsel erkannt?',{exact:true}).first().click();await page.getByRole('link',{name:'Regel im Screener untersuchen',exact:true}).first().click();await page.locator('main footer').waitFor();if(await page.getByRole('combobox',{name:'Kennzahl'}).inputValue()!=='momentum6m')throw Error('signal rule handoff lost');await page.goto(origin+'/vu2/?view=signals&window=60');await page.locator('main footer').waitFor();await page.getByRole('combobox',{name:'Signals Unternehmen'}).selectOption('MSFT');}
 if(view==='fundamentals'){await page.locator('.q-chart .bar').first().waitFor();await page.getByRole('combobox',{name:'Berichtsart'}).selectOption('ttm');await page.getByText('TTM noch nicht verfügbar',{exact:true}).waitFor();await page.getByRole('combobox',{name:'Berichtsart'}).selectOption('quarterly');await page.getByText('Berichtszeitraum beachten',{exact:true}).waitFor();await page.getByRole('combobox',{name:'Fundamentale Kennzahl'}).selectOption('free_cash_flow');await page.getByText('Quartalsabgrenzung noch nicht bestätigt',{exact:true}).waitFor();await page.getByRole('combobox',{name:'Berichtsart'}).selectOption('annual');await page.getByRole('rowheader',{name:'FY 2016',exact:true}).waitFor();await page.getByRole('combobox',{name:'Fundamentale Kennzahl'}).selectOption('revenue');await page.getByRole('heading',{name:'Umsatz',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Fundamentale Kennzahl'}).selectOption('net_income');await page.getByRole('combobox',{name:'Berichtsart'}).selectOption('ttm');await page.getByText('TTM noch nicht verfügbar',{exact:true}).waitFor();const saved=await page.getByRole('link',{name:'Diese Historie erneut öffnen',exact:true}).getAttribute('href');await page.goto(origin+saved);await page.getByText('TTM noch nicht verfügbar',{exact:true}).waitFor();if(await page.getByRole('combobox',{name:'Fundamentale Kennzahl'}).inputValue()!=='net_income'||await page.getByRole('combobox',{name:'Unternehmen',exact:true}).inputValue()!=='NVDA')throw Error('history link lost state');
  await page.goto(origin+'/vu2/?view=fundamentals&ticker=TSLA');await page.getByText('Historie derzeit nicht verfügbar',{exact:true}).waitFor();if(await page.getByRole('combobox',{name:'Unternehmen',exact:true}).inputValue()!=='TSLA'||await page.locator('.q-chart').count())throw Error('history silently substituted a company');
  await page.goto(origin+'/vu2/?view=fundamentals&ticker=NVDA&metric=unknown');await page.getByText('Historienauswahl prüfen',{exact:true}).waitFor();if(await page.locator('.q-chart').count())throw Error('invalid metric rendered fallback');await page.goto(origin+'/vu2/?view=fundamentals&ticker=NVDA');await page.getByRole('heading',{name:'Umsatz',exact:true}).waitFor();}
 if(view==='research'){for(const href of await page.locator('.catalog a').evaluateAll(links=>links.map(a=>a.href))){const response=await page.request.get(href);if(!response.ok())throw Error('workspace link unavailable '+href);}}
 if(view==='markets'){if(await page.locator('.market-observation').count()!==5)throw Error('market observations missing');await page.getByText('Warum?',{exact:true}).first().click();await page.getByText(/Abstand zum 200-Tage-Durchschnitt:/).first().waitFor();}
 if(view==='discover'){if(await page.locator('.collection').count()!==3)throw Error('collections missing');await page.getByRole('link',{name:'Regeln im Screener bearbeiten'}).nth(1).click();await page.locator('main footer').waitFor();if(await page.getByRole('combobox',{name:'Kennzahl'}).inputValue()!=='revenueGrowth'||await page.getByRole('spinbutton').inputValue()!=='20')throw Error('recipe handoff lost');await page.goto(origin+'/vu2/?view=discover');await page.locator('main footer').waitFor();}
 if(view==='screener'){await page.getByRole('spinbutton').fill('999');await page.getByRole('button',{name:'Anwenden'}).click();await page.getByText('0 Treffer in 5 verfügbaren Unternehmen · kein Gesamtmarkt-Ranking').waitFor();await page.getByRole('spinbutton').fill('10');await page.getByRole('button',{name:'Kriterium hinzufügen'}).click();await page.getByRole('spinbutton').nth(1).fill('20');await page.getByRole('button',{name:'Anwenden'}).click();await page.getByText('1 Treffer in 5 verfügbaren Unternehmen · kein Gesamtmarkt-Ranking').waitFor();await page.getByText('Regeln speichern & Methodik',{exact:true}).click();const saved=await page.getByRole('link',{name:'Diese Auswahl erneut öffnen'}).getAttribute('href');await page.goto(origin+'/vu2/?view=screener&query=invalid');await page.locator('main footer').waitFor();if(await page.locator('a.row').count())throw Error('invalid rules silently replaced');await page.goto(origin+saved);await page.locator('main footer').waitFor();if(await page.getByRole('spinbutton').count()!==2)throw Error('saved rules lost');await page.getByText('1 Treffer in 5 verfügbaren Unternehmen · kein Gesamtmarkt-Ranking').waitFor();}
 if(view==='watchlist'){
  await page.getByRole('heading',{name:'Wen möchtest du beobachten?',exact:true}).waitFor();
  for(const ticker of ['NVDA','TSLA']){await page.getByRole('textbox',{name:'Watchlist Ticker'}).fill(ticker);await page.getByRole('button',{name:'Titel hinzufügen',exact:true}).click();}
  await page.getByRole('heading',{name:'Analyse noch nicht verfügbar',exact:true}).waitFor();
  await page.getByRole('button',{name:'Watchlist speichern',exact:true}).click();await page.reload();await page.locator('main footer').waitFor();if(await page.locator('.watchlist-member').count()!==2)throw Error('watchlist selection not preserved');
  await page.getByRole('button',{name:'TSLA aus Watchlist entfernen',exact:true}).click();await page.getByRole('button',{name:'Watchlist speichern',exact:true}).click();
  await page.getByRole('link',{name:'Historische Änderungen',exact:true}).click();await page.locator('main footer').waitFor();if(await page.getByRole('combobox',{name:'Signals Unternehmen'}).inputValue()!=='NVDA')throw Error('watchlist signal context lost');
  await page.goto(origin+'/vu2/?view=watchlist');await page.locator('main footer').waitFor();
  const saved=await page.evaluate(()=>{const key='vu2.watchlist.selection.v1',value=localStorage.getItem(key);localStorage.setItem(key,'broken');return value;});
  await page.reload();await page.getByRole('heading',{name:'Gespeicherte Watchlist nicht lesbar',exact:true}).waitFor();await page.getByRole('link',{name:'Bisherige Watchlist öffnen',exact:true}).waitFor();
  if(await page.evaluate(()=>localStorage.getItem('vu2.watchlist.selection.v1'))!=='broken')throw Error('corrupt watchlist overwritten');
  await page.evaluate(value=>localStorage.setItem('vu2.watchlist.selection.v1',value),saved);await page.reload();await page.locator('main footer').waitFor();await page.getByText('Warum diese Einordnung?',{exact:true}).click();
  if(await page.evaluate(()=>localStorage.getItem('vu.quant.watchlist.v1'))!==null)throw Error('legacy demo was seeded');
  await page.goto(origin+'/vu2/?view=home');await page.locator('main footer').waitFor();await page.locator('.home-watch-row').getByRole('link',{name:'NVDA',exact:true}).waitFor();await page.screenshot({path:out+'/home-personal-'+width+'.png',fullPage:true});await page.goto(origin+'/vu2/?view=watchlist');await page.locator('main footer').waitFor();await page.getByText('Warum diese Einordnung?',{exact:true}).click();
 }
 if(view==='compare'){
  if(await page.locator('.compare-table th[scope="row"]').count()!==18)throw Error('full comparison evidence missing');
  await page.getByRole('button',{name:'Unternehmen hinzufügen',exact:true}).click();await page.getByRole('button',{name:'Unternehmen hinzufügen',exact:true}).click();await page.locator('.compare-controls select').nth(3).waitFor();await page.getByRole('combobox',{name:'Vergleich Bereich'}).selectOption('growth');
  await page.getByRole('rowheader',{name:/Margenausweitung/}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('.compare-table td').length===16);
  const saved=await page.getByRole('link',{name:'Diese Auswahl erneut öffnen',exact:true}).getAttribute('href');await page.goto(origin+saved);await page.locator('main footer').waitFor();if(await page.locator('.compare-controls select').count()!==4)throw Error('comparison link lost selection');
  await page.goto(origin+'/vu2/?view=compare&tickers=NVDA,TSLA');await page.locator('main footer').waitFor();await page.getByRole('heading',{name:'Nicht alle Unternehmen auswertbar',exact:true}).waitFor();if(await page.locator('.compare-table thead th').count()!==3)throw Error('unavailable comparison column dropped');
  await page.goto(origin+'/vu2/?view=compare&tickers=NVDA,NVDA');await page.locator('main footer').waitFor();await page.getByRole('heading',{name:'Vergleichsauswahl prüfen',exact:true}).waitFor();
  await page.goto(origin+saved);await page.locator('main footer').waitFor();await page.getByRole('combobox',{name:'Vergleich Bereich'}).selectOption('quality');await page.getByRole('button',{name:'AAPL aus Vergleich entfernen',exact:true}).click();await page.getByRole('button',{name:'JPM aus Vergleich entfernen',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.compare-table thead th').length===3);await page.getByText('Definition',{exact:true}).first().click();
 }
 if(view==='atlas'){
  await page.getByText(/kein angeschlossenes Sprachmodell/).waitFor();await page.locator('.atlas-evidence').getByText('65,21 %',{exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Atlas Frage'}).selectOption('growth');await page.locator('.atlas-evidence').getByText('83,38 %',{exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Atlas Frage'}).selectOption('technical');await page.getByRole('heading',{name:'Die Kursstruktur von NVDA',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Atlas Unternehmen'}).selectOption('JPM');await page.getByRole('heading',{name:'Die Kursstruktur von JPM',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Atlas Frage'}).selectOption('quality');await page.getByRole('combobox',{name:'Atlas Unternehmen'}).selectOption('NVDA');await page.locator('.atlas-evidence').getByText('65,21 %',{exact:true}).waitFor();await page.getByText('Beleg & Definition',{exact:true}).first().click();
  const calls=await page.evaluate(async()=>{const tools=VUAtlasTools.create(VUProductServices.create({loadJSON:QuantShell.loadJSON,displayPolicy:VUDisplayPolicy,queryEngine:VUQuery}));return [await tools.call('runBacktest',{}),await tools.call('getQuantEvidence',{ticker:'TSLA'})];});if(calls[0].ok||calls[1].data.state==='AVAILABLE')throw Error('Atlas crossed execution/display scope');
 }
 await page.screenshot({path:out+'/'+view+'-'+width+'.png',fullPage:true});if(width===390){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/'+view+'-390-viewport.png'});}checks.push({view,width,pass:true});
 }
 await page.goto(origin+'/vu2/?view=does-not-exist');await page.getByRole('heading',{name:'Diese Ansicht wurde nicht gefunden',exact:true}).waitFor();if(await page.locator('h1').count()!==1)throw Error('unknown route kept a misleading view');await page.screenshot({path:out+'/not-found-'+width+'.png',fullPage:true});await page.getByRole('link',{name:'Research öffnen',exact:true}).click();await page.getByRole('heading',{name:'Research ohne Umwege',exact:true}).waitFor();checks.push({view:'unknown-workspace-recovery',width,pass:true});
 await page.route('**/quant/api/product-services.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+`
;{const original=VUProductServices.create;VUProductServices.create=(...args)=>({...original(...args),getHomeIntelligence:async()=>{throw Error('QA injected product rejection');}});}`});});
 await page.goto(origin+'/vu2/?view=home');await page.getByRole('heading',{name:'Ansicht derzeit nicht verfügbar',exact:true}).waitFor();if(await page.locator('h1').count()!==1||await page.locator('a.row').count())throw Error('failed render retained partial content');await page.screenshot({path:out+'/render-recovery-'+width+'.png',fullPage:true});await page.unroute('**/quant/api/product-services.js');await page.getByRole('link',{name:'Erneut versuchen',exact:true}).click();await page.getByRole('heading',{name:'Was ist für dich wichtig?',exact:true}).waitFor();checks.push({view:'render-failure-recovery',width,pass:true});
 await page.goto(origin+'/vu2/?view=stock&ticker=NVDA');await page.locator('main footer').waitFor();
 const visibleNav=page.locator(width===390?'.mobile-nav':'.nav');if(await visibleNav.getByRole('link',{name:'Research',exact:true}).getAttribute('aria-current')!=='location')throw Error('research context missing');
 await page.keyboard.press('Tab');if(!await page.locator('.skip').evaluate(e=>e===document.activeElement))throw Error('skip link not first');await page.keyboard.press('Enter');if(!await page.locator('main').evaluate(e=>e===document.activeElement))throw Error('skip target not focused');
 const searchButton=page.getByRole('button',{name:'Suche',exact:true});await searchButton.focus();await page.keyboard.press('Enter');const searchInput=page.getByRole('textbox',{name:'Suche',exact:true});await searchInput.fill('NVDA');await page.keyboard.press('Control+k');if(await searchInput.inputValue()!=='NVDA')throw Error('repeated command lost query');await page.getByRole('status').filter({hasText:'1 Treffer'}).waitFor();
 for(let i=0;i<12;i++){await page.keyboard.press(i<6?'Tab':'Shift+Tab');if(!await page.getByRole('dialog').evaluate(e=>e.contains(document.activeElement)))throw Error('focus escaped modal');}await page.keyboard.press('Escape');if(!await searchButton.evaluate(e=>e===document.activeElement))throw Error('search focus not restored');checks.push({view:'keyboard-navigation',width,pass:true});
 await page.goto(origin+'/quant/technical/?symbol=NVDA&layer=ELLIOTT');await page.locator('[role="tab"][data-layer="ELLIOTT"][aria-selected="true"]').waitFor();await page.locator('.q-tech-chart-wrap svg').waitFor();await page.getByRole('heading',{name:'Szenarien',exact:true}).waitFor();await page.getByRole('button',{name:'Alternative',exact:true}).click();await page.screenshot({path:out+'/elliott-preserved-'+width+'.png',fullPage:true});checks.push({view:'elliott-preserved',width,pass:true});
 await page.goto(origin+'/vu2/?view=home');await page.locator('main footer').waitFor();await page.keyboard.press('Control+k');await page.getByRole('dialog').waitFor();await page.getByRole('textbox',{name:'Suche',exact:true}).fill('NVDA');await page.getByRole('dialog').getByRole('link',{name:/NVDA/}).click();await page.locator('main footer').waitFor();await page.locator('.quote').getByText('225,73 $',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Full Chart',exact:true}).click();await page.locator('.q-chart').first().waitFor();await page.goBack();await page.locator('main footer').waitFor();
 for(const [name,heading] of [['Technical','Kursstruktur untersuchen'],['Elliott Wave','Elliott Wave · Szenarien verstehen'],['Historische Fundamentals','Wie entwickelt sich das Geschäft?'],['Quant','Das Unternehmen in Zahlen']]){await page.getByRole('link',{name,exact:true}).click();await page.getByRole('heading',{name:heading,exact:true}).waitFor();await page.goBack();await page.locator('main footer').waitFor();}
 await page.getByRole('link',{name:'Strategie definieren',exact:true}).click();await page.getByRole('heading',{name:'Vor einem historischen Test',exact:true}).waitFor();if(await page.getByRole('link',{name:'Bestehende Backtest-Umgebung',exact:true}).getAttribute('href')!=='/quant/backtests/')throw Error('professional backtest access lost');
 await page.goto(origin+'/vu2/?view=research');await page.locator('main footer').waitFor();const directory=await page.locator('.catalog a').evaluateAll(a=>a.map(x=>x.getAttribute('href')));for(const path of ['/discover/','/news/','/etf/','/macro/','/hedgefonds/','/analysten/','/morning/','/magazin/','/reports/xpeng/','/academy/','/quant/ranking/','/quant/screener/'])if(!directory.includes(path))throw Error('preserved workspace missing '+path);
 await page.keyboard.press('Control+k');await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');if(await page.getByRole('dialog').isVisible())throw Error('command dialog keyboard exit failed');checks.push({view:'guided-professional-journey',width,pass:true});
 if(errors.length)throw Error(errors.join('\n'));await page.close();}
 const tablet=await browser.newPage({viewport:{width:768,height:1024},deviceScaleFactor:1});for(const view of ['home','compare','research']){await tablet.goto(origin+'/vu2/?view='+view);await tablet.locator('main footer').waitFor();if(await tablet.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('tablet overflow '+view);const nav=tablet.locator('.nav');if(!await nav.isVisible()||await nav.locator('a').count()!==6)throw Error('tablet navigation incomplete');await tablet.screenshot({path:out+'/'+view+'-768.png',fullPage:true});checks.push({view,width:768,pass:true});}await tablet.close();
 await writeFile(out+'/results.json',JSON.stringify({checks},null,2));await writeFile(out+'/performance.json',JSON.stringify({environment:'GitHub Actions local static server; not production performance',samples:performanceSamples},null,2));console.log(JSON.stringify({passed:checks.length,output:out}));
}finally{await browser.close();await new Promise(r=>server.close(r));}
